/-
Aggregate for ErdosProblems.Erdos686.EvenK: imports the whole subtree so `lake build ErdosProblems.Erdos686.EvenK.All` builds it.
Generated by scripts/gen_aggregates.py — do not edit by hand.
-/
import ErdosProblems.Erdos686.EvenK.Base
import ErdosProblems.Erdos686.EvenK.FiniteTableDefs
import ErdosProblems.Erdos686.EvenK.K16
import ErdosProblems.Erdos686.EvenK.K18
import ErdosProblems.Erdos686.EvenK.K182024
import ErdosProblems.Erdos686.EvenK.K28
import ErdosProblems.Erdos686.EvenK.K32
import ErdosProblems.Erdos686.EvenK.Table20Cover
import ErdosProblems.Erdos686.EvenK.Table20P197
import ErdosProblems.Erdos686.EvenK.Table20P199
import ErdosProblems.Erdos686.EvenK.Table20P211
import ErdosProblems.Erdos686.EvenK.Table20P227
import ErdosProblems.Erdos686.EvenK.Table20P233
import ErdosProblems.Erdos686.EvenK.Table20P239
import ErdosProblems.Erdos686.EvenK.Table20P241
import ErdosProblems.Erdos686.EvenK.Table24Cover
import ErdosProblems.Erdos686.EvenK.Table24P13
import ErdosProblems.Erdos686.EvenK.Table24P131
import ErdosProblems.Erdos686.EvenK.Table24P157
import ErdosProblems.Erdos686.EvenK.Table24P191
import ErdosProblems.Erdos686.EvenK.Table24P197
import ErdosProblems.Erdos686.EvenK.Table24P227
import ErdosProblems.Erdos686.EvenK.Table24P239
import ErdosProblems.Erdos686.EvenK.Table24P241
import ErdosProblems.Erdos686.EvenK.Table24P71
import ErdosProblems.Erdos686.EvenK.K18.All
import ErdosProblems.Erdos686.EvenK.K22.All
import ErdosProblems.Erdos686.EvenK.K28.All
import ErdosProblems.Erdos686.EvenK.K32.All
