import Research.FourthCrossingFirstMomentGate
import Mathlib.Tactic

open MeasureTheory Set
open scoped BigOperators

namespace Erdos521

noncomputable local instance axisCylinderDecidable (p : Prop) : Decidable p :=
  Classical.propDecidable p

local instance axisCylinderFairProbability : IsProbabilityMeasure fairCoin := by
  unfold fairCoin
  infer_instance

local instance axisCylinderRademacherProbability : IsProbabilityMeasure rademacherMeasure := by
  unfold rademacherMeasure
  infer_instance

def coefficientPrefixMap (n : ℕ) :
    (ℕ → Bool) → ((Finset.range (2 * n) : Finset ℕ) → Bool) :=
  fun ω i ↦ ω i

/-- Cylinder generated by an arbitrary finite collection of good axis paths. -/
def axisPathCylinder (n : ℕ) (A : Finset (AxisGoodPath n)) : Set (ℕ → Bool) :=
  coefficientPrefixMap n ⁻¹'
    (axisGoodPrefixMap n '' (A : Set (AxisGoodPath n)))

lemma measurable_coefficientPrefixMap (n : ℕ) : Measurable (coefficientPrefixMap n) := by
  apply measurable_pi_lambda
  intro i
  exact measurable_pi_apply i.val

lemma measurableSet_axisPathCylinder (n : ℕ) (A : Finset (AxisGoodPath n)) :
    MeasurableSet (axisPathCylinder n A) := by
  apply MeasurableSet.preimage _ (measurable_coefficientPrefixMap n)
  exact (A.finite_toSet.image (axisGoodPrefixMap n)).measurableSet

lemma axisGoodPrefixMap_apply_eq_coefficients {n : ℕ} (p : AxisGoodPath n)
    (i : (Finset.range (2 * n) : Finset ℕ)) :
    axisGoodPrefixMap n p i = axisPathCoefficients p i.val := by
  unfold axisGoodPrefixMap bitsToRangePrefix
  rw [axisPathCoefficients_eq, extendBits_of_lt]

lemma mem_axisPathCylinder_iff (n : ℕ) (A : Finset (AxisGoodPath n)) (ω : ℕ → Bool) :
    ω ∈ axisPathCylinder n A ↔
      ∃ p ∈ A, ∀ i < 2 * n, axisPathCoefficients p i = ω i := by
  simp only [axisPathCylinder, Set.mem_preimage, Set.mem_image]
  constructor
  · rintro ⟨p, hp, heq⟩
    refine ⟨p, hp, fun i hi ↦ ?_⟩
    have h := congrFun heq ⟨i, Finset.mem_range.mpr hi⟩
    rw [axisGoodPrefixMap_apply_eq_coefficients] at h
    exact h
  · rintro ⟨p, hp, heq⟩
    refine ⟨p, hp, ?_⟩
    funext i
    rw [axisGoodPrefixMap_apply_eq_coefficients]
    exact heq i (Finset.mem_range.mp i.property)

lemma axisPathCylinder_subset_coneRecord (n : ℕ) (A : Finset (AxisGoodPath n)) :
    axisPathCylinder n A ⊆ coneRecordEvent n := by
  intro ω hω
  obtain ⟨p, hp, heq⟩ := (mem_axisPathCylinder_iff n A ω).mp hω
  have hpcone : axisPathCoefficients p ∈ coneRecordEvent n := by
    rw [axisPathCoefficients_eq]
    exact (coneRecord_extend_iff_axisGood _).mpr (by simpa using p.property)
  apply (isConeRecord_iff_of_prefix (ω := axisPathCoefficients p) (η := ω) heq).mp
  exact hpcone

lemma coneRecord_mem_full_axisPathCylinder (n : ℕ) (ω : ℕ → Bool)
    (hω : ω ∈ coneRecordEvent n) :
    ω ∈ axisPathCylinder n Finset.univ := by
  let x : Fin (2 * n) → Bool := fun j ↦ ω j.val
  have hgood : AxisGood (bitsAxisEquiv n x).1 (bitsAxisEquiv n x).2 := by
    apply (coneRecord_extend_iff_axisGood x).mp
    apply (isConeRecord_iff_of_prefix (ω := extendBits n x) (η := ω) ?_).mpr hω
    intro k hk
    simp [x, extendBits, hk]
  let p : AxisGoodPath n := ⟨bitsAxisEquiv n x, hgood⟩
  apply (mem_axisPathCylinder_iff n Finset.univ ω).mpr
  refine ⟨p, Finset.mem_univ _, ?_⟩
  intro i hi
  rw [axisPathCoefficients_eq]
  change extendBits n ((bitsAxisEquiv n).symm (bitsAxisEquiv n x)) i = ω i
  rw [(bitsAxisEquiv n).symm_apply_apply]
  simp [x, extendBits, hi]

/-- Every finite set of good paths has exactly its cardinality divided by `4^n` as cylinder mass. -/
lemma axisPathCylinder_measure_eq (n : ℕ) (A : Finset (AxisGoodPath n)) :
    rademacherMeasure.real (axisPathCylinder n A) =
      (A.card : ℝ) / (4 : ℝ) ^ n := by
  let S := Finset.range (2 * n)
  let E : Set (S → Bool) := axisGoodPrefixMap n '' (A : Set (AxisGoodPath n))
  have hm := rademacherMeasure_prefix_preimage S E
  have hc : E.ncard = A.card := by
    dsimp [E]
    rw [Set.ncard_image_of_injective _ (axisGoodPrefixMap_injective n),
      Set.ncard_coe_finset]
  change rademacherMeasure.real (coefficientPrefixMap n ⁻¹' E) = _
  unfold coefficientPrefixMap
  rw [Measure.real, hm, ENNReal.toReal_div, ENNReal.toReal_natCast,
    ENNReal.toReal_natCast, hc]
  change (A.card : ℝ) / ((2 ^ S.card : ℕ) : ℝ) = (A.card : ℝ) / (4 : ℝ) ^ n
  rw [show S.card = 2 * n by simp [S]]
  congr 1
  push_cast
  rw [pow_mul]
  norm_num

end Erdos521
