import Research.FourthCoefficientGeometry
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Complex
import Mathlib.Tactic

open scoped BigOperators

namespace Erdos521

/-- Integer old coefficient vectors for the pair `(fourth sum, one-step increment)`. -/
def fourthIntegerA (q : ℕ) : ℤ := Nat.choose (q + 3) 3

def fourthIntegerB (q : ℕ) : ℤ := Nat.choose (q + 3) 2

@[simp] lemma fourthIntegerA_zero : fourthIntegerA 0 = 1 := by
  norm_num [fourthIntegerA]

@[simp] lemma fourthIntegerB_zero : fourthIntegerB 0 = 3 := by
  norm_num [fourthIntegerB]

/-- The old vector at `q=0`, together with the new vector `(0,1)`, generates all of `ℤ²`. -/
lemma fourth_integer_vectors_primitive (x y : ℤ) :
    ∃ m n : ℤ,
      x = m * fourthIntegerA 0 + n * 0 ∧
      y = m * fourthIntegerB 0 + n * 1 := by
  refine ⟨x, y - 3 * x, ?_, ?_⟩ <;> simp <;> ring

/-- Consequently the lattice generated by the possible sign-flip differences `2v` is exactly
`2ℤ²`; this pins down the dual Fourier period lattice as `πℤ²`. -/
lemma fourth_integer_difference_vectors_generate_even (x y : ℤ) :
    ∃ m n : ℤ,
      2 * x = m * (2 * fourthIntegerA 0) + n * (2 * 0) ∧
      2 * y = m * (2 * fourthIntegerB 0) + n * (2 * 1) := by
  refine ⟨x, y - 3 * x, ?_, ?_⟩ <;> simp <;> ring

/-- Integer-valued Rademacher sign. -/
def integerSign : Bool → ℤ
  | true => 1
  | false => -1

@[simp] lemma integerSign_true : integerSign true = 1 := rfl
@[simp] lemma integerSign_false : integerSign false = -1 := rfl

lemma integerSign_eq_one_sub_two (b : Bool) :
    integerSign b = 1 - 2 * (if b then 0 else 1) := by
  cases b <;> norm_num [integerSign]

/-- Original integer pair sum, including the new `(0,1)` sign. -/
def fourthIntegerPairSum (k : ℕ) (e : Fin (k + 1) → Bool) (z : Bool) : ℤ × ℤ :=
  (∑ q : Fin (k + 1), fourthIntegerA q * integerSign (e q),
    integerSign z + ∑ q : Fin (k + 1), fourthIntegerB q * integerSign (e q))

/-- Every attainable pair lies in one deterministic affine coset of `2ℤ²`. -/
lemma fourthIntegerPairSum_affine_even_coset (k : ℕ)
    (e : Fin (k + 1) → Bool) (z : Bool) :
    ∃ u v : ℤ,
      (fourthIntegerPairSum k e z).1 =
        (∑ q : Fin (k + 1), fourthIntegerA q) - 2 * u ∧
      (fourthIntegerPairSum k e z).2 =
        (1 + ∑ q : Fin (k + 1), fourthIntegerB q) - 2 * v := by
  let d : Bool → ℤ := fun b ↦ if b then 0 else 1
  refine ⟨∑ q : Fin (k + 1), fourthIntegerA q * d (e q),
    d z + ∑ q : Fin (k + 1), fourthIntegerB q * d (e q), ?_, ?_⟩
  · unfold fourthIntegerPairSum
    dsimp only
    simp_rw [integerSign_eq_one_sub_two]
    calc
      (∑ q : Fin (k + 1),
          fourthIntegerA q * (1 - 2 * d (e q))) =
          ∑ q : Fin (k + 1),
            (fourthIntegerA q - 2 * (fourthIntegerA q * d (e q))) := by
        apply Finset.sum_congr rfl
        intro q hq
        ring
      _ = (∑ q : Fin (k + 1), fourthIntegerA q) -
          ∑ q : Fin (k + 1), 2 * (fourthIntegerA q * d (e q)) := by
        rw [Finset.sum_sub_distrib]
      _ = (∑ q : Fin (k + 1), fourthIntegerA q) -
          2 * ∑ q : Fin (k + 1), fourthIntegerA q * d (e q) := by
        rw [Finset.mul_sum]
  · unfold fourthIntegerPairSum
    dsimp only
    simp_rw [integerSign_eq_one_sub_two]
    have hsum : (∑ q : Fin (k + 1),
        fourthIntegerB q * (1 - 2 * d (e q))) =
        (∑ q : Fin (k + 1), fourthIntegerB q) -
          2 * ∑ q : Fin (k + 1), fourthIntegerB q * d (e q) := by
      calc
        _ = ∑ q : Fin (k + 1),
            (fourthIntegerB q - 2 * (fourthIntegerB q * d (e q))) := by
          apply Finset.sum_congr rfl
          intro q hq
          ring
        _ = (∑ q : Fin (k + 1), fourthIntegerB q) -
            ∑ q : Fin (k + 1), 2 * (fourthIntegerB q * d (e q)) := by
          rw [Finset.sum_sub_distrib]
        _ = _ := by rw [Finset.mul_sum]
    rw [hsum]
    ring

/-- The phases in the original integer dual coordinates, including the new vector. -/
noncomputable def fourthOriginalPhase (k : ℕ) (s t : ℝ) :
    Option (Fin (k + 1)) → ℝ
  | none => t
  | some q => s * fourthCoefficientA q + t * fourthCoefficientB q

/-- The original-coordinate characteristic cosine product. -/
noncomputable def fourthOriginalCharacteristicProduct (k : ℕ) (s t : ℝ) : ℝ :=
  ∏ i : Option (Fin (k + 1)), Real.cos (fourthOriginalPhase k s t i)

lemma eq_zero_of_abs_le_pi_div_two_of_abs_cos_eq_one {x : ℝ}
    (hx : |x| ≤ Real.pi / 2) (hcos : |Real.cos x| = 1) : x = 0 := by
  have hmem : x ∈ Set.Icc (-(Real.pi / 2)) (Real.pi / 2) := by
    rw [Set.mem_Icc]
    exact ⟨(neg_le_of_abs_le hx), (le_of_abs_le hx)⟩
  have hnonneg := Real.cos_nonneg_of_mem_Icc hmem
  rw [abs_of_nonneg hnonneg] at hcos
  have hlo : -(2 * Real.pi) < x := by
    have := neg_le_of_abs_le hx
    nlinarith [Real.pi_pos]
  have hhi : x < 2 * Real.pi := by
    have := le_of_abs_le hx
    nlinarith [Real.pi_pos]
  exact (Real.cos_eq_one_iff_of_lt_of_lt hlo hhi).mp hcos

/-- On the closed fundamental dual cell of `2ℤ²`, the origin is the unique point where the
characteristic product has modulus one. -/
lemma fourthOriginalCharacteristicProduct_abs_eq_one_iff (k : ℕ) (s t : ℝ)
    (hs : |s| ≤ Real.pi / 2) (ht : |t| ≤ Real.pi / 2) :
    |fourthOriginalCharacteristicProduct k s t| = 1 ↔ s = 0 ∧ t = 0 := by
  classical
  constructor
  · intro hprod
    unfold fourthOriginalCharacteristicProduct at hprod
    rw [Finset.abs_prod] at hprod
    have hall (i : Option (Fin (k + 1))) :
        |Real.cos (fourthOriginalPhase k s t i)| = 1 := by
      let f : Option (Fin (k + 1)) → ℝ :=
        fun j ↦ |Real.cos (fourthOriginalPhase k s t j)|
      let P : ℝ := ∏ j ∈ (Finset.univ : Finset (Option (Fin (k + 1)))).erase i, f j
      have hfi0 : 0 ≤ f i := abs_nonneg _
      have hfi1 : f i ≤ 1 := Real.abs_cos_le_one _
      have hP0 : 0 ≤ P := Finset.prod_nonneg fun j hj ↦ abs_nonneg _
      have hP1 : P ≤ 1 := Finset.prod_le_one
        (fun j hj ↦ abs_nonneg _) (fun j hj ↦ Real.abs_cos_le_one _)
      have heq : f i * P = 1 := by
        exact (Finset.mul_prod_erase Finset.univ f (Finset.mem_univ i)).trans hprod
      have hmul : f i * P ≤ f i := mul_le_of_le_one_right hfi0 hP1
      exact le_antisymm hfi1 (by linarith)
    have ht0 : t = 0 :=
      eq_zero_of_abs_le_pi_div_two_of_abs_cos_eq_one ht (hall none)
    let q0 : Fin (k + 1) := ⟨0, by omega⟩
    have hq0 := hall (some q0)
    have hphase0 : fourthOriginalPhase k s t (some q0) = s := by
      dsimp [fourthOriginalPhase, q0]
      rw [ht0]
      norm_num [fourthCoefficientA, fourthCoefficientB]
    rw [hphase0] at hq0
    exact ⟨eq_zero_of_abs_le_pi_div_two_of_abs_cos_eq_one hs hq0, ht0⟩
  · rintro ⟨rfl, rfl⟩
    simp [fourthOriginalCharacteristicProduct, fourthOriginalPhase]

end Erdos521
