/-
Aggregate for ErdosProblems.Erdos730.Audit: imports the whole subtree so `lake build ErdosProblems.Erdos730.Audit.All` builds it.
Generated by scripts/gen_aggregates.py — do not edit by hand.
-/
import ErdosProblems.Erdos730.Audit.BranchEvents
import ErdosProblems.Erdos730.Audit.ConsecutiveTransition
import ErdosProblems.Erdos730.Audit.DensityAssembly
import ErdosProblems.Erdos730.Audit.DensityEvents
import ErdosProblems.Erdos730.Audit.DigitBoxes
import ErdosProblems.Erdos730.Audit.DivisorSwitching
import ErdosProblems.Erdos730.Audit.DominatedLimit
import ErdosProblems.Erdos730.Audit.FiniteBlockCount
import ErdosProblems.Erdos730.Audit.FirstPowerRoutes
import ErdosProblems.Erdos730.Audit.FixedDepthDensity
import ErdosProblems.Erdos730.Audit.FixedDepthFourier
import ErdosProblems.Erdos730.Audit.FixedDepthParity
import ErdosProblems.Erdos730.Audit.FullDensityBudget
import ErdosProblems.Erdos730.Audit.FullDensityCore
import ErdosProblems.Erdos730.Audit.FullDensityReduction
import ErdosProblems.Erdos730.Audit.FullDensityTheorem
import ErdosProblems.Erdos730.Audit.HigherPowerCount
import ErdosProblems.Erdos730.Audit.HigherPowerDecay
import ErdosProblems.Erdos730.Audit.HigherPowerDensity
import ErdosProblems.Erdos730.Audit.HigherPowerEvents
import ErdosProblems.Erdos730.Audit.KummerTransition
import ErdosProblems.Erdos730.Audit.LimsupSeries
import ErdosProblems.Erdos730.Audit.LowerHalfFourier
import ErdosProblems.Erdos730.Audit.Mertens
import ErdosProblems.Erdos730.Audit.ObstructionMaps
import ErdosProblems.Erdos730.Audit.PNTAP
import ErdosProblems.Erdos730.Audit.PadicIsometry
import ErdosProblems.Erdos730.Audit.PrimeBands
import ErdosProblems.Erdos730.Audit.RangeAssembly
import ErdosProblems.Erdos730.Audit.SmallPrimeDepth
import ErdosProblems.Erdos730.Audit.SmallPrimeEvents
import ErdosProblems.Erdos730.Audit.SmallPrimeTail
import ErdosProblems.Erdos730.Audit.TransitionDensity
import ErdosProblems.Erdos730.Audit.UnitBandPayment
import ErdosProblems.Erdos730.Audit.UnitRangeBlock
