/-
Direct files of ErdosProblems.Erdos686.EvenK.K22 only (the split siblings build the subdirectories).
Generated by scripts/gen_aggregates.py — do not edit by hand.
-/
import ErdosProblems.Erdos686.EvenK.K22.Core
import ErdosProblems.Erdos686.EvenK.K22.Defs
import ErdosProblems.Erdos686.EvenK.K22.FiniteStrip
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS0
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS1
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS10
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS11
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS12
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS13
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS14
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS15
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS16
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS17
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS18
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS19
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS2
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS20
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS21
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS22
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS23
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS24
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS25
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS26
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS27
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS3
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS4
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS5
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS6
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS7
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS8
import ErdosProblems.Erdos686.EvenK.K22.FiniteStripS9
