-- Library root: import every problem's aggregate so `lake build`
-- builds the whole library.  One entry per Erdős problem.
-- Generated by scripts/gen_aggregates.py — do not edit by hand.
import ErdosProblems.Erdos23.All
import ErdosProblems.Erdos154.All
import ErdosProblems.Erdos617
import ErdosProblems.Erdos686.All
import ErdosProblems.Erdos699.All
import ErdosProblems.Erdos727
import ErdosProblems.Erdos730.All
