/- leanprover/lean4:v4.29.1  mathlib v4.29.1 -/
import ErdosProblems.Erdos730.FixedDepthDensity

/-!
Kernel-axiom audit for the fixed-depth density passage of Erdős 730.
-/

namespace Erdos730.FixedDepthDensity

#print axioms relaxedDigitDensity_eq_card_ratio
#print axioms relaxedDigitDensity_formula
#print axioms relaxedDigitDensity_sub_base_le
#print axioms relaxedDigitDensity_weighted_error_le
#print axioms relaxedDigitDensity_le_one
#print axioms fixedDepthDensityCorrection_le_tail
#print axioms tendsto_fixedDepthDensityCorrection_zero
#print axioms fixedDepthPrimeSet_reciprocalSum_eq
#print axioms fixedDepthRelaxedPrimeMass_eq
#print axioms tendsto_fixedDepthRelaxedPrimeMass
#print axioms one_le_fixedDepthBlockDiscrepancy
#print axioms fixedDepthBlockCount_mul_pow_le
#print axioms fixedDepthBlockCount_normalized_le
#print axioms sqrt_prime_pow_div
#print axioms fixedDepthBlockDiscrepancy_scaled_le
#print axioms fixedDepthBlockDiscrepancy_double_scaled_le
#print axioms fixedDepthCompleteBlocks_normalized_discrepancy_le
#print axioms two_mul_fixedDepthCompleteBlocks_normalized_discrepancy_le
#print axioms eventually_fixedDepthFourierWeight_le
#print axioms eventually_fixedDepthFourierBandError_le_tail
#print axioms tendsto_fixedDepthFourierBandError_zero
#print axioms tendsto_fixedDepthFourierError_zero
#print axioms tendsto_fixedDepthUpper_div_self_zero
#print axioms fixedDepthTerminalBlockError_le_Chebyshev
#print axioms tendsto_fixedDepthTerminalChebyshevMajorant_zero
#print axioms tendsto_fixedDepthTerminalBlockError_zero
#print axioms tendsto_fixedDepthUnitError_zero
#print axioms tendsto_fixedDepthAnalyticMajorant
#print axioms eventually_le_limit_add_of_le_fixedDepthAnalyticMajorant
#print axioms limsup_le_of_le_fixedDepthAnalyticMajorant

end Erdos730.FixedDepthDensity
