/-
Aggregate for ErdosProblems.Erdos23: imports the whole subtree so `lake build ErdosProblems.Erdos23.All` builds it.
Generated by scripts/gen_aggregates.py — do not edit by hand.
-/
import ErdosProblems.Erdos23.GapGA
import ErdosProblems.Erdos23.GapGACanonical
import ErdosProblems.Erdos23.GapGAClosed
import ErdosProblems.Erdos23.GapGBAggregationArithmetic
import ErdosProblems.Erdos23.GapGBBinaryLayerAuto
import ErdosProblems.Erdos23.GapGBBinaryLayers
import ErdosProblems.Erdos23.GapGBEqualityBoundary
import ErdosProblems.Erdos23.GapGBIsometricCuts
import ErdosProblems.Erdos23.GapGBJoint
import ErdosProblems.Erdos23.GapGBLayerCapacity
import ErdosProblems.Erdos23.GapGBOneDefect
import ErdosProblems.Erdos23.GapGBOneDefectAlignment
import ErdosProblems.Erdos23.GapGBOneDefectIntervals
import ErdosProblems.Erdos23.GapGBSeries
import ErdosProblems.Erdos23.GapGBSeriesAudit
import ErdosProblems.Erdos23.GapGBTwoDefect
import ErdosProblems.Erdos23.GapGBTwoDefectAlignment
import ErdosProblems.Erdos23.GapGBTwoDefectFinal
import ErdosProblems.Erdos23.GapGBTwoDemand
import ErdosProblems.Erdos23.GapGBTwoDemandWeighted
