/*
  Exact audit of the unordered degree-10 triple-partition field.

  The field is generated by a symmetric invariant of a 3+3 partition of the
  six roots.  Because the invariant does not distinguish the two
  complementary triples, the original sextic need not split into cubics.
*/

Q := Rationals();
R<x> := PolynomialRing(Q);
f := x^6 + 64/9*x^5 - 200/9*x^3 + 64/9*x + 16;

S<w> := PolynomialRing(Q);
g :=
  w^10
  - 12800/27*w^8
  + 79520/81*w^7
  + 79083520/729*w^6
  - 6772256768/6561*w^5
  - 36859590400/531441*w^4
  + 1435869593600/59049*w^3
  + 118517873377280/4782969*w^2
  - 63032357027840/177147*w
  - 42283606730604544/43046721;

print "TRIPLE_PARTITION_FIELD_DEGREE", Degree(g);
print "TRIPLE_PARTITION_FIELD_IRREDUCIBLE", IsIrreducible(g);

L<a> := NumberField(g);
RL<X> := PolynomialRing(L);
fL := X^6 + 64/9*X^5 - 200/9*X^3 + 64/9*X + 16;
factorization := Factorization(fL);

print "SEXTIC_FACTOR_DEGREES",
  Sort([Degree(entry[1]) : entry in factorization]);
print "SEXTIC_FACTORIZATION", factorization;
