import Research.CriticalRepresentationDichotomy

namespace Erdos336

set_option maxHeartbeats 1200000

open scoped Pointwise

variable {G : Type*} [AddCommGroup G] [DecidableEq G]

/-- The double of an explicit three-point set. -/
theorem add_triple_zero_eq (a b : G) :
    ({0, a, b} : Finset G) + {0, a, b} =
      {0, a, b, a + a, a + b, b + b} := by
  classical
  ext x
  constructor
  · intro hx
    obtain ⟨u, hu, v, hv, rfl⟩ := Finset.mem_add.mp hx
    simp only [Finset.mem_insert, Finset.mem_singleton] at hu hv ⊢
    rcases hu with rfl | rfl | rfl <;> rcases hv with rfl | rfl | rfl <;>
      simp [add_comm]
  · intro hx
    simp only [Finset.mem_insert, Finset.mem_singleton] at hx
    rcases hx with hx | hx | hx | hx | hx | hx
    · subst x; exact Finset.mem_add.mpr ⟨0, by simp, 0, by simp, by simp⟩
    · subst x; exact Finset.mem_add.mpr ⟨a, by simp, 0, by simp, by simp⟩
    · subst x; exact Finset.mem_add.mpr ⟨b, by simp, 0, by simp, by simp⟩
    · subst x; exact Finset.mem_add.mpr ⟨a, by simp, a, by simp, rfl⟩
    · subst x; exact Finset.mem_add.mpr ⟨a, by simp, b, by simp, rfl⟩
    · subst x; exact Finset.mem_add.mpr ⟨b, by simp, b, by simp, rfl⟩

/-- Five listed points in a five-element finset are pairwise distinct. -/
theorem five_distinct_of_card
    (a b c d e : G) (h : ({a, b, c, d, e} : Finset G).card = 5) :
    a ≠ b ∧ a ≠ c ∧ a ≠ d ∧ a ≠ e ∧
    b ≠ c ∧ b ≠ d ∧ b ≠ e ∧ c ≠ d ∧ c ≠ e ∧ d ≠ e := by
  classical
  have h4 : ({b, c, d, e} : Finset G).card ≤ 4 := by
    have h1 := Finset.card_insert_le d {e}
    have h2 := Finset.card_insert_le c {d, e}
    have h3 := Finset.card_insert_le b {c, d, e}
    simp only [Finset.card_singleton] at h1
    omega
  have ha : a ∉ ({b, c, d, e} : Finset G) := by
    intro ha
    rw [Finset.card_insert_of_mem ha] at h
    omega
  have htail4 : ({b, c, d, e} : Finset G).card = 4 := by
    rw [Finset.card_insert_of_notMem ha] at h
    omega
  have h3 : ({c, d, e} : Finset G).card ≤ 3 := by
    have h1 := Finset.card_insert_le d {e}
    have h2 := Finset.card_insert_le c {d, e}
    simp only [Finset.card_singleton] at h1
    omega
  have hb : b ∉ ({c, d, e} : Finset G) := by
    intro hb
    rw [Finset.card_insert_of_mem hb] at htail4
    omega
  have htail3 : ({c, d, e} : Finset G).card = 3 := by
    rw [Finset.card_insert_of_notMem hb] at htail4
    omega
  have h2 : ({d, e} : Finset G).card ≤ 2 := Finset.card_insert_le d {e}
  have hc : c ∉ ({d, e} : Finset G) := by
    intro hc
    rw [Finset.card_insert_of_mem hc] at htail3
    omega
  have htail2 : ({d, e} : Finset G).card = 2 := by
    rw [Finset.card_insert_of_notMem hc] at htail3
    omega
  have hde : d ≠ e := by
    intro hde
    subst d
    simp at htail2
  simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at ha hb hc
  exact ⟨ha.1, ha.2.1, ha.2.2.1, ha.2.2.2,
    hb.1, hb.2.1, hb.2.2, hc.1, hc.2, hde⟩

/-- If a five-element union consists of a three-element core and a pair, then
the pair has two elements and is disjoint from the core. -/
theorem pair_disjoint_of_union_card_five
    (A P : Finset G) (hA : A.card = 3) (hP : P.card ≤ 2)
    (hU : (A ∪ P).card = 5) : P.card = 2 ∧ Disjoint A P := by
  have hid := Finset.card_union_add_card_inter A P
  have hinter : (A ∩ P).card = 0 := by omega
  have hp2 : P.card = 2 := by omega
  refine ⟨hp2, ?_⟩
  rw [Finset.disjoint_iff_inter_eq_empty, ← Finset.card_eq_zero]
  exact hinter

/-- The explicit two-element subgroup generated by a nonzero involution. -/
def orderTwoAddSubgroup (t : G) (ht : t + t = 0) : AddSubgroup G where
  carrier := {0, t}
  zero_mem' := by simp
  add_mem' := by
    intro x y hx hy
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx hy ⊢
    rcases hx with rfl | rfl <;> rcases hy with rfl | rfl <;> simp [ht]
  neg_mem' := by
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx ⊢
    rcases hx with rfl | rfl
    · simp
    · right
      exact neg_eq_of_add_eq_zero_right ht

@[simp] theorem mem_orderTwoAddSubgroup
    (t : G) (ht : t + t = 0) (x : G) :
    x ∈ orderTwoAddSubgroup t ht ↔ x = 0 ∨ x = t := by
  rfl

/-- A three-term progression with five double sums has exactly the two
new sums `3x,4x`, and all five terms are distinct. -/
theorem critical_progression_data
    (C : Finset G) (x : G)
    (hC : C = {0, x, x + x}) (hCcard : C.card = 3)
    (hCCcard : (C + C).card = 5) :
    x ≠ 0 ∧ x + x ≠ 0 ∧ x + x ≠ x ∧
      x + (x + x) ∈ criticalNewSums C ∧
      (x + x) + (x + x) ∈ criticalNewSums C ∧
      x + (x + x) ≠ (x + x) + (x + x) := by
  classical
  let x2 := x + x
  let x3 := x + x2
  let x4 := x2 + x2
  have hdouble : C + C = C ∪ {x3, x4} := by
    rw [hC, add_triple_zero_eq]
    ext z
    simp [x2, x3, x4, add_assoc]
    tauto
  have hpairle : ({x3, x4} : Finset G).card ≤ 2 := Finset.card_insert_le _ _
  have hUcard : (C ∪ {x3, x4}).card = 5 := by rw [← hdouble]; exact hCCcard
  obtain ⟨hpair, hdisj⟩ := pair_disjoint_of_union_card_five
    C {x3, x4} hCcard hpairle hUcard
  have hx34 : x3 ≠ x4 := by
    intro h
    have heq : ({x3, x4} : Finset G) = {x3} := by ext z; simp [h]
    rw [heq] at hpair
    simp at hpair
  have hx3not : x3 ∉ C := by
    intro hx
    exact Finset.disjoint_left.mp hdisj hx (by simp)
  have hx4not : x4 ∉ C := by
    intro hx
    exact Finset.disjoint_left.mp hdisj hx (by simp)
  have hx0 : x ≠ 0 := by
    intro h
    rw [hC, h] at hCcard
    simp at hCcard
  have hx20 : x2 ≠ 0 := by
    intro h
    have hCpair : C = {0, x} := by
      rw [hC, show x + x = 0 from h]
      ext z
      simp [or_comm]
    rw [hCpair] at hCcard
    have hc := Finset.card_insert_le 0 ({x} : Finset G)
    simp only [Finset.card_singleton] at hc
    omega
  have hx2x : x2 ≠ x := by
    intro h
    have hCpair : C = {0, x} := by
      rw [hC, show x + x = x from h]
      ext z
      simp
    rw [hCpair] at hCcard
    have hc := Finset.card_insert_le 0 ({x} : Finset G)
    simp only [Finset.card_singleton] at hc
    omega
  refine ⟨hx0, by simpa [x2] using hx20, by simpa [x2] using hx2x, ?_, ?_, ?_⟩
  · apply Finset.mem_sdiff.mpr
    refine ⟨?_, hx3not⟩
    rw [hdouble]
    apply Finset.mem_union_right
    change x3 ∈ ({x3, x4} : Finset G)
    simp
  · apply Finset.mem_sdiff.mpr
    refine ⟨?_, hx4not⟩
    rw [hdouble]
    apply Finset.mem_union_right
    change x4 ∈ ({x3, x4} : Finset G)
    simp
  · exact hx34

/-- A set supported on a subgroup and one further quotient class has a
2-point image and a 3-point double image, provided the first two multiples of
the further class are distinct. -/
theorem binary_support_gives_two_three_quotient
    (C : Finset G) (L : AddSubgroup G) (g : G)
    (hzero : 0 ∈ C) (hgC : g ∈ C)
    (hcover : ∀ x ∈ C, x ∈ L ∨ x - g ∈ L)
    (hgL : g ∉ L) (hggL : g + g ∉ L) :
    (subgroupQuotientImage L C).card = 2 ∧
      (subgroupQuotientImage L (C + C)).card = 3 := by
  classical
  let q : G →+ (G ⧸ L) := QuotientAddGroup.mk' L
  have hqg0 : q g ≠ 0 := by
    intro h
    exact hgL ((QuotientAddGroup.eq_zero_iff g).mp h)
  have hqgg0 : q g + q g ≠ 0 := by
    intro h
    apply hggL
    apply (QuotientAddGroup.eq_zero_iff (g + g)).mp
    change q (g + g) = 0
    rw [q.map_add]
    exact h
  have hqggg : q g + q g ≠ q g := by
    intro h
    have hz : q g = 0 := by
      apply add_left_cancel (a := -q g)
      simpa using congrArg (fun z => -q g + z) h
    exact hqg0 hz
  have hImage : subgroupQuotientImage L C = {0, q g} := by
    change C.image q = {0, q g}
    ext z
    constructor
    · intro hz
      obtain ⟨x, hxC, rfl⟩ := Finset.mem_image.mp hz
      rcases hcover x hxC with hxL | hxgL
      · have : q x = 0 := (QuotientAddGroup.eq_zero_iff x).mpr hxL
        simp [this]
      · have heq : q x = q g := by
          apply (QuotientAddGroup.eq_iff_sub_mem).mpr
          exact hxgL
        simp [heq]
    · intro hz
      simp only [Finset.mem_insert, Finset.mem_singleton] at hz
      rcases hz with rfl | rfl
      · exact Finset.mem_image.mpr ⟨0, hzero, q.map_zero⟩
      · exact Finset.mem_image.mpr ⟨g, hgC, rfl⟩
  have hDouble : subgroupQuotientImage L (C + C) =
      {0, q g, q g + q g} := by
    change (C + C).image q = _
    rw [Finset.image_add, show C.image q = {0, q g} from hImage]
    ext z
    constructor
    · intro hz
      obtain ⟨x, hx, y, hy, rfl⟩ := Finset.mem_add.mp hz
      simp only [Finset.mem_insert, Finset.mem_singleton] at hx hy ⊢
      rcases hx with rfl | rfl <;> rcases hy with rfl | rfl <;>
        simp [add_comm]
    · intro hz
      simp only [Finset.mem_insert, Finset.mem_singleton] at hz
      rcases hz with rfl | rfl | rfl
      · exact Finset.mem_add.mpr ⟨0, by simp, 0, by simp, by simp⟩
      · exact Finset.mem_add.mpr ⟨q g, by simp, 0, by simp, by simp⟩
      · exact Finset.mem_add.mpr ⟨q g, by simp, q g, by simp, rfl⟩
  constructor
  · rw [hImage]
    exact Finset.card_pair hqg0.symm
  · rw [hDouble]
    apply Finset.card_eq_three.mpr
    exact ⟨0, q g, q g + q g, hqg0.symm, hqgg0.symm, hqggg.symm, rfl⟩

/-- Complete repair of the omitted three-element critical case.  A
three-point set with five double sums has either a load-two selector, a
2-class/3-double-class subgroup quotient, or is a genuine three-term
progression with its two new sums explicitly identified. -/
theorem critical_three_representation_dichotomy
    (C : Finset G) (hzero : 0 ∈ C) (hCcard : C.card = 3)
    (hCCcard : (C + C).card = 5) :
    (∃ s : CriticalSelector C, ∀ z ∈ C, selectorLoad s z ≤ 2) ∨
    (∃ L : AddSubgroup G,
      (subgroupQuotientImage L C).card = 2 ∧
      (subgroupQuotientImage L (C + C)).card = 3) ∨
    ∃ x : G,
      C = {0, x, x + x} ∧ x ≠ 0 ∧ x + x ≠ 0 ∧ x + x ≠ x ∧
      x + (x + x) ∈ criticalNewSums C ∧
      (x + x) + (x + x) ∈ criticalNewSums C ∧
      x + (x + x) ≠ (x + x) + (x + x) := by
  classical
  have hEraseCard : (C.erase 0).card = 2 := by
    rw [Finset.card_erase_of_mem hzero, hCcard]
  obtain ⟨b, g, hbg, hErase⟩ := Finset.card_eq_two.mp hEraseCard
  have hbE : b ∈ C.erase 0 := by rw [hErase]; simp
  have hgE : g ∈ C.erase 0 := by rw [hErase]; simp
  have hbC : b ∈ C := (Finset.mem_erase.mp hbE).2
  have hgC : g ∈ C := (Finset.mem_erase.mp hgE).2
  have hb0 : b ≠ 0 := (Finset.mem_erase.mp hbE).1
  have hg0 : g ≠ 0 := (Finset.mem_erase.mp hgE).1
  have hC : C = {0, b, g} := by
    rw [← Finset.insert_erase hzero, hErase]
  have hCC : C + C = {0, b, g, b + b, b + g, g + g} := by
    rw [hC, add_triple_zero_eq]
  by_cases hsum0 : b + g = 0
  · left
    let P : Finset G := {b + b, g + g}
    have hUnion : C + C = C ∪ P := by
      rw [hCC, hC]
      ext z
      simp [P, hsum0]
      tauto
    have hPcardLe : P.card ≤ 2 := Finset.card_insert_le _ _
    have hUcard : (C ∪ P).card = 5 := by rw [← hUnion]; exact hCCcard
    obtain ⟨hPcard, hdisj⟩ := pair_disjoint_of_union_card_five
      C P hCcard hPcardLe hUcard
    have hbbgg : b + b ≠ g + g := by
      intro h
      have heq : P = {b + b} := by ext z; simp [P, h]
      rw [heq] at hPcard
      simp at hPcard
    have hD : criticalNewSums C = P := by
      ext z
      constructor
      · intro hz
        have hz' := Finset.mem_sdiff.mp hz
        rw [hUnion] at hz'
        exact (Finset.mem_union.mp hz'.1).resolve_left hz'.2
      · intro hzP
        apply Finset.mem_sdiff.mpr
        refine ⟨?_, ?_⟩
        · rw [hUnion]
          exact Finset.mem_union_right _ hzP
        · intro hzC
          exact Finset.disjoint_left.mp hdisj hzC hzP
    let s : CriticalSelector C :=
      { left := fun u => if u = b + b then b else g
        right := fun u => if u = b + b then b else g
        left_mem := by
          intro u hu
          have huP : u ∈ P := by rw [← hD]; exact hu
          have hor : u = b + b ∨ u = g + g := by simpa [P] using huP
          split
          · exact hbC
          · exact hgC
        right_mem := by
          intro u hu
          have huP : u ∈ P := by rw [← hD]; exact hu
          have hor : u = b + b ∨ u = g + g := by simpa [P] using huP
          split
          · exact hbC
          · exact hgC
        add_eq := by
          intro u hu
          have huP : u ∈ P := by rw [← hD]; exact hu
          have hor : u = b + b ∨ u = g + g := by simpa [P] using huP
          split <;> rename_i h
          · exact h.symm
          · have : u = g + g := hor.resolve_left h
            exact this.symm }
    refine ⟨s, ?_⟩
    intro z _hzC
    have hinj : ∀ u ∈ P, ∀ v ∈ P, s.left u = z → s.left v = z → u = v := by
      intro u hu v hv huz hvz
      have hu' : u = b + b ∨ u = g + g := by simpa [P] using hu
      have hv' : v = b + b ∨ v = g + g := by simpa [P] using hv
      rcases hu' with rfl | rfl <;> rcases hv' with rfl | rfl
      · rfl
      · exfalso
        apply hbg
        calc
          b = s.left (b + b) := by simp [s]
          _ = z := huz
          _ = s.left (g + g) := hvz.symm
          _ = g := by simp [s, Ne.symm hbbgg]
      · exfalso
        apply hbg
        calc
          b = s.left (b + b) := by simp [s]
          _ = z := hvz
          _ = s.left (g + g) := huz.symm
          _ = g := by simp [s, Ne.symm hbbgg]
      · rfl
    have hfilter : (P.filter fun u => s.left u = z).card ≤ 1 := by
      rw [Finset.card_le_one]
      intro u hu v hv
      exact hinj u (Finset.mem_filter.mp hu).1 v (Finset.mem_filter.mp hv).1
        (Finset.mem_filter.mp hu).2 (Finset.mem_filter.mp hv).2
    change ((criticalNewSums C).filter (fun u => s.left u = z)).card +
      ((criticalNewSums C).filter (fun u => s.right u = z)).card ≤ 2
    rw [hD]
    change (P.filter (fun u => s.left u = z)).card +
      (P.filter (fun u => s.left u = z)).card ≤ 2
    omega
  · by_cases hb20 : b + b = 0
    · right; left
      let L := orderTwoAddSubgroup b hb20
      have hfive : ({0, b, g, b + g, g + g} : Finset G).card = 5 := by
        rw [← hCCcard, hCC]
        congr 1
        ext z
        simp [hb20]
        tauto
      have hd := five_distinct_of_card 0 b g (b + g) (g + g) hfive
      have hgL : g ∉ L := by
        intro h
        rcases (mem_orderTwoAddSubgroup b hb20 g).mp h with h | h
        · exact hg0 h
        · exact hbg h.symm
      have hggL : g + g ∉ L := by
        intro h
        rcases (mem_orderTwoAddSubgroup b hb20 (g + g)).mp h with h | h
        · exact hd.2.2.2.1 h.symm
        · exact hd.2.2.2.2.2.2.1 h.symm
      refine ⟨L, binary_support_gives_two_three_quotient C L g hzero hgC ?_ hgL hggL⟩
      intro z hz
      rw [hC] at hz
      simp only [Finset.mem_insert, Finset.mem_singleton] at hz
      rcases hz with hz | hz | hz
      · subst z; left; exact L.zero_mem
      · subst z; left; exact (mem_orderTwoAddSubgroup b hb20 b).mpr (Or.inr rfl)
      · subst z; right; simp
    · by_cases hb2g : b + b = g
      · right; right
        refine ⟨b, ?_, critical_progression_data C b ?_ hCcard hCCcard⟩
        · rw [hC, ← hb2g]
        · rw [hC, ← hb2g]
      · by_cases hg20 : g + g = 0
        · right; left
          let L := orderTwoAddSubgroup g hg20
          have hfive : ({0, b, g, b + g, b + b} : Finset G).card = 5 := by
            rw [← hCCcard, hCC]
            congr 1
            ext z
            simp [hg20]
            tauto
          have hd := five_distinct_of_card 0 b g (b + g) (b + b) hfive
          have hbL : b ∉ L := by
            intro h
            rcases (mem_orderTwoAddSubgroup g hg20 b).mp h with h | h
            · exact hb0 h
            · exact hbg h
          have hbbL : b + b ∉ L := by
            intro h
            rcases (mem_orderTwoAddSubgroup g hg20 (b + b)).mp h with h | h
            · exact hd.2.2.2.1 h.symm
            · exact hd.2.2.2.2.2.2.2.2.1 h.symm
          refine ⟨L, binary_support_gives_two_three_quotient C L b hzero hbC ?_ hbL hbbL⟩
          intro z hz
          rw [hC] at hz
          simp only [Finset.mem_insert, Finset.mem_singleton] at hz
          rcases hz with hz | hz | hz
          · subst z; left; exact L.zero_mem
          · subst z; right; simp
          · subst z; left; exact (mem_orderTwoAddSubgroup g hg20 g).mpr (Or.inr rfl)
        · by_cases hg2b : g + g = b
          · right; right
            have hC' : C = {0, g, g + g} := by
              rw [hC, hg2b]
              ext z
              simp [or_comm]
            refine ⟨g, hC', critical_progression_data C g hC' hCcard hCCcard⟩
          · by_cases heq2 : b + b = g + g
            · right; left
              let t := b - g
              have htt : t + t = 0 := by
                dsimp [t]
                calc
                  (b - g) + (b - g) = (b + b) - (g + g) := by abel
                  _ = 0 := by rw [heq2]; simp
              let L := orderTwoAddSubgroup t htt
              have hfive : ({0, b, g, b + g, b + b} : Finset G).card = 5 := by
                rw [← hCCcard, hCC]
                congr 1
                ext z
                simp [heq2]
              have hd := five_distinct_of_card 0 b g (b + g) (b + b) hfive
              have hgL : g ∉ L := by
                intro h
                rcases (mem_orderTwoAddSubgroup t htt g).mp h with h | h
                · exact hg0 h
                · have hbgg : b = g + g := by
                    dsimp [t] at h
                    calc
                      b = (b - g) + g := by abel
                      _ = g + g := by rw [← h]
                  have hself : (g + g) + (g + g) = g + g := by
                    calc
                      (g + g) + (g + g) = b + b := by rw [hbgg]
                      _ = g + g := heq2
                  have hgg0 : g + g = 0 := by
                    apply add_left_cancel (a := g + g)
                    simpa using hself
                  exact hb0 (hbgg.trans hgg0)
              have hggL : g + g ∉ L := by
                intro h
                rcases (mem_orderTwoAddSubgroup t htt (g + g)).mp h with h | h
                · exact hd.2.2.2.1 (heq2.trans h).symm
                · apply hd.2.2.1
                  calc
                    (0 : G) = t + t := htt.symm
                    _ = (b - g) + (g + g) := by dsimp [t]; rw [h]
                    _ = b + g := by abel
              refine ⟨L, binary_support_gives_two_three_quotient C L g hzero hgC ?_ hgL hggL⟩
              intro z hz
              rw [hC] at hz
              simp only [Finset.mem_insert, Finset.mem_singleton] at hz
              rcases hz with hz | hz | hz
              · subst z; left; exact L.zero_mem
              · subst z; right
                apply (mem_orderTwoAddSubgroup t htt (b - g)).mpr
                exact Or.inr rfl
              · subst z; right; simp
            · exfalso
              have hb2b : b + b ≠ b := by
                intro h
                apply hb0
                apply add_left_cancel (a := b)
                simpa using h
              have hb2bg : b + b ≠ b + g := by
                intro h
                exact hbg (add_left_cancel h)
              have hg2g : g + g ≠ g := by
                intro h
                apply hg0
                apply add_left_cancel (a := g)
                simpa using h
              have hg2bg : g + g ≠ b + g := by
                intro h
                exact hbg (add_right_cancel h).symm
              have hbgB : b + g ≠ b := by
                intro h
                apply hg0
                apply add_left_cancel (a := b)
                simpa using h
              have hbgG : b + g ≠ g := by
                intro h
                apply hb0
                apply add_right_cancel (b := g)
                simpa using h
              have h0tail : (0 : G) ∉ ({b, g, b + g, b + b, g + g} : Finset G) := by
                simp only [Finset.mem_insert, Finset.mem_singleton, not_or]
                exact ⟨hb0.symm, hg0.symm, fun h => hsum0 h.symm,
                  fun h => hb20 h.symm, fun h => hg20 h.symm⟩
              have hbTail : b ∉ ({g, b + g, b + b, g + g} : Finset G) := by
                simp only [Finset.mem_insert, Finset.mem_singleton, not_or]
                exact ⟨hbg, hbgB.symm, hb2b.symm, fun h => hg2b h.symm⟩
              have hgTail : g ∉ ({b + g, b + b, g + g} : Finset G) := by
                simp only [Finset.mem_insert, Finset.mem_singleton, not_or]
                exact ⟨hbgG.symm, fun h => hb2g h.symm, hg2g.symm⟩
              have hbgTail : b + g ∉ ({b + b, g + g} : Finset G) := by
                simp only [Finset.mem_insert, Finset.mem_singleton, not_or]
                exact ⟨hb2bg.symm, hg2bg.symm⟩
              have hcard6 : ({0, b, g, b + g, b + b, g + g} : Finset G).card = 6 := by
                rw [Finset.card_insert_of_notMem h0tail,
                  Finset.card_insert_of_notMem hbTail,
                  Finset.card_insert_of_notMem hgTail,
                  Finset.card_insert_of_notMem hbgTail,
                  Finset.card_insert_of_notMem (by simpa only [Finset.mem_singleton] using heq2)]
                simp
              have hcard6' : ({0, b, g, b + b, b + g, g + g} : Finset G).card = 6 := by
                simpa [Finset.insert_comm] using hcard6
              rw [hCC] at hCCcard
              omega

end Erdos336
