import Research.IntegerFiberEndpoint
import Research.RectifiedPrimitiveExpansion

namespace Erdos336

open scoped Pointwise

variable {H : Type*} [AddCommGroup H] [DecidableEq H]

/-- Endpoint points in the bottom fibre whose translate by `δ` lies in the
top fibre. -/
def endpointOverlap (T : Finset (ℤ × H)) (l : ℤ) (δ : ℤ × H) :
    Finset (ℤ × H) :=
  integerFiber T 0 ∩ (-δ +ᵥ integerFiber T l)

/-- The top representatives which duplicate endpoint-overlap points modulo
`zmultiples δ`. -/
def endpointDuplicateTop (T : Finset (ℤ × H)) (l : ℤ) (δ : ℤ × H) :
    Finset (ℤ × H) :=
  δ +ᵥ endpointOverlap T l δ

@[simp] theorem card_endpointDuplicateTop
    (T : Finset (ℤ × H)) (l : ℤ) (δ : ℤ × H) :
    (endpointDuplicateTop T l δ).card = (endpointOverlap T l δ).card := by
  exact Finset.card_vadd_finset δ _

lemma endpointDuplicateTop_subset
    (T : Finset (ℤ × H)) (l : ℤ) (δ : ℤ × H) :
    endpointDuplicateTop T l δ ⊆ T := by
  intro x hx
  obtain ⟨e, he, hex⟩ := Finset.mem_vadd_finset.mp hx
  have heTop := (Finset.mem_inter.mp he).2
  obtain ⟨y, hy, hye⟩ := Finset.mem_vadd_finset.mp heTop
  have hxy : x = y := by
    simp only [vadd_eq_add] at hex hye
    rw [← hex, ← hye]
    abel
  simpa [hxy] using (mem_integerFiber.mp hy).1

/-- Removing the duplicated top representatives does not change the image in
the cyclic quotient generated by the endpoint displacement. -/
theorem image_erase_endpointDuplicateTop
    (T : Finset (ℤ × H)) (l : ℤ) (δ : ℤ × H)
    (hlpos : 0 < l) (hδfst : δ.1 = l) :
    let Δ := AddSubgroup.zmultiples δ
    let q : (ℤ × H) →+ ((ℤ × H) ⧸ Δ) := QuotientAddGroup.mk' Δ
    (T \ endpointDuplicateTop T l δ).image q = T.image q := by
  dsimp
  let Δ := AddSubgroup.zmultiples δ
  let q : (ℤ × H) →+ ((ℤ × H) ⧸ Δ) := QuotientAddGroup.mk' Δ
  apply Finset.Subset.antisymm
  · exact Finset.image_subset_image (Finset.sdiff_subset.trans (by rfl))
  · intro z hz
    obtain ⟨x, hxT, hxz⟩ := Finset.mem_image.mp hz
    by_cases hxD : x ∈ endpointDuplicateTop T l δ
    · obtain ⟨e, heE, hex⟩ := Finset.mem_vadd_finset.mp hxD
      apply Finset.mem_image.mpr
      refine ⟨e, Finset.mem_sdiff.mpr ⟨(mem_integerFiber.mp
        (Finset.mem_inter.mp heE).1).1, ?_⟩, ?_⟩
      · intro heD
        have heTop := (mem_integerFiber.mp
          (Finset.mem_inter.mp heE).1).2
        obtain ⟨u, huE, hue⟩ := Finset.mem_vadd_finset.mp heD
        have huTop := (mem_integerFiber.mp
          (Finset.mem_inter.mp huE).1).2
        simp only [vadd_eq_add] at hue
        have hfirst := congrArg Prod.fst hue
        simp only [Prod.fst_add] at hfirst
        rw [heTop, huTop, hδfst] at hfirst
        omega
      · rw [← hxz]
        have hqδ : q δ = 0 := by
          exact (QuotientAddGroup.eq_zero_iff δ).mpr
            (AddSubgroup.mem_zmultiples δ)
        simp only [vadd_eq_add] at hex
        rw [← hex]
        change q e = q (δ + e)
        rw [map_add, hqδ, zero_add]
    · exact Finset.mem_image.mpr
        ⟨x, Finset.mem_sdiff.mpr ⟨hxT, hxD⟩, hxz⟩

/-- After deleting the duplicated top representatives, quotienting by
`zmultiples δ` is injective on a strip of width `δ.1`. -/
theorem quotient_injective_erase_endpointDuplicateTop
    (T : Finset (ℤ × H)) (l : ℤ) (δ : ℤ × H)
    (hlpos : 0 < l) (hδfst : δ.1 = l)
    (hbounds : ∀ x ∈ T, 0 ≤ x.1 ∧ x.1 ≤ l) :
    let Δ := AddSubgroup.zmultiples δ
    let q : (ℤ × H) →+ ((ℤ × H) ⧸ Δ) := QuotientAddGroup.mk' Δ
    Set.InjOn q (↑(T \ endpointDuplicateTop T l δ) : Set (ℤ × H)) := by
  dsimp
  let Δ := AddSubgroup.zmultiples δ
  let q : (ℤ × H) →+ ((ℤ × H) ⧸ Δ) := QuotientAddGroup.mk' Δ
  intro x hx y hy hqxy
  obtain ⟨hxT, hxD⟩ := Finset.mem_sdiff.mp hx
  obtain ⟨hyT, hyD⟩ := Finset.mem_sdiff.mp hy
  have hmem : x - y ∈ Δ := by
    apply (QuotientAddGroup.eq_iff_sub_mem).mp
    simpa [q, Δ] using hqxy
  obtain ⟨n, hn⟩ := AddSubgroup.mem_zmultiples_iff.mp hmem
  have hfst := congrArg Prod.fst hn
  change n * δ.1 = x.1 - y.1 at hfst
  rw [hδfst] at hfst
  have hxb := hbounds x hxT
  have hyb := hbounds y hyT
  have hnlo : -1 ≤ n := by nlinarith
  have hnhi : n ≤ 1 := by nlinarith
  have hncases : n = -1 ∨ n = 0 ∨ n = 1 := by omega
  rcases hncases with hnneg | hnzero | hnpos
  · have hxy : y = δ + x := by
      rw [hnneg] at hn
      simp only [neg_smul, one_zsmul] at hn
      have hxform : x = -δ + y := (sub_eq_iff_eq_add).mp hn.symm
      rw [hxform]
      abel
    have hxfst : x.1 = 0 := by rw [hnneg] at hfst; nlinarith
    have hyfst : y.1 = l := by rw [hnneg] at hfst; nlinarith
    apply False.elim (hyD ?_)
    apply Finset.mem_vadd_finset.mpr
    refine ⟨x, Finset.mem_inter.mpr ⟨?_, ?_⟩, hxy.symm⟩
    · exact mem_integerFiber.mpr ⟨hxT, hxfst⟩
    · apply Finset.mem_vadd_finset.mpr
      refine ⟨y, mem_integerFiber.mpr ⟨hyT, hyfst⟩, ?_⟩
      simp only [vadd_eq_add]
      rw [hxy]
      abel
  · rw [hnzero] at hn
    simp only [zero_zsmul] at hn
    exact sub_eq_zero.mp hn.symm
  · have hxy : x = δ + y := by
      rw [hnpos] at hn
      simp only [one_zsmul] at hn
      exact (sub_eq_iff_eq_add).mp hn.symm
    have hyfst : y.1 = 0 := by rw [hnpos] at hfst; nlinarith
    have hxfst : x.1 = l := by rw [hnpos] at hfst; nlinarith
    apply False.elim (hxD ?_)
    apply Finset.mem_vadd_finset.mpr
    refine ⟨y, Finset.mem_inter.mpr ⟨?_, ?_⟩, hxy.symm⟩
    · exact mem_integerFiber.mpr ⟨hyT, hyfst⟩
    · apply Finset.mem_vadd_finset.mpr
      refine ⟨x, mem_integerFiber.mpr ⟨hxT, hxfst⟩, ?_⟩
      simp only [vadd_eq_add]
      rw [hxy]
      abel

/-- Exact endpoint-overlap formula for the quotient image. -/
theorem card_image_endpointQuotient
    (T : Finset (ℤ × H)) (l : ℤ) (δ : ℤ × H)
    (hlpos : 0 < l) (hδfst : δ.1 = l)
    (hbounds : ∀ x ∈ T, 0 ≤ x.1 ∧ x.1 ≤ l) :
    let Δ := AddSubgroup.zmultiples δ
    let q : (ℤ × H) →+ ((ℤ × H) ⧸ Δ) := QuotientAddGroup.mk' Δ
    (T.image q).card + (endpointOverlap T l δ).card = T.card := by
  dsimp
  let Δ := AddSubgroup.zmultiples δ
  let q : (ℤ × H) →+ ((ℤ × H) ⧸ Δ) := QuotientAddGroup.mk' Δ
  let D := endpointDuplicateTop T l δ
  have hDsub : D ⊆ T := endpointDuplicateTop_subset T l δ
  have hinj := quotient_injective_erase_endpointDuplicateTop
    T l δ hlpos hδfst hbounds
  have hcardImage : ((T \ D).image q).card = (T \ D).card :=
    Finset.card_image_iff.mpr hinj
  have himage := image_erase_endpointDuplicateTop T l δ hlpos hδfst
  change (T.image q).card + (endpointOverlap T l δ).card = T.card
  rw [← himage, hcardImage, Finset.card_sdiff_of_subset hDsub]
  have hDcard : D.card = (endpointOverlap T l δ).card :=
    card_endpointDuplicateTop T l δ
  rw [← hDcard]
  have hDle : D.card ≤ T.card := Finset.card_le_card hDsub
  omega

end Erdos336
