/- leanprover/lean4:v4.29.1  mathlib v4.29.1 -/
import Mathlib.FieldTheory.KummerExtension
import Mathlib.NumberTheory.Padics.PadicVal.Basic
import ErdosProblems.Erdos686.Core.FiveThue

/-!
# Erdős 686, k=5: exact obstruction to a classical Runge shortcut

The projective centered curve has infinity polynomial `X^5-4Y^5`.  Over
`ℚ` its five geometric branches form one irreducible orbit, so the usual
multi-orbit Runge hypothesis is absent.  Passing to `ℚ(4^(1/5))` separates
the real branch, but the order generated by the fifth root already contains
an explicit norm-one unit which is strictly between zero and one at that
real embedding.  Its powers prevent a size argument based only on the norm
and the distinguished archimedean absolute value.

This file kernel-checks the arithmetic certificates used by that audit.  It
does not assert a general Runge theorem or the open `k=5` tail.
-/

namespace Erdos686
namespace Erdos686Variant

open Polynomial

/-- Four is not a fifth power in `ℚ`, witnessed by its 2-adic valuation. -/
lemma four_ne_rat_fifth_power (b : ℚ) : b ^ 5 ≠ 4 := by
  intro h
  have hb : b ≠ 0 := by
    rintro rfl
    norm_num at h
  letI : Fact (Nat.Prime 2) := ⟨by norm_num⟩
  have hv := congrArg (padicValRat 2) h
  rw [padicValRat.pow hb] at hv
  have hv4 : padicValRat 2 (4 : ℚ) = 2 := by
    have hv2 : padicValRat 2 (2 : ℚ) = 1 :=
      padicValRat.self (p := 2) (by norm_num)
    rw [show (4 : ℚ) = (2 : ℚ) ^ 2 by norm_num,
      padicValRat.pow (by norm_num), hv2]
    norm_num
  rw [hv4] at hv
  omega

/-- The five infinity branches are one irreducible degree-five orbit over
`ℚ`: the dehomogenized infinity polynomial is `T^5-4`. -/
theorem k5_infinity_polynomial_irreducible :
    Irreducible ((X : ℚ[X]) ^ 5 - C 4) := by
  apply X_pow_sub_C_irreducible_of_prime_pow
      (p := 5) (by norm_num) (by norm_num) 1
  intro b
  exact four_ne_rat_fifth_power b

/-- Exact inverse certificate for `epsilon=1+a-a^3` in any ring containing
a fifth root `a` of four. -/
theorem k5_runge_unit_inverse
    {R : Type*} [CommRing R] {a : R} (ha : a ^ 5 = 4) :
    (1 + a - a ^ 3) *
      (3 * a ^ 4 + 4 * a ^ 3 + 5 * a ^ 2 + 7 * a + 9) = 1 := by
  calc
    (1 + a - a ^ 3) *
        (3 * a ^ 4 + 4 * a ^ 3 + 5 * a ^ 2 + 7 * a + 9) =
      1 + (-3 * a ^ 2 - 4 * a - 2) * (a ^ 5 - 4) := by ring
    _ = 1 := by rw [ha]; ring

/-- Every positive power of the explicit unit has the displayed inverse. -/
theorem k5_runge_unit_power_inverse
    {R : Type*} [CommRing R] {a : R} (ha : a ^ 5 = 4) (m : ℕ) :
    (1 + a - a ^ 3) ^ m *
      (3 * a ^ 4 + 4 * a ^ 3 + 5 * a ^ 2 + 7 * a + 9) ^ m = 1 := by
  rw [← mul_pow, k5_runge_unit_inverse ha, one_pow]

/-- On the real fifth-root branch, the exact rational bracket used by the
`k=5` descent makes the unit positive and strictly smaller than one. -/
theorem k5_runge_unit_real_small {a : ℝ}
    (hlo : (131 : ℝ) / 100 < a) (hhi : a < (132 : ℝ) / 100) :
    0 < 1 + a - a ^ 3 ∧ 1 + a - a ^ 3 < 1 := by
  have ha0 : 0 < a := by linarith
  have ha1 : 1 < a := by linarith
  have hcubeUpper : a ^ 3 < ((132 : ℝ) / 100) ^ 3 := by
    have hfactor :
        0 < ((132 : ℝ) / 100) ^ 2 + ((132 : ℝ) / 100) * a + a ^ 2 := by
      positivity
    have hprod := mul_pos (sub_pos.mpr hhi) hfactor
    nlinarith
  have hcubeSelf : a < a ^ 3 := by
    have hprod : 0 < a * (a - 1) * (a + 1) :=
      mul_pos (mul_pos ha0 (sub_pos.mpr ha1)) (by linarith)
    nlinarith
  constructor
  · have hmargin :
        0 < 1 + (131 : ℝ) / 100 - ((132 : ℝ) / 100) ^ 3 := by
      norm_num
    linarith
  · linarith

/-- A quantified upper bound for the small real embedding of the unit. -/
theorem k5_runge_unit_real_lt_nine_over_125 {a : ℝ}
    (hlo : (131 : ℝ) / 100 < a) (hhi : a < (132 : ℝ) / 100) :
    1 + a - a ^ 3 < (9 : ℝ) / 125 := by
  have ha0 : 0 < a := by linarith
  have hcubeLower : ((131 : ℝ) / 100) ^ 3 < a ^ 3 := by
    have hfactor :
        0 < a ^ 2 + a * ((131 : ℝ) / 100) + ((131 : ℝ) / 100) ^ 2 := by
      positivity
    have hprod := mul_pos (sub_pos.mpr hlo) hfactor
    nlinarith
  have hmargin :
      1 + (132 : ℝ) / 100 - ((131 : ℝ) / 100) ^ 3 < (9 : ℝ) / 125 := by
    norm_num
  linarith

/-- The distinguished real absolute values of the unit powers remain in
`(0,1)`.  This is the exact archimedean unit obstruction consumed by the
number-field Runge audit. -/
theorem k5_runge_unit_power_real_small {a : ℝ}
    (hlo : (131 : ℝ) / 100 < a) (hhi : a < (132 : ℝ) / 100)
    {m : ℕ} (hm : 0 < m) :
    0 < (1 + a - a ^ 3) ^ m ∧ (1 + a - a ^ 3) ^ m < 1 := by
  have hunit := k5_runge_unit_real_small hlo hhi
  exact ⟨pow_pos hunit.1 m, pow_lt_one₀ hunit.1.le hunit.2 hm.ne'⟩

/-- At the exact cutoff reached by the finite Farey certificate, a concrete
unit power is already smaller than `10^-166` in the distinguished real
embedding. -/
theorem k5_runge_unit_pow_146_lt_ten_pow_neg_166 {a : ℝ}
    (hlo : (131 : ℝ) / 100 < a) (hhi : a < (132 : ℝ) / 100) :
    (1 + a - a ^ 3) ^ 146 < 1 / (10 : ℝ) ^ 166 := by
  have hpos := (k5_runge_unit_real_small hlo hhi).1
  have hupper := k5_runge_unit_real_lt_nine_over_125 hlo hhi
  calc
    (1 + a - a ^ 3) ^ 146 < ((9 : ℝ) / 125) ^ 146 :=
      pow_lt_pow_left₀ hupper hpos.le (by norm_num)
    _ < 1 / (10 : ℝ) ^ 166 := by norm_num

#print axioms four_ne_rat_fifth_power
#print axioms k5_infinity_polynomial_irreducible
#print axioms k5_runge_unit_inverse
#print axioms k5_runge_unit_power_inverse
#print axioms k5_runge_unit_real_small
#print axioms k5_runge_unit_real_lt_nine_over_125
#print axioms k5_runge_unit_power_real_small
#print axioms k5_runge_unit_pow_146_lt_ten_pow_neg_166

end Erdos686Variant
end Erdos686
