import Erdos699.Proved.Basic

namespace Erdos699

#check primePowerPartGE_five_half_sub_one_eq_self_of_four_dvd_three_dvd
#check i_three_caseI_exists_joint_half_sub_one_cube_from_four_dvd_row_bound
#check i_three_caseI_half_sub_one_cube_from_four_dvd_row_bound

end Erdos699
