import Erdos699.Proved.Basic

namespace Erdos699

#check i_three_caseI_four_dvd_odd_factor_joint_package_from_row_bound
#check i_three_caseI_four_dvd_odd_factor_joint_squeeze_from_row_bound
#check squeezedNormalizedCaseIKernel
#check i_three_caseI_four_dvd_odd_factor_squeezedNormalized_from_row_bound
#check i_three_caseI_four_dvd_odd_factor_false_of_no_squeezedNormalized
#check squeezedNormalized_gap_pos
#check squeezedNormalized_gap_sq_eq_sq
#check squeezedNormalized_discriminant_eq_gap_sq
#check squeezedNormalizedRowOneCandidate
#check squeezedNormalizedRowOneCandidate_half_row_pos
#check squeezedNormalizedCaseIKernel_iff_rowOneCandidate_and_halfRow_dvd
#check squeezedNormalizedRowOneCandidate_halfRow_dvd_iff_gcd_eq
#check squeezedNormalizedCaseIKernel_iff_rowOneCandidate_and_halfRow_gcd_eq
#check squeezedNormalizedRowOneCandidate_not_caseIKernel_of_halfRow_gcd_lt

end Erdos699
