import Erdos699.Proved.Basic

namespace Erdos699

#check consecutiveDivisorKernel
#check consecutiveDivisorKernelBelow
#check rowOneDivisorSplit
#check rowOneDivisorSplit_dvd_mul_sub_one
#check rowOneDivisorSplit_modEq_zero
#check rowOneDivisorSplit_modEq_one_of_one_le
#check rowOneDivisorSplit_of_modEq
#check rowOneDivisorSplit_iff_modEq_of_one_le
#check rowOneDivisorSplit_coprime_of_one_le
#check rowOneDivisorSplit_modEq_chineseRemainder_of_coprime
#check rowOneDivisorSplit_modEq_unique_of_coprime
#check rowOneDivisorSplit_modEq_unique
#check rowOneDivisorSplit_eq_of_lt
#check rowOneDivisorSplit_eq_of_half_bound
#check rowOneDivisorSplit_eq_of_consecutiveDivisorKernelBelow_short
#check sub_one_short_bound_of_two_lt
#check rowOneDivisorSplit_eq_of_sub_one_consecutiveDivisorKernelBelow
#check rowOneDivisorSplit_gcdDiv_of_dvd_mul_sub_one
#check rowOneDivisorSplit_gcdDiv_of_consecutiveDivisorKernel
#check rowOneDivisorSplit_gcdDiv_of_consecutiveDivisorKernelBelow
#check rowOneDivisorSplit_gcd_eq_zeroPart_of_one_le
#check rowOneDivisorSplit_div_gcd_eq_onePart_of_one_le
#check rowOneDivisorSplit_eq_gcdDiv_parts_of_one_le
#check rowOneDivisorSplit_kernel_iff_row_two
#check not_consecutiveDivisorKernel_of_row_two_gcd_lt
#check rowOneDivisorSplit_not_consecutiveDivisorKernel_of_row_two_gcd_lt
#check not_consecutiveDivisorKernelBelow_of_row_two_gcd_lt
#check rowOneDivisorSplit_not_consecutiveDivisorKernelBelow_of_row_two_gcd_lt
#check i_three_caseI_four_dvd_consecutive_kernel_below_from_no_common

end Erdos699
