import Erdos699.Proved.Basic

namespace Erdos699

#check i_three_caseI_row_two_primePowerPartGE_dvd_t_mul_X_sub_t_mul_X_sub_two_t_from_row_bound
#check i_three_caseI_row_two_half_sub_one_dvd_t_mul_X_sub_t_mul_X_sub_two_t_from_row_bound
#check i_three_caseI_row_two_half_large_part_dvd_triple_from_row_bound
#check i_three_caseI_joint_large_part_dvd_factor_mul_X_sub_two_t_from_row_bound
#check i_three_caseI_joint_half_sub_one_dvd_factor_mul_X_sub_two_t_from_row_bound
#check i_three_caseI_joint_half_sub_one_large_part_dvd_factor_mul_X_sub_two_t_from_row_bound

end Erdos699
