/- Kernel-audit entrypoint for the barycentric moment ladder. -/
import ErdosProblems.Erdos686BarycentricMomentLadder

#print axioms Erdos686.Erdos686Variant.momentNumerator_recurrence
#print axioms Erdos686.Erdos686Variant.momentNumerator_eq_X_pow_of_lower_moments
#print axioms Erdos686.Erdos686Variant.rational_momentDelta_eq_zero_iff
#print axioms Erdos686.Erdos686Variant.integer_momentDelta_eq_zero_iff
#print axioms Erdos686.Erdos686Variant.mu_vandermonde_termination_domain
#print axioms Erdos686.Erdos686Variant.mu_vandermonde_termination
#print axioms Erdos686.Erdos686Variant.exists_nonzero_integral_moment_pair
#print axioms Erdos686.Erdos686Variant.exists_first_nonzero_integral_moment_block
#print axioms Erdos686.Erdos686Variant.reflect_matchingPhi
#print axioms Erdos686.Erdos686Variant.reverseMatchingPhi_moment_factorization
#print axioms Erdos686.Erdos686Variant.reverseMatchingPhi_coeff_momentDelta
#print axioms Erdos686.Erdos686Variant.matchingPhi_coeff_momentDelta
#print axioms Erdos686.Erdos686Variant.matchingPhi_natDegree_le_first_moment_block
#print axioms Erdos686.Erdos686Variant.matchingPhi_natDegree_eq_first_nonzero_moment_block
#print axioms Erdos686.Erdos686Variant.matchingPhi_degree_eq_first_nonzero_moment_block
#print axioms Erdos686.Erdos686Variant.matchingPhi_quotient_natDegree_eq_first_nonzero_moment_block
#print axioms Erdos686.Erdos686Variant.fin_matchingPhi_exists_first_nonzero_block_and_exact_degree
#print axioms Erdos686.Erdos686Variant.fin_matchingPhi_ne_zero_of_injective_nonzero_weights
