/- Kernel-audit entrypoint for the low-degree bivariate osculation package. -/
import ErdosProblems.Erdos686LowDegreeOsculation
import ErdosProblems.Erdos686OsculationKernel
import ErdosProblems.Erdos686OsculationTaylor
import ErdosProblems.Erdos686OsculationDichotomy

#print axioms Erdos686.Erdos686Variant.osculationMonomialBasis_card
#print axioms Erdos686.Erdos686Variant.osculation_direction_row_dotProduct
#print axioms Erdos686.Erdos686Variant.affine_cube_subset_card_le_finrank
#print axioms Erdos686.Erdos686Variant.exists_nonzero_bounded_integer_kernel_vector
#print axioms Erdos686.Erdos686Variant.exists_bounded_independent_osculation_kernel_family
#print axioms Erdos686.Erdos686Variant.osculation_owner_square_dvd
#print axioms Erdos686.Erdos686Variant.osculation_support_product_square_dvd
#print axioms Erdos686.Erdos686Variant.osculation_evaluate_eq_zero_of_product_square_bound
#print axioms Erdos686.Erdos686Variant.PrimitiveRationalGCDPresentation.specialization_split
