/- Kernel-audit entrypoint for the basis-free fixed-divisor interface. -/
import ErdosProblems.Erdos686OsculationFixedDivisor

#print axioms Erdos686.Erdos686Variant.IsFixedDivisor.associated
#print axioms Erdos686.Erdos686Variant.IsFixedDivisor.of_associated
#print axioms Erdos686.Erdos686Variant.finitePolynomialFamilyGCD_isFixedDivisor_span
#print axioms Erdos686.Erdos686Variant.exists_isFixedDivisor_of_finiteDimensional
#print axioms Erdos686.Erdos686Variant.exists_isFixedDivisor_boundedOsculationPolynomialSpace
#print axioms Erdos686.Erdos686Variant.exists_fixedDivisorPresentation_of_finiteDimensional
#print axioms Erdos686.Erdos686Variant.osculationCoeffToRatPolynomial_injective
#print axioms Erdos686.Erdos686Variant.boundedOsculationPolynomialSpace_ne_bot_of_entry_bound
#print axioms Erdos686.Erdos686Variant.exists_isFixedDivisor_boundedOsculationPolynomialSpace_of_entry_bound
#print axioms Erdos686.Erdos686Variant.exists_fixedDivisorPresentation_boundedOsculation_of_entry_bound
#print axioms Erdos686.Erdos686Variant.FixedDivisorPresentation.quotient_add
#print axioms Erdos686.Erdos686Variant.FixedDivisorPresentation.quotient_smul
#print axioms Erdos686.Erdos686Variant.FixedDivisorPresentation.residual_has_no_common_nonunit
#print axioms Erdos686.Erdos686Variant.FixedDivisorPresentation.isUnit_gcd_basis_quotients
#print axioms Erdos686.Erdos686Variant.FixedDivisorPresentation.two_specialization_split
