import Mathlib

namespace LocalPotential

/-- Three vertices form a directed 3-cycle under `f`, in either orientation. -/
def IsThreeCycle {α : Type*} (f : α → α) (a b c : α) : Prop :=
  (f a = b ∧ f b = c ∧ f c = a) ∨
  (f a = c ∧ f c = b ∧ f b = a)

/-- Among four distinct vertices, some triple is not a directed 3-cycle for
an arbitrary map.  This is the combinatorial first step in the one-extremum
obstruction. -/
theorem exists_noncycle_triple {α : Type*} (f : α → α)
    (a b c d : α) (hab : a ≠ b) (hac : a ≠ c) (had : a ≠ d)
    (hbc : b ≠ c) (hbd : b ≠ d) (hcd : c ≠ d) :
    ∃ x y z, x ≠ y ∧ x ≠ z ∧ y ≠ z ∧ ¬ IsThreeCycle f x y z := by
  by_cases h : IsThreeCycle f a b c
  · refine ⟨a, b, d, hab, had, hbd, ?_⟩
    intro h'
    rcases h with h | h <;> rcases h' with h' | h'
    · exact hcd (h.2.1.symm.trans h'.2.1)
    · exact hbd (h.1.symm.trans h'.1)
    · exact hbc (h'.1.symm.trans h.1)
    · exact hcd (h.1.symm.trans h'.1)
  · exact ⟨a, b, c, hab, hac, hbc, h⟩

/-- No three distinct members of `S` form a directed cycle under `f`. -/
def NoThreeCycle {α : Type*} (S : Finset α) (f : α → α) : Prop :=
  ∀ ⦃x y z⦄, x ∈ S → y ∈ S → z ∈ S →
    x ≠ y → x ≠ z → y ≠ z → ¬ (f x = y ∧ f y = z ∧ f z = x)

/-- `IsThreeCycle` excludes every orientation of a directed cycle on the
corresponding three-element finset. -/
theorem noThreeCycle_insert {α : Type*} [DecidableEq α] (f : α → α)
    {a b c : α} (hab : a ≠ b) (hac : a ≠ c) (hbc : b ≠ c)
    (hno : ¬ IsThreeCycle f a b c) : NoThreeCycle {a, b, c} f := by
  intro x y z hx hy hz hxy hxz hyz hcycle
  simp only [Finset.mem_insert, Finset.mem_singleton] at hx hy hz
  rcases hx with rfl | rfl | rfl <;>
    rcases hy with rfl | rfl | rfl <;>
      rcases hz with rfl | rfl | rfl <;>
        simp_all [IsThreeCycle]

/-- A depth-two rank for a distinguished star edge.  On a three-vertex set
without a directed 3-cycle this strictly decreases along every non-mutual
choice arrow. -/
def choiceRank {α : Type*} [DecidableEq α] (S : Finset α) (f : α → α)
    (x : α) : Nat :=
  (if f x ∈ S then 1 else 0) +
    (if f x ∈ S ∧ f (f x) ∈ S ∧ f (f x) ≠ x then 1 else 0)

/-- Along a non-mutual choice arrow inside a three-element set, the depth-two
rank strictly decreases in the direction of the arrow. -/
theorem choiceRank_lt_of_arrow {α : Type*} [DecidableEq α]
    (S : Finset α) (f : α → α) (hcard : S.card = 3)
    (hfix : ∀ ⦃z⦄, z ∈ S → f z ≠ z) (hcycle : NoThreeCycle S f)
    {x y : α} (hx : x ∈ S) (hy : y ∈ S) (hxy : x ≠ y)
    (hyx : f y = x) (hnot : f x ≠ y) :
    choiceRank S f x < choiceRank S f y := by
  have hfyS : f y ∈ S := by simpa [hyx] using hx
  by_cases hfxS : f x ∈ S
  · have hfx_ne_x : f x ≠ x := hfix hx
    have hfx_ne_y : f x ≠ y := hnot
    let T : Finset α := {x, y, f x}
    have hTcard : T.card = 3 := by
      simp [T, hxy, hfx_ne_x, hfx_ne_y, Ne.symm]
    have hsub : T ⊆ S := by
      intro z hz
      simp only [T, Finset.mem_insert, Finset.mem_singleton] at hz
      rcases hz with rfl | rfl | rfl
      · exact hx
      · exact hy
      · exact hfxS
    have hle : S.card ≤ T.card := by omega
    have hTS : T = S := (Finset.subset_iff_eq_of_card_le hle).mp hsub
    have hsecond : ¬ (f (f x) ∈ S ∧ f (f x) ≠ x) := by
      rintro ⟨hffS, hff_ne_x⟩
      have hff_ne_fx : f (f x) ≠ f x := hfix hfxS
      have hff_eq_y : f (f x) = y := by
        have : f (f x) ∈ T := by simpa [hTS] using hffS
        simp only [T, Finset.mem_insert, Finset.mem_singleton] at this
        rcases this with this | this | this
        · exact (hff_ne_x this).elim
        · exact this
        · exact (hff_ne_fx this).elim
      have hy_ne_fx : y ≠ f x := fun h => hfx_ne_y h.symm
      have hx_ne_fx : x ≠ f x := fun h => hfx_ne_x h.symm
      exact hcycle hy hx hfxS hxy.symm hy_ne_fx hx_ne_fx
        ⟨hyx, rfl, hff_eq_y⟩
    simp [choiceRank, hfxS, hfyS, hyx, hx, hnot, hsecond]
  · simp [choiceRank, hfxS, hfyS, hyx, hx, hnot]

/-- Symmetric edge weights generated by the ranks of the distinguished edges.
Unused edges receive weight three. -/
def starWeight {α : Type*} [DecidableEq α] (S : Finset α) (f : α → α)
    (x y : α) : Nat :=
  min (if x ∈ S ∧ f x = y then choiceRank S f x else 3)
      (if y ∈ S ∧ f y = x then choiceRank S f y else 3)

@[simp] theorem starWeight_comm {α : Type*} [DecidableEq α]
    (S : Finset α) (f : α → α) (x y : α) :
    starWeight S f x y = starWeight S f y x := by
  simp [starWeight, min_comm]

/-- Under the three-point acyclicity assumptions, every distinguished edge is
the unique minimum in the star of its selected endpoint. -/
theorem starWeight_designated_lt {α : Type*} [DecidableEq α]
    (S : Finset α) (f : α → α) (hcard : S.card = 3)
    (hfix : ∀ ⦃z⦄, z ∈ S → f z ≠ z) (hcycle : NoThreeCycle S f)
    {x y : α} (hx : x ∈ S) (hyx : y ≠ x) (hynot : y ≠ f x) :
    starWeight S f x (f x) < starWeight S f x y := by
  have hfx_ne_y : f x ≠ y := hynot.symm
  have hown_le : starWeight S f x (f x) ≤ choiceRank S f x := by
    simp [starWeight, hx]
  have hrank_lt : choiceRank S f x < 3 := by
    simp only [choiceRank]
    split <;> split <;> omega
  by_cases hpre : y ∈ S ∧ f y = x
  · have hxy : x ≠ y := hyx.symm
    have hranks := choiceRank_lt_of_arrow S f hcard hfix hcycle hx hpre.1 hxy
      hpre.2 hfx_ne_y
    have hry_le : choiceRank S f y ≤ 3 := by
      simp only [choiceRank]
      split <;> split <;> omega
    have hother : starWeight S f x y = choiceRank S f y := by
      simp [starWeight, hx, hfx_ne_y, hpre, Nat.min_eq_right hry_le]
    omega
  · have hother : starWeight S f x y = 3 := by
      simp [starWeight, hx, hfx_ne_y, hpre]
    omega

/-- **One-extremum obstruction.**  Given any loopless choice map and any four
distinct vertices, one can symmetrically weight all pairs so that three
vertices simultaneously see their chosen edge as the unique minimum of their
star.  Hence a deletion rule based on one intrinsically designated minimum
core can never enforce a two-facet cap. -/
theorem three_simultaneous_chosen_minima {α : Type*} [DecidableEq α]
    (f : α → α) (hloop : ∀ x, f x ≠ x)
    (a b c d : α) (hab : a ≠ b) (hac : a ≠ c) (had : a ≠ d)
    (hbc : b ≠ c) (hbd : b ≠ d) (hcd : c ≠ d) :
    ∃ S : Finset α, S.card = 3 ∧
      ∃ w : α → α → Nat,
        (∀ x y, w x y = w y x) ∧
        ∀ x ∈ S, ∀ y, y ≠ x → y ≠ f x → w x (f x) < w x y := by
  rcases exists_noncycle_triple f a b c d hab hac had hbc hbd hcd with
    ⟨x, y, z, hxy, hxz, hyz, hno⟩
  let S : Finset α := {x, y, z}
  have hcard : S.card = 3 := by
    simp [S, hxy, hxz, hyz, Ne.symm]
  have hcycle : NoThreeCycle S f := by
    simpa [S] using noThreeCycle_insert f hxy hxz hyz hno
  have hfix : ∀ ⦃u⦄, u ∈ S → f u ≠ u := by
    intro u _
    exact hloop u
  refine ⟨S, hcard, starWeight S f, ?_, ?_⟩
  · exact fun u v => starWeight_comm S f u v
  · intro u hu v hvu hvf
    exact starWeight_designated_lt S f hcard hfix hcycle hu hvu hvf

end LocalPotential
