/-
Aggregate for ErdosProblems.Erdos686: imports the whole subtree so `lake build ErdosProblems.Erdos686.All` builds it.
Generated by scripts/gen_aggregates.py — do not edit by hand.
-/
import ErdosProblems.Erdos686.Core.All
import ErdosProblems.Erdos686.EvenK.All
import ErdosProblems.Erdos686.K5.All
