/-
Aggregate for ErdosProblems.Erdos699.WIP: imports the whole subtree so `lake build ErdosProblems.Erdos699.WIP.All` builds it.
Generated by scripts/gen_aggregates.py — do not edit by hand.
-/
import ErdosProblems.Erdos699.WIP.BranchFreeFactorSquareCheck
import ErdosProblems.Erdos699.WIP.BranchFreeJointRowBoundCheck
import ErdosProblems.Erdos699.WIP.FourDvdFullHalfRowCheck
import ErdosProblems.Erdos699.WIP.FourDvdHalfRowCheck
import ErdosProblems.Erdos699.WIP.FourDvdOddJointSqueezeCheck
import ErdosProblems.Erdos699.WIP.HalfRowCheck
import ErdosProblems.Erdos699.WIP.HalfRowLargePartCheck
import ErdosProblems.Erdos699.WIP.HalfRowLargePartPackageCheck
import ErdosProblems.Erdos699.WIP.KernelReductionCheck
import ErdosProblems.Erdos699.WIP.OddFactorParityCheck
import ErdosProblems.Erdos699.WIP.RowBoundFactorSquareCheck
import ErdosProblems.Erdos699.WIP.RowOneRowBoundCheck
import ErdosProblems.Erdos699.WIP.RowTwoRowBoundCheck
