/-
Aggregate for ErdosProblems.Erdos686.EvenK.K32: imports the whole subtree so `lake build ErdosProblems.Erdos686.EvenK.K32.All` builds it.
Generated by scripts/gen_aggregates.py — do not edit by hand.
-/
import ErdosProblems.Erdos686.EvenK.K32.CandidateCover
import ErdosProblems.Erdos686.EvenK.K32.CandidateCoverS0
import ErdosProblems.Erdos686.EvenK.K32.CandidateCoverS1
import ErdosProblems.Erdos686.EvenK.K32.CandidateCoverS10
import ErdosProblems.Erdos686.EvenK.K32.CandidateCoverS11
import ErdosProblems.Erdos686.EvenK.K32.CandidateCoverS12
import ErdosProblems.Erdos686.EvenK.K32.CandidateCoverS2
import ErdosProblems.Erdos686.EvenK.K32.CandidateCoverS3
import ErdosProblems.Erdos686.EvenK.K32.CandidateCoverS4
import ErdosProblems.Erdos686.EvenK.K32.CandidateCoverS5
import ErdosProblems.Erdos686.EvenK.K32.CandidateCoverS6
import ErdosProblems.Erdos686.EvenK.K32.CandidateCoverS7
import ErdosProblems.Erdos686.EvenK.K32.CandidateCoverS8
import ErdosProblems.Erdos686.EvenK.K32.CandidateCoverS9
import ErdosProblems.Erdos686.EvenK.K32.CandidateCoverScans
import ErdosProblems.Erdos686.EvenK.K32.CandidateDefs
import ErdosProblems.Erdos686.EvenK.K32.CandidateLogic
import ErdosProblems.Erdos686.EvenK.K32.Core
import ErdosProblems.Erdos686.EvenK.K32.Defs
import ErdosProblems.Erdos686.EvenK.K32.FiniteStrip
import ErdosProblems.Erdos686.EvenK.K32.FiniteStripS0
import ErdosProblems.Erdos686.EvenK.K32.FiniteStripS1
import ErdosProblems.Erdos686.EvenK.K32.FiniteStripS10
import ErdosProblems.Erdos686.EvenK.K32.FiniteStripS11
import ErdosProblems.Erdos686.EvenK.K32.FiniteStripS2
import ErdosProblems.Erdos686.EvenK.K32.FiniteStripS3
import ErdosProblems.Erdos686.EvenK.K32.FiniteStripS4
import ErdosProblems.Erdos686.EvenK.K32.FiniteStripS5
import ErdosProblems.Erdos686.EvenK.K32.FiniteStripS6
import ErdosProblems.Erdos686.EvenK.K32.FiniteStripS7
import ErdosProblems.Erdos686.EvenK.K32.FiniteStripS8
import ErdosProblems.Erdos686.EvenK.K32.FiniteStripS9
import ErdosProblems.Erdos686.EvenK.K32.Table.All
