import Research.FixedChildGlobalCount

namespace IsotropicKernel

open scoped BigOperators

/-- Add one outside point (`none`) to the ordered child coordinates
`Option (Fin d)`. -/
abbrev LocalParentIndex (d : ℕ) := Option (Option (Fin d))

/-- Actual rows of the child generated by `p`, together with one outside label
whose row is given in the favorable basis coordinates `z.1`. -/
def localParentRows
    {K : Type*} [Field K] [Fintype K] [DecidableEq K] {d : ℕ}
    (p : GoodParam K d) (z : (Fin d → K) × K) :
    LocalParentIndex d → (Fin d → K)
  | none => (outsideActual p z).1
  | some o => (goodParamToSample p).1 o

/-- Diagonal coefficients on the same local parent. -/
def localParentCoeff
    {K : Type*} [Field K] [Fintype K] [DecidableEq K] {d : ℕ}
    (p : GoodParam K d) (z : (Fin d → K) × K) :
    LocalParentIndex d → K
  | none => z.2
  | some o => (goodParamToSample p).2 o

/-- The child's full-support isotropic relation, extended by zero at the
outside point. -/
def localChildRelation
    {K : Type*} [MonoidWithZero K] {d : ℕ} (p : Fin d → Kˣ) :
    LocalParentIndex d → K
  | none => 0
  | some o => normalizedNull (fun i => (p i : K)) o

/-- The second parent relation associated to outside basis coordinates `a`.
It has outside coordinate one and child-basis coordinates `-a`. -/
def localOutsideRelation
    {K : Type*} [Ring K] {d : ℕ} (a : Fin d → K) :
    LocalParentIndex d → K
  | none => 1
  | some none => 0
  | some (some i) => -a i

/-- Row-relation predicate for the generated local parent. -/
def IsLocalParentRelation
    {K : Type*} [Field K] [Fintype K] [DecidableEq K] {d : ℕ}
    (p : GoodParam K d) (z : (Fin d → K) × K)
    (u : LocalParentIndex d → K) : Prop :=
  ∑ i, u i • localParentRows p z i = 0

/-- Diagonal bilinear pairing on the generated local parent. -/
def localParentPair
    {K : Type*} [Field K] [Fintype K] [DecidableEq K] {d : ℕ}
    (p : GoodParam K d) (z : (Fin d → K) × K)
    (u v : LocalParentIndex d → K) : K :=
  ∑ i, localParentCoeff p z i * u i * v i

/-- Total isotropy restricted to the local parent's relation space. -/
def LocalParentTotallyIsotropic
    {K : Type*} [Field K] [Fintype K] [DecidableEq K] {d : ℕ}
    (p : GoodParam K d) (z : (Fin d → K) × K) : Prop :=
  ∀ u v, IsLocalParentRelation p z u → IsLocalParentRelation p z v →
    localParentPair p z u v = 0

/-- The extended child null vector is a relation of the generated parent. -/
theorem localChildRelation_is_relation
    {K : Type*} [Field K] [Fintype K] [DecidableEq K] {d : ℕ}
    (p : GoodParam K d) (z : (Fin d → K) × K) :
    IsLocalParentRelation p z (localChildRelation p.1) := by
  simp only [IsLocalParentRelation, Fintype.sum_option, localChildRelation,
    localParentRows, zero_smul, zero_add]
  simpa [goodParamToSample] using
    (normalizedNull_generatedRows_relation
      (fun i => (p.1 i : K)) p.2.1.1)

/-- The outside vector is the second advertised parent relation. -/
theorem localOutsideRelation_is_relation
    {K : Type*} [Field K] [Fintype K] [DecidableEq K] {d : ℕ}
    (p : GoodParam K d) (z : (Fin d → K) × K) :
    IsLocalParentRelation p z (localOutsideRelation z.1) := by
  simp only [IsLocalParentRelation, Fintype.sum_option, localOutsideRelation,
    localParentRows, one_smul, goodParamToSample, generatedRows, zero_smul,
    zero_add, neg_smul]
  simp [outsideActual, Fintype.linearCombination_apply]

/-- If the full local parent relation plane were totally isotropic, the
outside coordinate label would satisfy exactly the two equations defining
`BadOutside`. -/
theorem badOutside_of_localParentTotallyIsotropic
    {K : Type*} [Field K] [Fintype K] [DecidableEq K] {d : ℕ}
    (p : GoodParam K d) (z : (Fin d → K) × K)
    (htotal : LocalParentTotallyIsotropic p z) :
    z ∈ BadOutside p := by
  have hcross := htotal (localChildRelation p.1) (localOutsideRelation z.1)
    (localChildRelation_is_relation p z) (localOutsideRelation_is_relation p z)
  have hself := htotal (localOutsideRelation z.1) (localOutsideRelation z.1)
    (localOutsideRelation_is_relation p z) (localOutsideRelation_is_relation p z)
  constructor
  · simp only [localParentPair, Fintype.sum_option, localParentCoeff,
      localChildRelation, localOutsideRelation, zero_mul, mul_zero, zero_add,
      goodParamToSample, normalizedNull, mul_one] at hcross
    rw [dotProductEquiv_apply_apply]
    simp only [dotProduct, crossVector]
    have hneg : -∑ i, p.2.2.1.1 (some i) * (p.1 i : K) * z.1 i = 0 := by
      simpa [mul_assoc] using hcross
    simpa [mul_assoc] using neg_eq_zero.mp hneg
  · simp only [localParentPair, Fintype.sum_option, localParentCoeff,
      localOutsideRelation, goodParamToSample, mul_one, zero_mul, mul_zero,
      zero_add, neg_mul, mul_neg, neg_neg] at hself
    have hsum : z.2 + ∑ i, p.2.2.1.1 (some i) * z.1 i ^ 2 = 0 := by
      simpa [pow_two, mul_assoc] using hself
    exact eq_neg_of_add_eq_zero_left hsum

/-- Avoiding the exact `BadOutside` equations certifies that the corresponding
parent relation space is not totally isotropic. -/
theorem not_localParentTotallyIsotropic_of_not_badOutside
    {K : Type*} [Field K] [Fintype K] [DecidableEq K] {d : ℕ}
    (p : GoodParam K d) (z : (Fin d → K) × K)
    (hsafe : z ∉ BadOutside p) :
    ¬ LocalParentTotallyIsotropic p z :=
  fun htotal => hsafe (badOutside_of_localParentTotallyIsotropic p z htotal)

end IsotropicKernel
