import Research.Substitution
import Research.CutoffBridge

/-!
# Regular-grid increments as a numerical semigroup

This is the exact geometric-to-arithmetic bridge used in the proposed BCZ
upper bound.  Every element of the additive semigroup generated by increments
`m^n-1` is realizable as a tile-count increment.
-/

namespace Erdos769

/-- The set of all positive-base regular-grid substitution increments in
dimension `n`. -/
def regularIncrements (n : ℕ) : Set ℕ :=
  {x | ∃ m : ℕ, 0 < m ∧ x = m ^ n - 1}

/-- Every nonnegative sum of regular-grid increments is geometrically
realizable, starting from the one-tile tiling. -/
theorem admissible_one_add_of_mem_regularIncrementClosure {n x : ℕ}
    (hx : x ∈ AddSubmonoid.closure (regularIncrements n)) :
    Admissible n (1 + x) := by
  induction hx using AddSubmonoid.closure_induction with
  | mem x hx =>
      obtain ⟨m, hm, rfl⟩ := hx
      have hg := regularGrid_admissible n m hm
      have hp : 0 < m ^ n := pow_pos hm n
      convert hg using 1 <;> omega
  | zero =>
      simpa using regularGrid_admissible n 1 (by omega)
  | add x y hx hy ihx ihy =>
      let i0 : Fin (1 + x) := ⟨0, by omega⟩
      have hs := admissible_substitute ihx ihy i0
      convert hs using 1 <;> omega

/-- A conductor bound for the additive semigroup of regular-grid increments
immediately gives the corresponding bound (shifted by one) for an actual
minimal cubical cutoff. -/
theorem exists_cutoff_le_of_regularIncrement_conductor {n C : ℕ}
    (hC : ∀ x, C ≤ x →
      x ∈ AddSubmonoid.closure (regularIncrements n)) :
    ∃ c, IsCutoff n c ∧ c ≤ C + 1 := by
  apply exists_cutoff_le_of_eventually_admissible
  intro k hk
  have hsub : C ≤ k - 1 := by omega
  have hadm := admissible_one_add_of_mem_regularIncrementClosure (hC (k - 1) hsub)
  convert hadm using 1 <;> omega

end Erdos769
