import Research.GeometricBudgets

namespace Erdos321

noncomputable def depthBlockFraction (d : ℕ) : ℝ :=
  1 / (2 : ℝ) ^ (d + 1)

/-- Product of the logarithmic coordinates generated by depth-dependent lower
blocks. -/
noncomputable def shiftedCoordinateProduct : ℕ → ℝ → ℝ
  | 0, _ => 1
  | d + 1, x =>
      Real.log x * shiftedCoordinateProduct d
        (depthBlockFraction (d + 1) * Real.log x)

/-- Product of the retained mass fractions of those blocks. -/
noncomputable def blockMassRetention (d : ℕ) : ℝ :=
  ∏ r ∈ Finset.range d, (1 - 1 / (2 : ℝ) ^ (r + 2))

/-- The complete shifted lower-block product. -/
noncomputable def shiftedBlockProduct (d : ℕ) (x : ℝ) : ℝ :=
  blockMassRetention d * shiftedCoordinateProduct d x

noncomputable def coordinateError (B : ℝ) (r : ℕ) : ℝ :=
  ((r : ℝ) + 4) * Real.log 2 / ((2 : ℝ) ^ r * B)

noncomputable def coordinateRetention (B : ℝ) (d : ℕ) : ℝ :=
  ∏ r ∈ Finset.range d, (1 - coordinateError B r)

private theorem geometric_sum_le_two (k : ℕ) :
    (∑ r ∈ Finset.range k, 1 / (2 : ℝ) ^ r) ≤ 2 := by
  have h := blockFraction_sum_le_half k
  have heq : (∑ r ∈ Finset.range k, 1 / (2 : ℝ) ^ r) =
      4 * ∑ r ∈ Finset.range k, 1 / (2 : ℝ) ^ (r + 2) := by
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro r hr
    rw [show r + 2 = r + 1 + 1 by omega, pow_succ, pow_succ]
    ring
  rw [heq]
  nlinarith

/-- The sum of every shifted-coordinate relative error is uniformly at most
`10/B`. -/
theorem coordinateError_sum_le
    {B : ℝ} (hB : 0 < B) (d : ℕ) :
    (∑ r ∈ Finset.range d, coordinateError B r) ≤ 10 / B := by
  have hw := weighted_geometric_sum_le_eight d
  have hg := geometric_sum_le_two d
  have hsplit : (∑ r ∈ Finset.range d, coordinateError B r) =
      (Real.log 2 / B) *
        ((∑ r ∈ Finset.range d, ((r : ℝ) + 3) / (2 : ℝ) ^ r) +
          ∑ r ∈ Finset.range d, 1 / (2 : ℝ) ^ r) := by
    calc
      (∑ r ∈ Finset.range d, coordinateError B r) =
          ∑ r ∈ Finset.range d, (Real.log 2 / B) *
            (((r : ℝ) + 3) / (2 : ℝ) ^ r + 1 / (2 : ℝ) ^ r) := by
              apply Finset.sum_congr rfl
              intro r hr
              dsimp [coordinateError]
              field_simp
              ring
      _ = (Real.log 2 / B) *
          ((∑ r ∈ Finset.range d, ((r : ℝ) + 3) / (2 : ℝ) ^ r) +
            ∑ r ∈ Finset.range d, 1 / (2 : ℝ) ^ r) := by
              rw [← Finset.mul_sum, Finset.sum_add_distrib]
  rw [hsplit]
  have hlog2 : 0 ≤ Real.log (2 : ℝ) := Real.log_nonneg (by norm_num)
  have hlog2le : Real.log (2 : ℝ) ≤ 1 := by
    have h := Real.log_le_sub_one_of_pos (by norm_num : (0 : ℝ) < 2)
    norm_num at h ⊢
    exact h
  have hsum :
      (∑ r ∈ Finset.range d, ((r : ℝ) + 3) / (2 : ℝ) ^ r) +
          ∑ r ∈ Finset.range d, 1 / (2 : ℝ) ^ r ≤ 10 := by linarith
  have hfac : 0 ≤ Real.log 2 / B := div_nonneg hlog2 hB.le
  have := mul_le_mul_of_nonneg_left hsum hfac
  have hfac10 : (Real.log 2 / B) * 10 ≤ 10 / B := by
    calc
      (Real.log 2 / B) * 10 = Real.log 2 * (10 / B) := by ring
      _ ≤ 1 * (10 / B) :=
        mul_le_mul_of_nonneg_right hlog2le (by positivity)
      _ = 10 / B := by ring
  exact this.trans hfac10

private theorem coordinateError_nonneg {B : ℝ} (hB : 0 < B) (r : ℕ) :
    0 ≤ coordinateError B r := by
  dsimp [coordinateError]
  positivity

private theorem coordinateError_le_one
    {B : ℝ} (hB : 20 ≤ B) {d r : ℕ} (hr : r < d) :
    coordinateError B r ≤ 1 := by
  have hBpos : 0 < B := by linarith
  have hpoint : coordinateError B r ≤
      ∑ i ∈ Finset.range d, coordinateError B i := by
    apply Finset.single_le_sum (fun i hi => coordinateError_nonneg hBpos i)
    simpa using hr
  have hsum := coordinateError_sum_le hBpos d
  have h10 : 10 / B ≤ 1 := by
    apply (div_le_iff₀ hBpos).2
    linarith
  exact hpoint.trans (hsum.trans h10)

/-- The coordinate-retention product loses at most `10/B`, independently of
its depth. -/
theorem one_sub_ten_div_le_coordinateRetention
    {B : ℝ} (hB : 20 ≤ B) (d : ℕ) :
    1 - 10 / B ≤ coordinateRetention B d := by
  have hBpos : 0 < B := by linarith
  dsimp [coordinateRetention]
  have hp := one_sub_sum_le_prod_one_sub
    (s := Finset.range d) (e := coordinateError B)
    (fun r hr => coordinateError_nonneg hBpos r)
    (fun r hr => coordinateError_le_one hB (Finset.mem_range.mp hr))
  have hs := coordinateError_sum_le hBpos d
  linarith

private theorem log_two_pow {m : ℕ} :
    Real.log ((2 : ℝ) ^ m) = m * Real.log 2 := by
  rw [Real.log_pow]

/-- A scaled starting coordinate still retains the prescribed fraction of the
ordinary iterated-log product. -/
theorem coordinateRetention_mul_product_le_shifted
    {B x y : ℝ} {d : ℕ} (hB : 64 ≤ B)
    (htower : LogTowerAbove B d x)
    (hy : x / (2 : ℝ) ^ (d + 3) ≤ y) :
    coordinateRetention B d * iteratedLogTailProduct d x ≤
      shiftedCoordinateProduct d y := by
  induction d generalizing x y with
  | zero => simp [coordinateRetention, iteratedLogTailProduct,
      shiftedCoordinateProduct]
  | succ d ih =>
      have hBpos : 0 < B := by linarith
      have hx : B ≤ x := htower 0 (by omega)
      have hxpos : 0 < x := lt_of_lt_of_le hBpos hx
      have hylowerpos : 0 < x / (2 : ℝ) ^ (d + 1 + 3) := by positivity
      have hypos : 0 < y := lt_of_lt_of_le hylowerpos hy
      let X := Real.log x
      let Y := Real.log y
      let e := coordinateError B d
      have hX : B ≤ X := by
        simpa [X, realIteratedLog] using htower 1 (by omega)
      have hXpos : 0 < X := lt_of_lt_of_le hBpos hX
      have hlogmono := Real.strictMonoOn_log.monotoneOn hylowerpos hypos hy
      have hloglower : X - ((d : ℝ) + 4) * Real.log 2 ≤ Y := by
        have hpowlog := log_two_pow (m := d + 1 + 3)
        dsimp [X, Y]
        rw [Real.log_div (ne_of_gt hxpos) (by positivity : (2 : ℝ) ^ (d + 1 + 3) ≠ 0),
          hpowlog] at hlogmono
        norm_num [Nat.cast_add, Nat.cast_one] at hlogmono ⊢
        linarith
      have htower' : LogTowerAbove B (1 + d) x := by
        simpa [Nat.add_comm] using htower
      have hgeom := pow_two_mul_terminal_iteratedLog_le
        (B := B) (x := x) (j := 1) (d := d) (by linarith) htower'
      have hterminal : B ≤ realIteratedLog (1 + d) x :=
        htower (1 + d) (by omega)
      have hXB : (2 : ℝ) ^ d * B ≤ X := by
        have hm := mul_le_mul_of_nonneg_left hterminal (by positivity : 0 ≤ (2 : ℝ) ^ d)
        dsimp [X]
        exact hm.trans hgeom
      have he0 : 0 ≤ e := coordinateError_nonneg hBpos d
      have hehalf : e ≤ 1 / 2 := by
        have hpoint : e ≤ ∑ r ∈ Finset.range (d + 1), coordinateError B r := by
          apply Finset.single_le_sum (fun i hi => coordinateError_nonneg hBpos i)
          simp
        have hsum := coordinateError_sum_le hBpos (d + 1)
        have hten : 10 / B ≤ 1 / 2 := by
          apply (div_le_iff₀ hBpos).2
          nlinarith
        exact hpoint.trans (hsum.trans hten)
      have hfactor : (1 - e) * X ≤ Y := by
        have hloss : ((d : ℝ) + 4) * Real.log 2 ≤ e * X := by
          dsimp [e, coordinateError]
          have hnum : 0 ≤ ((d : ℝ) + 4) * Real.log 2 := by positivity
          have hdenpos : 0 < (2 : ℝ) ^ d * B := by positivity
          have hcoef : 0 ≤ ((d : ℝ) + 4) * Real.log 2 /
              ((2 : ℝ) ^ d * B) := by positivity
          have hdiv := mul_le_mul_of_nonneg_left hXB hcoef
          calc
            ((d : ℝ) + 4) * Real.log 2 =
                (((d : ℝ) + 4) * Real.log 2 /
                  ((2 : ℝ) ^ d * B)) * ((2 : ℝ) ^ d * B) := by
                    field_simp
            _ ≤ (((d : ℝ) + 4) * Real.log 2 /
                  ((2 : ℝ) ^ d * B)) * X := hdiv
        nlinarith
      have hYhalf : X / 2 ≤ Y := by nlinarith
      have hchildTower : LogTowerAbove B d X := by
        intro j hj
        rw [← realIteratedLog_succ_shift j x]
        exact htower (j + 1) (by omega)
      have hchildScale : X / (2 : ℝ) ^ (d + 3) ≤
          depthBlockFraction (d + 1) * Y := by
        dsimp [depthBlockFraction]
        rw [show d + 1 + 1 = d + 2 by omega]
        have hpowpos : 0 < (2 : ℝ) ^ (d + 2) := by positivity
        have hm := mul_le_mul_of_nonneg_left hYhalf
          (show 0 ≤ 1 / (2 : ℝ) ^ (d + 2) by positivity)
        calc
          X / (2 : ℝ) ^ (d + 3) = (1 / (2 : ℝ) ^ (d + 2)) * (X / 2) := by
            rw [show d + 3 = (d + 2) + 1 by omega, pow_succ]
            ring
          _ ≤ (1 / (2 : ℝ) ^ (d + 2)) * Y := hm
      have hchild := ih hchildTower hchildScale
      have hret0 : 0 ≤ coordinateRetention B d := by
        dsimp [coordinateRetention]
        apply Finset.prod_nonneg
        intro r hr
        have her := coordinateError_le_one (show 20 ≤ B by linarith)
          (Finset.mem_range.mp hr)
        linarith
      have hp0 := iteratedLogTailProduct_nonneg
        (logPositive_of_tower hBpos hchildTower)
      rw [coordinateRetention, Finset.prod_range_succ]
      dsimp [iteratedLogTailProduct, shiftedCoordinateProduct]
      change (coordinateRetention B d * (1 - e)) *
          (X * iteratedLogTailProduct d X) ≤
        Y * shiftedCoordinateProduct d (depthBlockFraction (d + 1) * Y)
      calc
        (coordinateRetention B d * (1 - e)) *
            (X * iteratedLogTailProduct d X) =
          (coordinateRetention B d * iteratedLogTailProduct d X) *
            ((1 - e) * X) := by ring
        _ ≤ (coordinateRetention B d * iteratedLogTailProduct d X) * Y :=
          mul_le_mul_of_nonneg_left hfactor (mul_nonneg hret0 hp0)
        _ ≤ shiftedCoordinateProduct d (depthBlockFraction (d + 1) * Y) * Y :=
          mul_le_mul_of_nonneg_right hchild (by nlinarith [hXpos, hehalf, hfactor])
        _ = Y * shiftedCoordinateProduct d (depthBlockFraction (d + 1) * Y) := by ring

/-- The mass-retention product is uniformly at least one half. -/
theorem half_le_blockMassRetention (d : ℕ) :
    1 / 2 ≤ blockMassRetention d := by
  dsimp [blockMassRetention]
  have hp := one_sub_sum_le_prod_one_sub
    (s := Finset.range d) (e := fun r => 1 / (2 : ℝ) ^ (r + 2))
    (fun r hr => by positivity)
    (fun r hr => by
      have : (1 : ℝ) ≤ (2 : ℝ) ^ (r + 2) := one_le_pow₀ (by norm_num)
      exact (div_le_one (by positivity)).2 this)
  have hs := blockFraction_sum_le_half d
  linarith

/-- At terminal threshold `64`, all shifted blocks retain at least one quarter
of the ordinary iterated-log tail product, uniformly in depth. -/
theorem quarter_product_le_shiftedBlockProduct
    {x : ℝ} {d : ℕ} (htower : LogTowerAbove 64 d x) :
    iteratedLogTailProduct d x / 4 ≤ shiftedBlockProduct d x := by
  have hscale : x / (2 : ℝ) ^ (d + 3) ≤ x := by
    have hx : 0 ≤ x := le_trans (by norm_num : (0 : ℝ) ≤ 64) (htower 0 (by omega))
    have hp : 1 ≤ (2 : ℝ) ^ (d + 3) := one_le_pow₀ (by norm_num)
    exact (div_le_iff₀ (by positivity : (0 : ℝ) < (2 : ℝ) ^ (d + 3))).2
      (by nlinarith)
  have hc := coordinateRetention_mul_product_le_shifted
    (B := (64 : ℝ)) (by norm_num) htower hscale
  have hret := one_sub_ten_div_le_coordinateRetention (B := (64 : ℝ))
    (by norm_num) d
  have hmass := half_le_blockMassRetention d
  have hp0 : 0 ≤ iteratedLogTailProduct d x :=
    iteratedLogTailProduct_nonneg
      (logPositive_of_tower (by norm_num : (0 : ℝ) < 64) htower)
  have hcoord : (27 / 32 : ℝ) * iteratedLogTailProduct d x ≤
      shiftedCoordinateProduct d x := by
    have hm := mul_le_mul_of_nonneg_right hret hp0
    norm_num at hm
    exact hm.trans hc
  dsimp [shiftedBlockProduct]
  have hm := mul_le_mul hmass hcoord (by positivity) (by positivity)
  nlinarith

end Erdos321
