import Research.Structural

namespace Erdos321

/-- The finite set of exact rational reciprocal subset sums generated by `A`. -/
def subsetSumValues (A : Finset ℕ) : Finset ℚ :=
  A.powerset.image reciprocalSubsetSum

/-- Number of distinct reciprocal subset sums generated by `A`. -/
def subsetSumCount (A : Finset ℕ) : ℕ :=
  (subsetSumValues A).card

/-- The total number of distinct harmonic subsums with denominators at most
`N` (Erdős problem 320's `S(N)`). -/
def harmonicSubsetSumCount (N : ℕ) : ℕ :=
  subsetSumCount (Finset.Icc 1 N)

/-- A valid set attains the full `2^|A|` possible subset sums. -/
theorem subsetSumCount_eq_pow_of_valid {A : Finset ℕ} (hA : Valid A) :
    subsetSumCount A = 2 ^ A.card := by
  rw [subsetSumCount, subsetSumValues, Finset.card_image_iff.mpr]
  · exact Finset.card_powerset A
  · intro S hS T hT hEq
    exact hA S hS T hT hEq

/-- In particular, the extremal function is entropy-bounded by the total
number of harmonic subsums. -/
theorem pow_extremalSize_le_harmonicSubsetSumCount (N : ℕ) :
    2 ^ extremalSize N ≤ harmonicSubsetSumCount N := by
  obtain ⟨A, hA, hcard⟩ := exists_extremizer N
  rw [← hcard, ← subsetSumCount_eq_pow_of_valid hA.2]
  change (subsetSumValues A).card ≤
    (subsetSumValues (Finset.Icc 1 N)).card
  apply Finset.card_le_card
  intro q hq
  rcases Finset.mem_image.mp hq with ⟨S, hS, rfl⟩
  rw [subsetSumValues, Finset.mem_image]
  refine ⟨S, Finset.mem_powerset.mpr ?_, rfl⟩
  exact (Finset.mem_powerset.mp hS).trans hA.1

/-- Every sum from a union is a sum of one value from each part. -/
theorem subsetSumValues_union_subset_sumset (A B : Finset ℕ) :
    subsetSumValues (A ∪ B) ⊆
      Finset.image₂ (fun q r : ℚ => q + r) (subsetSumValues A) (subsetSumValues B) := by
  intro q hq
  rcases Finset.mem_image.mp hq with ⟨S, hS, rfl⟩
  let SA := S ∩ A
  let SB := S \ A
  have hSsub : S ⊆ A ∪ B := Finset.mem_powerset.mp hS
  have hSA : SA ∈ A.powerset := Finset.mem_powerset.mpr Finset.inter_subset_right
  have hSBsub : SB ⊆ B := by
    intro n hn
    have hnS : n ∈ S := (Finset.mem_sdiff.mp hn).1
    have hnNotA : n ∉ A := (Finset.mem_sdiff.mp hn).2
    rcases Finset.mem_union.mp (hSsub hnS) with hnA | hnB
    · exact (hnNotA hnA).elim
    · exact hnB
  have hSB : SB ∈ B.powerset := Finset.mem_powerset.mpr hSBsub
  have hDisjoint : Disjoint SA SB := by
    rw [Finset.disjoint_left]
    intro n hnA hnB
    exact (Finset.mem_sdiff.mp hnB).2 (Finset.mem_inter.mp hnA).2
  have hUnion : SA ∪ SB = S := by
    ext n
    by_cases hnA : n ∈ A <;> simp [SA, SB, hnA]
  have hSum : reciprocalSubsetSum S =
      reciprocalSubsetSum SA + reciprocalSubsetSum SB := by
    rw [← hUnion]
    exact Finset.sum_union hDisjoint
  rw [hSum, Finset.mem_image₂]
  exact ⟨reciprocalSubsetSum SA, Finset.mem_image.mpr ⟨SA, hSA, rfl⟩,
    reciprocalSubsetSum SB, Finset.mem_image.mpr ⟨SB, hSB, rfl⟩, rfl⟩

/-- Distinct-sum counts are submultiplicative under union. -/
theorem subsetSumCount_union_le (A B : Finset ℕ) :
    subsetSumCount (A ∪ B) ≤ subsetSumCount A * subsetSumCount B := by
  exact (Finset.card_le_card (subsetSumValues_union_subset_sumset A B)).trans
    (Finset.card_image₂_le (fun q r : ℚ => q + r) (subsetSumValues A)
      (subsetSumValues B))

/-- Iterated block version of union submultiplicativity. -/
theorem subsetSumCount_biUnion_le_prod {ι : Type*} [DecidableEq ι]
    (P : Finset ι) (F : ι → Finset ℕ) :
    subsetSumCount (P.biUnion F) ≤ ∏ p ∈ P, subsetSumCount (F p) := by
  classical
  induction P using Finset.induction_on with
  | empty => simp [subsetSumCount, subsetSumValues, reciprocalSubsetSum]
  | @insert p P hp ih =>
      rw [Finset.biUnion_insert, Finset.prod_insert hp]
      exact (subsetSumCount_union_le (F p) (P.biUnion F)).trans
        (Nat.mul_le_mul_left _ ih)

end Erdos321
