import Research.VerticalStabilizer

namespace Erdos336

variable {H : Type*} [AddCommGroup H] [Fintype H] [DecidableEq H]

/-- The vertical part of a subgroup of `ℤ × H`. -/
def verticalPart (J : AddSubgroup (ℤ × H)) : AddSubgroup H :=
  J.comap verticalHom

@[simp] theorem mem_verticalPart {J : AddSubgroup (ℤ × H)} {k : H} :
    k ∈ verticalPart J ↔ (0, k) ∈ J := by
  rfl

/-- A subgroup of `ℤ × H` containing an element with positive integer
coordinate is generated by one positive-coordinate element together with its
vertical part. -/
theorem exists_positive_generator_add_vertical
    (J : AddSubgroup (ℤ × H)) (δ : ℤ × H)
    (hδJ : δ ∈ J) (hδpos : 0 < δ.1) :
    ∃ g : ℤ × H, g ∈ J ∧ 0 < g.1 ∧
      ∀ x ∈ J, ∃ n : ℤ, ∃ k ∈ verticalPart J,
        x = n • g + (0, k) := by
  classical
  let P : ℕ → Prop := fun r => 0 < r ∧
    ∃ x : ℤ × H, x ∈ J ∧ x.1 = (r : ℤ)
  have hP : ∃ r, P r := by
    refine ⟨δ.1.toNat, ?_⟩
    have hto : (δ.1.toNat : ℤ) = δ.1 := Int.toNat_of_nonneg hδpos.le
    refine ⟨by omega, δ, hδJ, hto.symm⟩
  let r := Nat.find hP
  have hrP : P r := Nat.find_spec hP
  obtain ⟨hrpos, g, hgJ, hgfst⟩ := hrP
  refine ⟨g, hgJ, ?_, ?_⟩
  · rw [hgfst]
    exact_mod_cast hrpos
  intro x hxJ
  let n : ℤ := x.1 / (r : ℤ)
  let rem : ℤ := x.1 % (r : ℤ)
  let y : ℤ × H := x - n • g
  have hyJ : y ∈ J := J.sub_mem hxJ (J.zsmul_mem hgJ n)
  have hrInt : (0 : ℤ) < (r : ℤ) := by exact_mod_cast hrpos
  have hrem0 : 0 ≤ rem := Int.emod_nonneg _ (by omega)
  have hremLt : rem < (r : ℤ) := Int.emod_lt_of_pos _ hrInt
  have hyfst : y.1 = rem := by
    change x.1 - n * g.1 = rem
    rw [hgfst]
    dsimp [rem, n]
    have hdiv := Int.ediv_mul_add_emod x.1 (r : ℤ)
    linarith
  have hremEq : rem = 0 := by
    by_contra hne
    have hrempos : 0 < rem := lt_of_le_of_ne hrem0 (Ne.symm hne)
    let s := rem.toNat
    have hsInt : (s : ℤ) = rem := Int.toNat_of_nonneg hrem0
    have hspos : 0 < s := by
      have hsposInt : (0 : ℤ) < (s : ℤ) := by rw [hsInt]; exact hrempos
      exact_mod_cast hsposInt
    have hslt : s < r := by
      have hsltInt : (s : ℤ) < (r : ℤ) := by rw [hsInt]; exact hremLt
      exact_mod_cast hsltInt
    have hsP : P s := by
      refine ⟨hspos, y, hyJ, ?_⟩
      rw [hyfst]
      exact hsInt.symm
    have hrs := Nat.find_min' hP hsP
    omega
  have hyzero : y.1 = 0 := by rw [hyfst, hremEq]
  have hydecomp : y = (0, y.2) := Prod.ext hyzero rfl
  refine ⟨n, y.2, ?_, ?_⟩
  · change (0, y.2) ∈ J
    rw [← hydecomp]
    exact hyJ
  · calc
      x = n • g + y := by dsimp [y]; abel
      _ = n • g + (0, y.2) := by rw [hydecomp]

end Erdos336
