import Research.LogApproximation
import Research.AdditiveScaleDensity

namespace Erdos123

/-- The multiplicative semigroup generated by two coprime nontrivial integers
is asymptotically dense on every fixed multiplicative scale: every sufficiently
large `x` has a semigroup point in `(x/ρ,x]`. -/
theorem smooth2_eventually_multiplicatively_leftDense
    {b c : ℕ} (hb : 1 < b) (hc : 1 < c) (hbc : Nat.Coprime b c)
    {ρ : ℝ} (hρ : 1 < ρ) :
    ∃ Y : ℝ, ∀ x : ℝ, Y ≤ x →
      ∃ u v : ℕ, x / ρ < (b : ℝ) ^ u * (c : ℝ) ^ v ∧
        (b : ℝ) ^ u * (c : ℝ) ^ v ≤ x := by
  have hlb : 0 < Real.log (b : ℝ) := Real.log_pos (by exact_mod_cast hb)
  have hlc : 0 < Real.log (c : ℝ) := Real.log_pos (by exact_mod_cast hc)
  have hbpos : (0 : ℝ) < (b : ℝ) := by exact_mod_cast (show 0 < b by omega)
  have hcpos : (0 : ℝ) < (c : ℝ) := by exact_mod_cast (show 0 < c by omega)
  have hρpos : 0 < ρ := by linarith
  have hlogρ : 0 < Real.log ρ := Real.log_pos hρ
  rcases exists_close_power_logs hb hc hbc hlogρ with
    ⟨p, q, hp, hq, hdir | hdir⟩
  · let d : ℝ := (p : ℝ) * Real.log (b : ℝ) - (q : ℝ) * Real.log (c : ℝ)
    have hd : d = (p : ℝ) * Real.log (b : ℝ) - (q : ℝ) * Real.log (c : ℝ) := rfl
    rcases additiveSemigroup_eventually_leftDense hlb hlc hp hq hd hdir.1 hdir.2 with
      ⟨X, hX⟩
    refine ⟨Real.exp X, ?_⟩
    intro x hx
    have hxpos : 0 < x := (Real.exp_pos X).trans_le hx
    have hXlog : X ≤ Real.log x := by
      apply Real.exp_le_exp.mp
      simpa [Real.exp_log hxpos] using hx
    rcases hX (Real.log x) hXlog with ⟨u, v, huvLower, huvUpper⟩
    refine ⟨u, v, ?_, ?_⟩
    · have he := Real.exp_lt_exp.mpr huvLower
      simpa [Real.exp_sub, Real.exp_log hxpos, Real.exp_log hρpos,
        Real.exp_add, Real.exp_nat_mul, Real.exp_log hbpos,
        Real.exp_log hcpos] using he
    · have he := Real.exp_le_exp.mpr huvUpper
      simpa [Real.exp_add, Real.exp_nat_mul, Real.exp_log hbpos,
        Real.exp_log hcpos, Real.exp_log hxpos] using he
  · let d : ℝ := (q : ℝ) * Real.log (c : ℝ) - (p : ℝ) * Real.log (b : ℝ)
    have hd : d = (q : ℝ) * Real.log (c : ℝ) - (p : ℝ) * Real.log (b : ℝ) := rfl
    rcases additiveSemigroup_eventually_leftDense hlc hlb hq hp hd hdir.1 hdir.2 with
      ⟨X, hX⟩
    refine ⟨Real.exp X, ?_⟩
    intro x hx
    have hxpos : 0 < x := (Real.exp_pos X).trans_le hx
    have hXlog : X ≤ Real.log x := by
      apply Real.exp_le_exp.mp
      simpa [Real.exp_log hxpos] using hx
    rcases hX (Real.log x) hXlog with ⟨v, u, huvLower, huvUpper⟩
    refine ⟨u, v, ?_, ?_⟩
    · have he := Real.exp_lt_exp.mpr huvLower
      simpa [Real.exp_sub, Real.exp_log hxpos, Real.exp_log hρpos,
        Real.exp_add, Real.exp_nat_mul, Real.exp_log hbpos,
        Real.exp_log hcpos, add_comm] using he
    · have he := Real.exp_le_exp.mpr huvUpper
      simpa [Real.exp_add, Real.exp_nat_mul, Real.exp_log hbpos,
        Real.exp_log hcpos, Real.exp_log hxpos, add_comm] using he

end Erdos123
