/-
Aggregate for ErdosProblems.Erdos699.Proved: imports the whole subtree so `lake build ErdosProblems.Erdos699.Proved.All` builds it.
Generated by scripts/gen_aggregates.py — do not edit by hand.
-/
import ErdosProblems.Erdos699.Proved.Basic
