import Research.TriangularShells

/-!
# A global normalized counterexample at the triangular shell `t = 6`

The rational oblique lattice generated by `(1,0)` and
`(136/305,273/305)` is one-separated.  It has 128 directed nonzero offsets
within radius six, whereas the unit triangular lattice has 126.  Boundary
accounting on a `365 × 365` patch still leaves a strict excess.
-/

namespace Research

set_option maxRecDepth 100000

/-- Use the standard lexicographic order when choosing representatives of
unordered pairs on product index types. -/
local instance prodLexLinearOrder {α β : Type*} [LinearOrder α]
    [LinearOrder β] : LinearOrder (α × β) :=
  Prod.Lex.instLinearOrder α β

/-- Numerator (with denominator 305) of squared distance for the rational
oblique lattice. -/
def obliqueNormNum (d : ℤ × ℤ) : ℤ :=
  305 * d.1 ^ 2 + 305 * d.2 ^ 2 + 272 * d.1 * d.2

/-- An executable integer window from `-6` through `6`. -/
def intWindow6 : Finset ℤ :=
  {(-6 : ℤ), -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6}

lemma mem_intWindow6_iff (z : ℤ) : z ∈ intWindow6 ↔ -6 ≤ z ∧ z ≤ 6 := by
  simp [intWindow6]
  omega

/-- The exact finite set of nonzero oblique-lattice offsets at distance at most
six.  Completeness of the `[-6,6]²` window is proved below. -/
def shellSixOffsets : Finset (ℤ × ℤ) :=
  ((intWindow6.product intWindow6).filter
    (fun d => d ≠ (0, 0) ∧ obliqueNormNum d ≤ 36 * 305))

/-- Exact kernel census of the oblique offsets. -/
theorem shellSixOffsets_card : shellSixOffsets.card = 128 := by
  decide

/-- Exact boundary statistics for the `365 × 365` patch. -/
theorem shellSixOffsets_weighted_sum :
    ∑ d ∈ shellSixOffsets,
      (365 - d.1.natAbs) * (365 - d.2.natAbs) = 16786618 := by
  decide

/-- Two auxiliary exact boundary statistics, useful for an independent audit
of the weighted count. -/
theorem shellSixOffsets_boundary_sums :
    (∑ d ∈ shellSixOffsets, (d.1.natAbs + d.2.natAbs)) = 732 ∧
    (∑ d ∈ shellSixOffsets, d.1.natAbs * d.2.natAbs) = 998 := by
  decide

/-- The quadratic form's useful sum-of-squares decomposition. -/
lemma obliqueNormNum_decomposition (m n : ℤ) :
    obliqueNormNum (m, n) =
      136 * (m + n) ^ 2 + 169 * m ^ 2 + 169 * n ^ 2 := by
  simp only [obliqueNormNum]
  ring

private lemma int_sq_ge_one {z : ℤ} (hz : z ≠ 0) : 1 ≤ z ^ 2 := by
  have hpos : 0 < z ^ 2 := sq_pos_of_ne_zero hz
  omega

/-- Every nonzero integer offset has squared distance at least one. -/
theorem obliqueNormNum_ge_denominator (m n : ℤ)
    (hne : (m, n) ≠ (0, 0)) : 305 ≤ obliqueNormNum (m, n) := by
  rw [obliqueNormNum_decomposition]
  by_cases hsum : m + n = 0
  · have hm : m ≠ 0 := by
      intro hm
      apply hne
      apply Prod.ext
      · exact hm
      · simpa [hm] using hsum
    have hn : n ≠ 0 := by
      intro hn
      apply hne
      apply Prod.ext
      · simpa [hn] using hsum
      · exact hn
    have hm2 := int_sq_ge_one hm
    have hn2 := int_sq_ge_one hn
    rw [hsum]
    norm_num
    omega
  · have hs2 := int_sq_ge_one hsum
    have hmn : 1 ≤ m ^ 2 + n ^ 2 := by
      by_cases hm : m = 0
      · subst m
        simpa using int_sq_ge_one (by
          intro hn
          exact hne (Prod.ext rfl hn))
      · have hm2 := int_sq_ge_one hm
        nlinarith [sq_nonneg n]
    nlinarith [sq_nonneg m, sq_nonneg n]

/-- Any offset within squared radius 36 lies in the enumeration window. -/
theorem oblique_norm_le_six_bounds (m n : ℤ)
    (h : obliqueNormNum (m, n) ≤ 36 * 305) :
    -6 ≤ m ∧ m ≤ 6 ∧ -6 ≤ n ∧ n ≤ 6 := by
  have hdecomp := obliqueNormNum_decomposition m n
  have hpos1 : 0 ≤ (m + n) ^ 2 := sq_nonneg (m + n)
  have hposm : 0 ≤ m ^ 2 := sq_nonneg m
  have hposn : 0 ≤ n ^ 2 := sq_nonneg n
  have hm2 : 169 * m ^ 2 ≤ 36 * 305 := by nlinarith
  have hn2 : 169 * n ^ 2 ≤ 36 * 305 := by nlinarith
  constructor
  · by_contra hm
    have : m ≤ -7 := by omega
    nlinarith [sq_nonneg (m + 7)]
  constructor
  · by_contra hm
    have : 7 ≤ m := by omega
    nlinarith [sq_nonneg (m - 7)]
  constructor
  · by_contra hn
    have : n ≤ -7 := by omega
    nlinarith [sq_nonneg (n + 7)]
  · by_contra hn
    have : 7 ≤ n := by omega
    nlinarith [sq_nonneg (n - 7)]

/-- Membership characterization proving that the exact offset census is global,
not merely a count in an arbitrary window. -/
theorem mem_shellSixOffsets_iff (d : ℤ × ℤ) :
    d ∈ shellSixOffsets ↔ d ≠ (0, 0) ∧ obliqueNormNum d ≤ 36 * 305 := by
  rcases d with ⟨m, n⟩
  constructor
  · intro h
    exact (Finset.mem_filter.mp h).2
  · intro h
    have hb := oblique_norm_le_six_bounds m n h.2
    apply Finset.mem_filter.mpr
    refine ⟨Finset.mem_product.mpr ⟨?_, ?_⟩, h⟩
    · exact (mem_intWindow6_iff m).2 ⟨hb.1, hb.2.1⟩
    · exact (mem_intWindow6_iff n).2 ⟨hb.2.2.1, hb.2.2.2⟩

/-- Triangular-lattice coordinate census through squared radius 36. -/
def triCoordsWithinThirtySix : Finset (ℤ × ℤ) :=
  ((intWindow6.product intWindow6).filter
    (fun d => triNormSq d ≤ 36)).erase (0, 0)

/-- Exact kernel census: the unit triangular lattice has 126 nonzero points at
ordinary distance at most six. -/
theorem triCoordsWithinThirtySix_card :
    triCoordsWithinThirtySix.card = 126 := by
  decide

/-- Any triangular-lattice coordinate of squared norm at most 36 lies in the
`[-6,6]²` census window. -/
theorem tri_norm_le_thirtySix_bounds (m n : ℤ)
    (h : triNormSq (m, n) ≤ 36) :
    -6 ≤ m ∧ m ≤ 6 ∧ -6 ≤ n ∧ n ≤ 6 := by
  have hm2 : 3 * m ^ 2 ≤ 144 := by
    simp only [triNormSq] at h
    nlinarith [sq_nonneg (m + 2 * n)]
  have hn2 : 3 * n ^ 2 ≤ 144 := by
    simp only [triNormSq] at h
    nlinarith [sq_nonneg (2 * m + n)]
  constructor
  · by_contra hm
    have : m ≤ -7 := by omega
    nlinarith [sq_nonneg (m + 7)]
  constructor
  · by_contra hm
    have : 7 ≤ m := by omega
    nlinarith [sq_nonneg (m - 7)]
  constructor
  · by_contra hn
    have : n ≤ -7 := by omega
    nlinarith [sq_nonneg (n + 7)]
  · by_contra hn
    have : 7 ≤ n := by omega
    nlinarith [sq_nonneg (n - 7)]

/-- Completeness characterization for the radius-six triangular census. -/
theorem mem_triCoordsWithinThirtySix_iff (d : ℤ × ℤ) :
    d ∈ triCoordsWithinThirtySix ↔
      d ≠ (0, 0) ∧ triNormSq d ≤ 36 := by
  rcases d with ⟨m, n⟩
  constructor
  · intro h
    have he := Finset.mem_erase.mp h
    exact ⟨he.1, (Finset.mem_filter.mp he.2).2⟩
  · intro h
    have hb := tri_norm_le_thirtySix_bounds m n h.2
    apply Finset.mem_erase.mpr
    refine ⟨h.1, Finset.mem_filter.mpr ⟨Finset.mem_product.mpr ⟨?_, ?_⟩, h.2⟩⟩
    · exact (mem_intWindow6_iff m).2 ⟨hb.1, hb.2.1⟩
    · exact (mem_intWindow6_iff n).2 ⟨hb.2.2.1, hb.2.2.2⟩

/-- The rational real-plane realization of the oblique lattice. -/
noncomputable def obliquePoint (q : Fin 365 × Fin 365) : ℝ × ℝ :=
  ((q.1.val : ℝ) + (136 / 305 : ℝ) * (q.2.val : ℝ),
    (273 / 305 : ℝ) * (q.2.val : ℝ))

/-- Exact squared-distance identity for two patch points. -/
lemma obliquePoint_sqDist_eq (q s : Fin 365 × Fin 365) :
    sqDist (obliquePoint q) (obliquePoint s) =
      (obliqueNormNum
        (((s.1.val : ℤ) - (q.1.val : ℤ)),
         ((s.2.val : ℤ) - (q.2.val : ℤ))) : ℝ) / 305 := by
  simp only [sqDist, obliquePoint, obliqueNormNum, Int.cast_add, Int.cast_sub,
    Int.cast_mul, Int.cast_pow, Nat.cast_ofNat, Int.cast_ofNat]
  norm_num
  ring

/-- Every patch is one-separated. -/
theorem obliquePoint_oneSeparated :
    ∀ q s : Fin 365 × Fin 365, q ≠ s →
      1 ≤ sqDist (obliquePoint q) (obliquePoint s) := by
  intro q s hqs
  let d : ℤ × ℤ :=
    ((s.1.val : ℤ) - (q.1.val : ℤ),
      (s.2.val : ℤ) - (q.2.val : ℤ))
  have hdne : d ≠ (0, 0) := by
    intro hd
    have hx : s.1.val = q.1.val := by
      have := congrArg Prod.fst hd
      dsimp [d] at this
      omega
    have hy : s.2.val = q.2.val := by
      have := congrArg Prod.snd hd
      dsimp [d] at this
      omega
    exact hqs (Prod.ext (Fin.ext hx.symm) (Fin.ext hy.symm))
  have hz := obliqueNormNum_ge_denominator d.1 d.2 (by
    simpa [d] using hdne)
  have hzR : (305 : ℝ) ≤ (obliqueNormNum d : ℝ) := by exact_mod_cast hz
  rw [obliquePoint_sqDist_eq]
  change 1 ≤ (obliqueNormNum d : ℝ) / 305
  norm_num at hzR ⊢
  linarith

/-- Coordinate offsets certified by the exact shell census. -/
abbrev ShellSixOffset := {d : ℤ × ℤ // d ∈ shellSixOffsets}

private lemma natAbs_le_six_of_bounds (z : ℤ) (hl : -6 ≤ z) (hu : z ≤ 6) :
    z.natAbs ≤ 6 := by
  by_cases hz : 0 ≤ z
  · have hc : (z.natAbs : ℤ) = z := Int.natAbs_of_nonneg hz
    omega
  · have hn : 0 ≤ -z := by omega
    have hc : (z.natAbs : ℤ) = -z := by
      calc
        (z.natAbs : ℤ) = ((-z).natAbs : ℕ) := by rw [Int.natAbs_neg]
        _ = -z := Int.natAbs_of_nonneg hn
    omega

lemma shellSixOffset_natAbs_le (d : ShellSixOffset) :
    d.val.1.natAbs ≤ 6 ∧ d.val.2.natAbs ≤ 6 := by
  have hm := (mem_shellSixOffsets_iff d.val).mp d.property
  have hb := oblique_norm_le_six_bounds d.val.1 d.val.2 hm.2
  exact ⟨natAbs_le_six_of_bounds d.val.1 hb.1 hb.2.1,
    natAbs_le_six_of_bounds d.val.2 hb.2.2.1 hb.2.2.2⟩

/-- Compactly enumerate the possible starts of a signed one-dimensional offset. -/
def signedStart (d : ℤ) (hd : d.natAbs ≤ 6)
    (k : Fin (365 - d.natAbs)) : Fin 365 :=
  if h : d < 0 then
    ⟨k.val + d.natAbs, by omega⟩
  else
    ⟨k.val, by omega⟩

/-- Corresponding endpoint of a signed one-dimensional offset. -/
def signedEnd (d : ℤ) (hd : d.natAbs ≤ 6)
    (k : Fin (365 - d.natAbs)) : Fin 365 :=
  if h : d < 0 then
    ⟨k.val, by omega⟩
  else
    ⟨k.val + d.natAbs, by omega⟩

lemma signedEnd_sub_signedStart (d : ℤ) (hd : d.natAbs ≤ 6)
    (k : Fin (365 - d.natAbs)) :
    ((signedEnd d hd k).val : ℤ) - ((signedStart d hd k).val : ℤ) = d := by
  by_cases h : d < 0
  · have hn : 0 ≤ -d := by omega
    have hc : (d.natAbs : ℤ) = -d := by
      calc
        (d.natAbs : ℤ) = ((-d).natAbs : ℕ) := by rw [Int.natAbs_neg]
        _ = -d := Int.natAbs_of_nonneg hn
    simp [signedEnd, signedStart, h, hc]
  · have hp : 0 ≤ d := by omega
    have hc : (d.natAbs : ℤ) = d := Int.natAbs_of_nonneg hp
    simp [signedEnd, signedStart, h, hc]

lemma signedStart_injective (d : ℤ) (hd : d.natAbs ≤ 6) :
    Function.Injective (signedStart d hd) := by
  intro a b h
  apply Fin.ext
  by_cases hdneg : d < 0
  · simpa [signedStart, hdneg] using h
  · simpa [signedStart, hdneg] using h

/-- A certified directed incidence consists of an allowed offset and one of its
valid starts in each coordinate. -/
abbrev ShellSixIncidence :=
  Σ d : ShellSixOffset,
    Fin (365 - d.val.1.natAbs) × Fin (365 - d.val.2.natAbs)

/-- Start patch index of a certified incidence. -/
def shellSixIncidenceStart (z : ShellSixIncidence) : Fin 365 × Fin 365 :=
  (signedStart z.1.val.1 (shellSixOffset_natAbs_le z.1).1 z.2.1,
   signedStart z.1.val.2 (shellSixOffset_natAbs_le z.1).2 z.2.2)

/-- End patch index of a certified incidence. -/
def shellSixIncidenceEnd (z : ShellSixIncidence) : Fin 365 × Fin 365 :=
  (signedEnd z.1.val.1 (shellSixOffset_natAbs_le z.1).1 z.2.1,
   signedEnd z.1.val.2 (shellSixOffset_natAbs_le z.1).2 z.2.2)

/-- Endpoint difference recovers the certified offset exactly. -/
lemma shellSixIncidence_difference (z : ShellSixIncidence) :
    (((shellSixIncidenceEnd z).1.val : ℤ) -
        ((shellSixIncidenceStart z).1.val : ℤ),
      ((shellSixIncidenceEnd z).2.val : ℤ) -
        ((shellSixIncidenceStart z).2.val : ℤ)) = z.1.val := by
  apply Prod.ext
  · exact signedEnd_sub_signedStart z.1.val.1
      (shellSixOffset_natAbs_le z.1).1 z.2.1
  · exact signedEnd_sub_signedStart z.1.val.2
      (shellSixOffset_natAbs_le z.1).2 z.2.2

/-- The endpoint pair attached to a certified incidence. -/
def shellSixIncidencePair (z : ShellSixIncidence) :
    (Fin 365 × Fin 365) × (Fin 365 × Fin 365) :=
  (shellSixIncidenceStart z, shellSixIncidenceEnd z)

lemma shellSixIncidencePair_injective :
    Function.Injective shellSixIncidencePair := by
  rintro ⟨d, k⟩ ⟨e, l⟩ hpair
  have hsx := congrArg (fun q => q.1.1.val) hpair
  have hsy := congrArg (fun q => q.1.2.val) hpair
  have hex := congrArg (fun q => q.2.1.val) hpair
  have hey := congrArg (fun q => q.2.2.val) hpair
  have hdval : d.val = e.val := by
    apply Prod.ext
    · calc
        d.val.1 =
            ((shellSixIncidenceEnd ⟨d, k⟩).1.val : ℤ) -
              ((shellSixIncidenceStart ⟨d, k⟩).1.val : ℤ) :=
          (congrArg Prod.fst (shellSixIncidence_difference ⟨d, k⟩)).symm
        _ = ((shellSixIncidenceEnd ⟨e, l⟩).1.val : ℤ) -
              ((shellSixIncidenceStart ⟨e, l⟩).1.val : ℤ) := by
          exact congrArg₂ (fun a b : ℕ => (a : ℤ) - (b : ℤ)) hex hsx
        _ = e.val.1 :=
          congrArg Prod.fst (shellSixIncidence_difference ⟨e, l⟩)
    · calc
        d.val.2 =
            ((shellSixIncidenceEnd ⟨d, k⟩).2.val : ℤ) -
              ((shellSixIncidenceStart ⟨d, k⟩).2.val : ℤ) :=
          (congrArg Prod.snd (shellSixIncidence_difference ⟨d, k⟩)).symm
        _ = ((shellSixIncidenceEnd ⟨e, l⟩).2.val : ℤ) -
              ((shellSixIncidenceStart ⟨e, l⟩).2.val : ℤ) := by
          exact congrArg₂ (fun a b : ℕ => (a : ℤ) - (b : ℤ)) hey hsy
        _ = e.val.2 :=
          congrArg Prod.snd (shellSixIncidence_difference ⟨e, l⟩)
  have hde : d = e := Subtype.ext hdval
  subst e
  have hstart : shellSixIncidenceStart ⟨d, k⟩ =
      shellSixIncidenceStart ⟨d, l⟩ := congrArg Prod.fst hpair
  have hkx : k.1 = l.1 :=
    signedStart_injective d.val.1 (shellSixOffset_natAbs_le d).1
      (congrArg Prod.fst hstart)
  have hky : k.2 = l.2 :=
    signedStart_injective d.val.2 (shellSixOffset_natAbs_le d).2
      (congrArg Prod.snd hstart)
  have hkl : k = l := Prod.ext hkx hky
  subst l
  rfl

/-- Embedding of all certified incidences into directed patch-index pairs. -/
def shellSixIncidenceEmbedding :
    ShellSixIncidence ↪
      ((Fin 365 × Fin 365) × (Fin 365 × Fin 365)) :=
  ⟨shellSixIncidencePair, shellSixIncidencePair_injective⟩

/-- There are exactly 16,786,618 certified directed incidences; the proof
reduces the dependent cardinality to the 169-cell offset census rather than
enumerating the inhabitants. -/
theorem shellSixIncidence_card :
    Fintype.card ShellSixIncidence = 16786618 := by
  rw [Fintype.card_sigma]
  simp only [Fintype.card_prod, Fintype.card_fin]
  calc
    (∑ d : ShellSixOffset,
        (365 - d.val.1.natAbs) * (365 - d.val.2.natAbs)) =
        ∑ d ∈ shellSixOffsets,
          (365 - d.1.natAbs) * (365 - d.2.natAbs) := by
      symm
      exact Finset.sum_subtype shellSixOffsets (fun _ => Iff.rfl)
        (fun d => (365 - d.1.natAbs) * (365 - d.2.natAbs))
    _ = 16786618 := shellSixOffsets_weighted_sum

/-- Directed pairs at squared distance at most 36. -/
noncomputable def radiusSixDirectedPairs {α : Type*} [Fintype α]
    [DecidableEq α] (p : α → ℝ × ℝ) : Finset (α × α) :=
  (Finset.univ.product Finset.univ).filter fun q =>
    q.1 ≠ q.2 ∧ sqDist (p q.1) (p q.2) ≤ 36

lemma mem_radiusSixDirectedPairs_iff {α : Type*} [Fintype α]
    [DecidableEq α] (p : α → ℝ × ℝ) (q : α × α) :
    q ∈ radiusSixDirectedPairs p ↔
      q.1 ≠ q.2 ∧ sqDist (p q.1) (p q.2) ≤ 36 := by
  simp [radiusSixDirectedPairs]

/-- Directed pairs written with the ordinary Euclidean-distance threshold six. -/
noncomputable def radiusSixOrdinaryDirectedPairs {α : Type*} [Fintype α]
    [DecidableEq α] (p : α → ℝ × ℝ) : Finset (α × α) :=
  (Finset.univ.product Finset.univ).filter fun q =>
    q.1 ≠ q.2 ∧ Real.sqrt (sqDist (p q.1) (p q.2)) ≤ 6

/-- Ordinary- and squared-distance directed definitions agree exactly. -/
theorem radiusSixOrdinaryDirectedPairs_eq {α : Type*} [Fintype α]
    [DecidableEq α] (p : α → ℝ × ℝ) :
    radiusSixOrdinaryDirectedPairs p = radiusSixDirectedPairs p := by
  ext q
  simp only [radiusSixOrdinaryDirectedPairs, radiusSixDirectedPairs,
    Finset.mem_filter, Finset.mem_product, Finset.mem_univ, true_and]
  constructor
  · rintro ⟨hne, hd⟩
    refine ⟨hne, ?_⟩
    rw [Real.sqrt_le_iff] at hd
    norm_num at hd ⊢
    exact hd
  · rintro ⟨hne, hd⟩
    refine ⟨hne, ?_⟩
    rw [Real.sqrt_le_iff]
    norm_num at hd ⊢
    exact hd

/-- The finite type of directed pairs satisfying the radius-six relation.  This
predicate representation avoids reducing an enormous Cartesian-product
finset in the structural injection proof. -/
def RadiusSixPairType {α : Type*} (p : α → ℝ × ℝ) :=
  {q : α × α // q.1 ≠ q.2 ∧ sqDist (p q.1) (p q.2) ≤ 36}

noncomputable instance RadiusSixPairType.instFintype {α : Type*} [Fintype α]
    (p : α → ℝ × ℝ) : Fintype (RadiusSixPairType p) := by
  letI : Finite (RadiusSixPairType p) :=
    Finite.of_injective (fun q : RadiusSixPairType p => q.val)
      Subtype.val_injective
  exact Fintype.ofFinite (RadiusSixPairType p)

/-- The predicate-subtype cardinality agrees with the direct finset count. -/
theorem RadiusSixPairType_card_eq {α : Type*} [Fintype α]
    [DecidableEq α] (p : α → ℝ × ℝ) :
    Fintype.card (RadiusSixPairType p) = (radiusSixDirectedPairs p).card := by
  classical
  let e : RadiusSixPairType p ≃ {q // q ∈ radiusSixDirectedPairs p} :=
    Equiv.subtypeEquivRight fun q => (mem_radiusSixDirectedPairs_iff p q).symm
  calc
    Fintype.card (RadiusSixPairType p) =
        Fintype.card {q // q ∈ radiusSixDirectedPairs p} :=
      Fintype.card_congr e
    _ = (radiusSixDirectedPairs p).card :=
      Fintype.card_coe (radiusSixDirectedPairs p)

/-- One ordered representative of every radius-six unordered pair. -/
noncomputable def radiusSixOrderedPairs {α : Type*} [Fintype α]
    [LinearOrder α] (p : α → ℝ × ℝ) : Finset (α × α) :=
  (Finset.univ.product Finset.univ).filter fun q =>
    q.1 < q.2 ∧ sqDist (p q.1) (p q.2) ≤ 36

/-- Direct unordered representatives with ordinary distance at most six. -/
noncomputable def radiusSixOrdinaryOrderedPairs {α : Type*} [Fintype α]
    [LinearOrder α] (p : α → ℝ × ℝ) : Finset (α × α) :=
  (Finset.univ.product Finset.univ).filter fun q =>
    q.1 < q.2 ∧ Real.sqrt (sqDist (p q.1) (p q.2)) ≤ 6

/-- Ordinary- and squared-distance direct unordered definitions agree exactly. -/
theorem radiusSixOrdinaryOrderedPairs_eq {α : Type*} [Fintype α]
    [LinearOrder α] (p : α → ℝ × ℝ) :
    radiusSixOrdinaryOrderedPairs p = radiusSixOrderedPairs p := by
  ext q
  simp only [radiusSixOrdinaryOrderedPairs, radiusSixOrderedPairs,
    Finset.mem_filter, Finset.mem_product, Finset.mem_univ, true_and]
  constructor
  · rintro ⟨hlt, hd⟩
    refine ⟨hlt, ?_⟩
    rw [Real.sqrt_le_iff] at hd
    norm_num at hd ⊢
    exact hd
  · rintro ⟨hlt, hd⟩
    refine ⟨hlt, ?_⟩
    rw [Real.sqrt_le_iff]
    norm_num at hd ⊢
    exact hd

lemma shellSixIncidencePair_valid (z : ShellSixIncidence) :
    let q := shellSixIncidencePair z
    q.1 ≠ q.2 ∧ sqDist (obliquePoint q.1) (obliquePoint q.2) ≤ 36 := by
  have hoff := (mem_shellSixOffsets_iff z.1.val).mp z.1.property
  change shellSixIncidenceStart z ≠ shellSixIncidenceEnd z ∧
    sqDist (obliquePoint (shellSixIncidenceStart z))
      (obliquePoint (shellSixIncidenceEnd z)) ≤ 36
  constructor
  · intro heq
    apply hoff.1
    rw [← shellSixIncidence_difference z, heq]
    simp
  · rw [obliquePoint_sqDist_eq, shellSixIncidence_difference]
    have hzR : (obliqueNormNum z.1.val : ℝ) ≤ (36 * 305 : ℝ) := by
      exact_mod_cast hoff.2
    norm_num at hzR ⊢
    linarith

/-- Embed every structurally certified incidence into the predicate type of
actual radius-six directed pairs. -/
def shellSixIncidenceToDirected :
    ShellSixIncidence ↪ RadiusSixPairType obliquePoint where
  toFun z := ⟨shellSixIncidencePair z, shellSixIncidencePair_valid z⟩
  inj' := by
    intro z w h
    apply shellSixIncidencePair_injective
    exact congrArg Subtype.val h

/-- The `365 × 365` patch contains at least 16,786,618 directed short pairs. -/
theorem obliquePatch_directed_card_ge :
    16786618 ≤ (radiusSixDirectedPairs obliquePoint).card := by
  calc
    16786618 = Fintype.card ShellSixIncidence := shellSixIncidence_card.symm
    _ ≤ Fintype.card (RadiusSixPairType obliquePoint) :=
      Fintype.card_le_of_embedding shellSixIncidenceToDirected
    _ = (radiusSixDirectedPairs obliquePoint).card :=
      RadiusSixPairType_card_eq obliquePoint

lemma sqDist_symm (p q : ℝ × ℝ) : sqDist p q = sqDist q p := by
  simp only [sqDist]
  ring

lemma swap_mem_radiusSixDirectedPairs_iff {α : Type*} [Fintype α]
    [DecidableEq α] (p : α → ℝ × ℝ) (q : α × α) :
    q.swap ∈ radiusSixDirectedPairs p ↔ q ∈ radiusSixDirectedPairs p := by
  rw [mem_radiusSixDirectedPairs_iff, mem_radiusSixDirectedPairs_iff]
  rcases q with ⟨a, b⟩
  simp only [Prod.swap_prod_mk, Prod.fst, Prod.snd]
  constructor
  · rintro ⟨hne, hd⟩
    exact ⟨hne.symm, by rwa [sqDist_symm]⟩
  · rintro ⟨hne, hd⟩
    exact ⟨hne.symm, by rwa [sqDist_symm]⟩

/-- Every unordered radius-six pair contributes exactly its two orientations to
the directed count. -/
theorem radiusSixDirected_card_eq_twice_ordered {α : Type*}
    [Fintype α] [DecidableEq α] [LinearOrder α] (p : α → ℝ × ℝ) :
    (radiusSixDirectedPairs p).card =
      2 * (radiusSixOrderedPairs p).card := by
  classical
  let inc := radiusSixDirectedPairs p
  let lower := inc.filter fun q : α × α => q.1 < q.2
  let upper := inc.filter fun q : α × α => q.2 < q.1
  have hlower : lower = radiusSixOrderedPairs p := by
    ext q
    simp only [lower, inc, radiusSixOrderedPairs, radiusSixDirectedPairs,
      Finset.mem_filter, Finset.mem_product, Finset.mem_univ, true_and]
    aesop
  have hsplit : lower ∪ upper = inc := by
    ext q
    simp only [lower, upper, Finset.mem_union, Finset.mem_filter]
    constructor
    · rintro (h | h) <;> exact h.1
    · intro hq
      have hne : q.1 ≠ q.2 :=
        (mem_radiusSixDirectedPairs_iff p q).mp hq |>.1
      rcases lt_or_gt_of_ne hne with hlt | hgt
      · exact Or.inl ⟨hq, hlt⟩
      · exact Or.inr ⟨hq, hgt⟩
  have hdisj : Disjoint lower upper := by
    rw [Finset.disjoint_left]
    intro q hql hqu
    exact (not_lt_of_ge (le_of_lt (Finset.mem_filter.mp hql).2))
      (Finset.mem_filter.mp hqu).2
  have hcards : lower.card = upper.card := by
    apply Finset.card_bij (fun q _ => q.swap)
    · intro q hq
      apply Finset.mem_filter.mpr
      exact ⟨(swap_mem_radiusSixDirectedPairs_iff p q).mpr
        (Finset.mem_filter.mp hq).1, (Finset.mem_filter.mp hq).2⟩
    · intro a ha b hb hab
      exact Prod.swap_injective hab
    · intro b hb
      refine ⟨b.swap, ?_, Prod.swap_swap b⟩
      apply Finset.mem_filter.mpr
      exact ⟨(swap_mem_radiusSixDirectedPairs_iff p b).mpr
        (Finset.mem_filter.mp hb).1, (Finset.mem_filter.mp hb).2⟩
  have hc := Finset.card_union_of_disjoint hdisj
  calc
    inc.card = lower.card + upper.card := by rw [← hsplit]; exact hc
    _ = lower.card + lower.card := by rw [← hcards]
    _ = 2 * lower.card := by omega
    _ = 2 * (radiusSixOrderedPairs p).card := by rw [hlower]

/-- At least 8,393,309 direct unordered pairs occur in the finite patch. -/
theorem obliquePatch_ordered_card_ge :
    8393309 ≤ (radiusSixOrderedPairs obliquePoint).card := by
  have hlower := obliquePatch_directed_card_ge
  have hdouble := radiusSixDirected_card_eq_twice_ordered obliquePoint
  rw [hdouble] at hlower
  omega

/-- The finite patch already beats the triangular normalized prediction:
`16,786,618 > 126 · 133,225 = 16,786,350`. -/
theorem obliquePatch_global_normalized_excess :
    126 * Fintype.card (Fin 365 × Fin 365) <
      (radiusSixDirectedPairs obliquePoint).card := by
  have h := obliquePatch_directed_card_ge
  simp only [Fintype.card_prod, Fintype.card_fin]
  norm_num
  omega

/-- Direct unordered form of the same strict excess:
`8,393,309 > 63 · 133,225 = 8,393,175`. -/
theorem obliquePatch_unordered_normalized_excess :
    63 * Fintype.card (Fin 365 × Fin 365) <
      (radiusSixOrderedPairs obliquePoint).card := by
  have h := obliquePatch_ordered_card_ge
  simp only [Fintype.card_prod, Fintype.card_fin]
  norm_num
  omega

/-- Coarse exact coordinate bounds for separating translated copies. -/
theorem obliquePoint_coordinate_bounds (q : Fin 365 × Fin 365) :
    0 ≤ (obliquePoint q).1 ∧ (obliquePoint q).1 ≤ 600 ∧
      0 ≤ (obliquePoint q).2 ∧ (obliquePoint q).2 ≤ 400 := by
  have hq1N : q.1.val ≤ 364 := by omega
  have hq2N : q.2.val ≤ 364 := by omega
  have hq1 : (q.1.val : ℝ) ≤ 364 := by exact_mod_cast hq1N
  have hq2 : (q.2.val : ℝ) ≤ 364 := by exact_mod_cast hq2N
  have hq10 : (0 : ℝ) ≤ q.1.val := by positivity
  have hq20 : (0 : ℝ) ≤ q.2.val := by positivity
  simp only [obliquePoint]
  constructor
  · positivity
  · constructor
    · norm_num
      nlinarith
    · constructor
      · positivity
      · norm_num
        nlinarith

/-- `m` copies of the oblique patch, translated 2000 units apart. -/
noncomputable def obliqueBlocks (m : ℕ)
    (q : Fin m × (Fin 365 × Fin 365)) : ℝ × ℝ :=
  (2000 * (q.1.val : ℝ) + (obliquePoint q.2).1,
    (obliquePoint q.2).2)

/-- Every replicated configuration remains one-separated. -/
theorem obliqueBlocks_oneSeparated (m : ℕ) :
    ∀ q s : Fin m × (Fin 365 × Fin 365), q ≠ s →
      1 ≤ sqDist (obliqueBlocks m q) (obliqueBlocks m s) := by
  intro q s hqs
  by_cases hb : q.1 = s.1
  · have hp : q.2 ≠ s.2 := by
      intro hp
      exact hqs (Prod.ext hb hp)
    have h := obliquePoint_oneSeparated q.2 s.2 hp
    simp only [obliqueBlocks, sqDist] at h ⊢
    rw [hb]
    convert h using 1 <;> ring
  · have hbval : q.1.val ≠ s.1.val := fun h => hb (Fin.ext h)
    rcases lt_or_gt_of_ne hbval with hlt | hgt
    · have hstep : (q.1.val : ℝ) + 1 ≤ (s.1.val : ℝ) := by
        exact_mod_cast (Nat.succ_le_iff.mpr hlt)
      have hq := obliquePoint_coordinate_bounds q.2
      have hs := obliquePoint_coordinate_bounds s.2
      have hdx : 1400 ≤
          (2000 * (s.1.val : ℝ) + (obliquePoint s.2).1) -
            (2000 * (q.1.val : ℝ) + (obliquePoint q.2).1) := by
        nlinarith
      simp only [obliqueBlocks, sqDist]
      nlinarith [sq_nonneg ((obliquePoint q.2).2 - (obliquePoint s.2).2)]
    · have hstep : (s.1.val : ℝ) + 1 ≤ (q.1.val : ℝ) := by
        exact_mod_cast (Nat.succ_le_iff.mpr hgt)
      have hq := obliquePoint_coordinate_bounds q.2
      have hs := obliquePoint_coordinate_bounds s.2
      have hdx : 1400 ≤
          (2000 * (q.1.val : ℝ) + (obliquePoint q.2).1) -
            (2000 * (s.1.val : ℝ) + (obliquePoint s.2).1) := by
        nlinarith
      simp only [obliqueBlocks, sqDist]
      nlinarith [sq_nonneg ((obliquePoint q.2).2 - (obliquePoint s.2).2)]

/-- Certified within-block incidences in `m` translated copies. -/
abbrev ShellSixBlockIncidence (m : ℕ) := Fin m × ShellSixIncidence

/-- Endpoint pair of a certified incidence in a translated block. -/
def shellSixBlockIncidencePair (m : ℕ) (z : ShellSixBlockIncidence m) :
    (Fin m × (Fin 365 × Fin 365)) ×
      (Fin m × (Fin 365 × Fin 365)) :=
  ((z.1, shellSixIncidenceStart z.2),
    (z.1, shellSixIncidenceEnd z.2))

lemma shellSixBlockIncidencePair_injective (m : ℕ) :
    Function.Injective (shellSixBlockIncidencePair m) := by
  rintro ⟨b, z⟩ ⟨c, w⟩ h
  have hbc : b = c := congrArg (fun q => q.1.1) h
  have hstart : shellSixIncidenceStart z = shellSixIncidenceStart w :=
    congrArg (fun q => q.1.2) h
  have hend : shellSixIncidenceEnd z = shellSixIncidenceEnd w :=
    congrArg (fun q => q.2.2) h
  have hzw : z = w := shellSixIncidencePair_injective (Prod.ext hstart hend)
  exact Prod.ext hbc hzw

lemma shellSixBlockIncidencePair_valid (m : ℕ)
    (z : ShellSixBlockIncidence m) :
    let q := shellSixBlockIncidencePair m z
    q.1 ≠ q.2 ∧ sqDist (obliqueBlocks m q.1) (obliqueBlocks m q.2) ≤ 36 := by
  have hv := shellSixIncidencePair_valid z.2
  change shellSixIncidenceStart z.2 ≠ shellSixIncidenceEnd z.2 ∧
    sqDist (obliquePoint (shellSixIncidenceStart z.2))
      (obliquePoint (shellSixIncidenceEnd z.2)) ≤ 36 at hv
  change (z.1, shellSixIncidenceStart z.2) ≠
      (z.1, shellSixIncidenceEnd z.2) ∧
    sqDist (obliqueBlocks m (z.1, shellSixIncidenceStart z.2))
      (obliqueBlocks m (z.1, shellSixIncidenceEnd z.2)) ≤ 36
  constructor
  · intro h
    exact hv.1 (congrArg Prod.snd h)
  · have heq :
        sqDist (obliqueBlocks m (z.1, shellSixIncidenceStart z.2))
          (obliqueBlocks m (z.1, shellSixIncidenceEnd z.2)) =
        sqDist (obliquePoint (shellSixIncidenceStart z.2))
          (obliquePoint (shellSixIncidenceEnd z.2)) := by
        simp only [obliqueBlocks, sqDist]
        ring
    rw [heq]
    exact hv.2

/-- Structural embedding of all within-block certified incidences. -/
def shellSixBlockIncidenceToDirected (m : ℕ) :
    ShellSixBlockIncidence m ↪ RadiusSixPairType (obliqueBlocks m) where
  toFun z := ⟨shellSixBlockIncidencePair m z,
    shellSixBlockIncidencePair_valid m z⟩
  inj' := by
    intro z w h
    apply shellSixBlockIncidencePair_injective m
    exact congrArg Subtype.val h

/-- Exact cardinality of the block-incidence type. -/
theorem shellSixBlockIncidence_card (m : ℕ) :
    Fintype.card (ShellSixBlockIncidence m) = m * 16786618 := by
  rw [Fintype.card_prod, Fintype.card_fin, shellSixIncidence_card]

/-- `m` blocks retain at least `m·16,786,618` directed radius-six pairs. -/
theorem obliqueBlocks_directed_card_ge (m : ℕ) :
    m * 16786618 ≤ (radiusSixDirectedPairs (obliqueBlocks m)).card := by
  calc
    m * 16786618 = Fintype.card (ShellSixBlockIncidence m) :=
      (shellSixBlockIncidence_card m).symm
    _ ≤ Fintype.card (RadiusSixPairType (obliqueBlocks m)) :=
      Fintype.card_le_of_embedding (shellSixBlockIncidenceToDirected m)
    _ = (radiusSixDirectedPairs (obliqueBlocks m)).card :=
      RadiusSixPairType_card_eq (obliqueBlocks m)

/-- Every nonempty collection of blocks violates the directed normalized
triangular bound at shell radius six. -/
theorem obliqueBlocks_global_normalized_excess (m : ℕ) (hm : 0 < m) :
    126 * Fintype.card (Fin m × (Fin 365 × Fin 365)) <
      (radiusSixDirectedPairs (obliqueBlocks m)).card := by
  have hlower := obliqueBlocks_directed_card_ge m
  calc
    126 * Fintype.card (Fin m × (Fin 365 × Fin 365)) =
        m * 16786350 := by
      simp only [Fintype.card_prod, Fintype.card_fin]
      ring
    _ < m * 16786618 :=
      Nat.mul_lt_mul_of_pos_left (by norm_num) hm
    _ ≤ (radiusSixDirectedPairs (obliqueBlocks m)).card := hlower

/-- The direct unordered count in `m` blocks is at least `m·8,393,309`. -/
theorem obliqueBlocks_ordered_card_ge (m : ℕ) :
    m * 8393309 ≤ (radiusSixOrderedPairs (obliqueBlocks m)).card := by
  have hlower := obliqueBlocks_directed_card_ge m
  have hdouble := radiusSixDirected_card_eq_twice_ordered (obliqueBlocks m)
  rw [hdouble] at hlower
  have htwice :
      2 * (m * 8393309) ≤
        2 * (radiusSixOrderedPairs (obliqueBlocks m)).card := by
    convert hlower using 1 <;> ring
  exact Nat.le_of_mul_le_mul_left htwice (by norm_num)

/-- Every nonempty collection of blocks also violates the direct unordered
bound `E₆ ≤ 63n`. -/
theorem obliqueBlocks_unordered_normalized_excess (m : ℕ) (hm : 0 < m) :
    63 * Fintype.card (Fin m × (Fin 365 × Fin 365)) <
      (radiusSixOrderedPairs (obliqueBlocks m)).card := by
  have hlower := obliqueBlocks_ordered_card_ge m
  calc
    63 * Fintype.card (Fin m × (Fin 365 × Fin 365)) =
        m * 8393175 := by
      simp only [Fintype.card_prod, Fintype.card_fin]
      ring
    _ < m * 8393309 :=
      Nat.mul_lt_mul_of_pos_left (by norm_num) hm
    _ ≤ (radiusSixOrderedPairs (obliqueBlocks m)).card := hlower

/-- Source-facing arbitrary-size counterexamples: above every requested
cardinality there is a one-separated finite configuration violating both the
directed average-degree and direct unordered shell-six bounds. -/
theorem arbitrarily_large_global_shell_six_counterexamples (N : ℕ) :
    N ≤ Fintype.card (Fin (N + 1) × (Fin 365 × Fin 365)) ∧
    (∀ q s : Fin (N + 1) × (Fin 365 × Fin 365), q ≠ s →
      1 ≤ sqDist (obliqueBlocks (N + 1) q) (obliqueBlocks (N + 1) s)) ∧
    triCoordsWithinThirtySix.card = 126 ∧
    126 * Fintype.card (Fin (N + 1) × (Fin 365 × Fin 365)) <
      (radiusSixDirectedPairs (obliqueBlocks (N + 1))).card ∧
    63 * Fintype.card (Fin (N + 1) × (Fin 365 × Fin 365)) <
      (radiusSixOrderedPairs (obliqueBlocks (N + 1))).card := by
  refine ⟨?_, obliqueBlocks_oneSeparated (N + 1),
    triCoordsWithinThirtySix_card,
    obliqueBlocks_global_normalized_excess (N + 1) (by omega),
    obliqueBlocks_unordered_normalized_excess (N + 1) (by omega)⟩
  simp only [Fintype.card_prod, Fintype.card_fin]
  nlinarith

/-- One-separation written in the ordinary Euclidean-distance notation of the
source problem. -/
def OrdinaryOneSeparatedOn {α : Type*} (p : α → ℝ × ℝ) : Prop :=
  ∀ i j, i ≠ j → 1 ≤ Real.sqrt (sqDist (p i) (p j))

/-- The translated blocks are one-separated in ordinary-distance notation. -/
theorem obliqueBlocks_ordinaryOneSeparated (m : ℕ) :
    OrdinaryOneSeparatedOn (obliqueBlocks m) := by
  intro q s hqs
  rw [Real.one_le_sqrt]
  exact obliqueBlocks_oneSeparated m q s hqs

/-- Arbitrarily large counterexamples, now stated entirely with ordinary
distance at most six. -/
theorem arbitrarily_large_global_shell_six_counterexamples_ordinary (N : ℕ) :
    N ≤ Fintype.card (Fin (N + 1) × (Fin 365 × Fin 365)) ∧
    OrdinaryOneSeparatedOn (obliqueBlocks (N + 1)) ∧
    triCoordsWithinThirtySix.card = 126 ∧
    126 * Fintype.card (Fin (N + 1) × (Fin 365 × Fin 365)) <
      (radiusSixOrdinaryDirectedPairs (obliqueBlocks (N + 1))).card ∧
    63 * Fintype.card (Fin (N + 1) × (Fin 365 × Fin 365)) <
      (radiusSixOrdinaryOrderedPairs (obliqueBlocks (N + 1))).card := by
  have h := arbitrarily_large_global_shell_six_counterexamples N
  refine ⟨h.1, obliqueBlocks_ordinaryOneSeparated (N + 1), h.2.2.1, ?_, ?_⟩
  · rw [radiusSixOrdinaryDirectedPairs_eq]
    exact h.2.2.2.1
  · rw [radiusSixOrdinaryOrderedPairs_eq]
    exact h.2.2.2.2

/-- The plausible eventual directed-average shell-six claim.  The right side
uses the exact triangular value 126. -/
def EventualShellSixDirectedAverageBound : Prop :=
  ∃ N : ℕ, ∀ (α : Type) [Fintype α] [DecidableEq α],
    N ≤ Fintype.card α → ∀ p : α → ℝ × ℝ,
      OrdinaryOneSeparatedOn p →
        (radiusSixOrdinaryDirectedPairs p).card ≤ 126 * Fintype.card α

/-- The equivalent direct-unordered normalization `E₆ ≤ 63n`. -/
def EventualShellSixUnorderedBound : Prop :=
  ∃ N : ℕ, ∀ (α : Type) [Fintype α] [LinearOrder α],
    N ≤ Fintype.card α → ∀ p : α → ℝ × ℝ,
      OrdinaryOneSeparatedOn p →
        (radiusSixOrdinaryOrderedPairs p).card ≤ 63 * Fintype.card α

/-- No sufficiently-large cutoff can rescue the directed global-average
reading at the genuine triangular shell radius six. -/
theorem not_eventualShellSixDirectedAverageBound :
    ¬ EventualShellSixDirectedAverageBound := by
  rintro ⟨N, hN⟩
  have hcard : N ≤
      Fintype.card (Fin (N + 1) × (Fin 365 × Fin 365)) := by
    simp only [Fintype.card_prod, Fintype.card_fin]
    nlinarith
  have hu := hN (Fin (N + 1) × (Fin 365 × Fin 365)) hcard
    (obliqueBlocks (N + 1)) (obliqueBlocks_ordinaryOneSeparated (N + 1))
  rw [radiusSixOrdinaryDirectedPairs_eq] at hu
  have hl := obliqueBlocks_global_normalized_excess (N + 1) (by omega)
  omega

/-- No sufficiently-large cutoff can rescue the direct unordered version. -/
theorem not_eventualShellSixUnorderedBound :
    ¬ EventualShellSixUnorderedBound := by
  rintro ⟨N, hN⟩
  have hcard : N ≤
      Fintype.card (Fin (N + 1) × (Fin 365 × Fin 365)) := by
    simp only [Fintype.card_prod, Fintype.card_fin]
    nlinarith
  have hu := hN (Fin (N + 1) × (Fin 365 × Fin 365)) hcard
    (obliqueBlocks (N + 1)) (obliqueBlocks_ordinaryOneSeparated (N + 1))
  rw [radiusSixOrdinaryOrderedPairs_eq] at hu
  have hl := obliqueBlocks_unordered_normalized_excess (N + 1) (by omega)
  omega

/-- Final shell-six resolution: the comparison value is exactly 126, but both
natural global normalizations fail on arbitrarily large one-separated sets. -/
theorem triangular_shell_six_global_average_reading_false :
    triCoordsWithinThirtySix.card = 126 ∧
      ¬ EventualShellSixDirectedAverageBound ∧
      ¬ EventualShellSixUnorderedBound :=
  ⟨triCoordsWithinThirtySix_card,
    not_eventualShellSixDirectedAverageBound,
    not_eventualShellSixUnorderedBound⟩

end Research
