/-
Aggregate module for Erdős problem 154: imports every
submodule so `lake build ErdosProblems.Erdos154.All` builds the whole problem.
Generated by scripts/gen_aggregates.py — do not edit by hand.
-/
import ErdosProblems.Erdos154
import ErdosProblems.Erdos154.Sumset
