/-
Aggregate for ErdosProblems.Erdos154: imports the whole subtree so `lake build ErdosProblems.Erdos154.All` builds it.
Generated by scripts/gen_aggregates.py — do not edit by hand.
-/
import ErdosProblems.Erdos154.Sumset
