#!/usr/bin/env python3
"""Generate Lean Farey certificates for the 10^1000 odd band."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
GENERATOR = REPO_ROOT / "compute" / "erdos686_thue_gen_lean.py"
IMPORTS = {
    5: "ErdosProblems.Erdos686FiveThue",
    7: "ErdosProblems.Erdos686SevenThue",
    9: "ErdosProblems.Erdos686NineThue",
    11: "ErdosProblems.Erdos686ElevenThue",
    13: "ErdosProblems.Erdos686ThirteenThue",
    15: "ErdosProblems.Erdos686FifteenThue",
}


def main() -> None:
    fragments: list[str] = []
    for k, module in IMPORTS.items():
        subprocess.run(
            [sys.executable, str(GENERATOR), "1000", str(k)],
            cwd=REPO_ROOT,
            check=True,
        )
        path = (
            REPO_ROOT
            / "compute"
            / "artifacts"
            / f"erdos686_k{k}_farey_cert_e1000.lean"
        )
        fragment = path.read_text()
        if not fragment.startswith("/- AUTOGENERATED"):
            raise AssertionError(f"unexpected generated fragment for k={k}")
        fragments.append(fragment)

    imports = "".join(f"import {module}\n" for module in IMPORTS.values())
    combined = (
        "/- This file is generated by\n"
        "   compute/campaign686/agent_cf_tail/generate_e1000_certificates.py. -/\n"
        + imports
        + "\nnamespace Erdos686.Erdos686Variant.CFTail1000\n\n"
        + "\n".join(fragments)
        + "\nend Erdos686.Erdos686Variant.CFTail1000\n"
    )
    output = REPO_ROOT / "ErdosProblems" / "Erdos686CFTailBandCert.lean"
    output.write_text(combined)


if __name__ == "__main__":
    main()
