#!/usr/bin/env python3
"""Cell-based exact cover search (RAM-free, any N).
Cells = cosets of sublattices of Z^2, kept as (A, b): lattice = A Z^2 (HNF
2x2), coset rep b. Tile (u,v,n,c): {x: u x1 + v x2 == c mod n}.
Intersect cell with tile-complement: compute phi on the cell's affine
parametrization: phi(b + A t) = phi(b) + (uA11+vA21) t1 + (uA12+vA22) t2
mod n — a linear form psi on t in Z^2. Cell splits along psi's level sets:
index d = n / gcd(n, g1, g2) pieces... we split into the standard n/gcd
classes of psi mod n. Remove classes == c. DFS over tile order + shifts
with best-first heuristic (most-constrained cell)."""
import json, sys, math
from sympy import primitive_root, discrete_log
sys.setrecursionlimit(100000)

N = int(sys.argv[1]) if len(sys.argv) > 1 else 5040
fam = {int(p): n for p, n in json.load(open(f"harvest_N{N}.json")).items()}
tiles = []
for p, n in sorted(fam.items(), key=lambda kv: kv[1]):
    g0 = primitive_root(p); g = pow(g0, (p-1)//n, p)
    u = discrete_log(p, 2, g) % n; v = discrete_log(p, 3, g) % n
    tiles.append((p, u, v, n))

# cell = (a11,a12,a21,a22, b1,b2) lattice cols A1=(a11,a21), A2=(a12,a22), rep b
START = (1,0,0,1,0,0)
def cell_index(cell):  # area = |det A|
    return abs(cell[0]*cell[3] - cell[1]*cell[2])

def split(cell, u, v, n, c):
    """return list of subcells of `cell` NOT covered by tile (u,v,n,c)."""
    a11,a12,a21,a22,b1,b2 = cell
    g1 = (u*a11 + v*a21) % n
    g2 = (u*a12 + v*a22) % n
    phib = (u*b1 + v*b2) % n
    g = math.gcd(math.gcd(g1, g2), n)
    # psi(t) = phib + g1 t1 + g2 t2 takes values phib + g*Z mod n
    if (c - phib) % g != 0:
        return [cell]          # tile misses cell entirely
    d = n // g                 # cell splits into d slabs along psi
    # find e1,e2 with g1 e1 + g2 e2 == g mod n (Bezout in Z/n)
    # solve via extended gcd over integers on (g1, g2, n)
    def egcd(a,b):
        if b==0: return (a,1,0)
        g_,x,y = egcd(b, a%b); return (g_, y, x - (a//b)*y)
    # combine g1,g2: first gcd(g1,n): 
    G1, x1, _ = egcd(g1, n); 
    # find e1,e2: try e2=0: need g1 e1 == g mod n: solvable iff gcd(g1,n)|g
    sols = None
    for e2 in range(0, min(n, 64)):
        rhs = (g - g2*e2) % n
        gg = math.gcd(g1, n)
        if gg and rhs % gg == 0:
            # e1 = rhs/g1 mod n/gg via inverse
            inv = pow(g1//gg, -1, n//gg) if n//gg > 1 else 0
            e1 = (rhs//gg * inv) % (n//gg) if n//gg > 1 else 0
            if (g1*e1 + g2*e2 - g) % n == 0: sols = (e1, e2); break
    if sols is None: return [cell]  # shouldn't happen; be safe
    e1, e2 = sols
    # kernel lattice of psi on t: {t: g1 t1 + g2 t2 == 0 mod n}, index d in Z^2
    # basis: f = (n//math.gcd(g1,n), 0)-ish — use general: kernel contains
    # (g2/g', -g1/g') where g' = gcd(g1,g2) and (n/gcd(g1,n), 0)... 
    # Simpler: kernel = {t : psi0(t)==0 mod d} where psi0 = (g1/g) t1 + (g2/g) t2,
    # gcd(psi0 coeffs, d) = 1. Kernel basis: (h2, -h1) and (x, y) with
    # h1 x + h2 y == d ... where h1=g1//g, h2=g2//g mod d, gcd(h1,h2,d)=1
    h1, h2 = (g1//g) % d, (g2//g) % d
    # find (x,y): h1 x + h2 y == 1 mod d  (exists since gcd(h1,h2,d)=1)
    xy = None
    for y in range(min(d, 4096)):
        rhs = (1 - h2*y) % d
        gg = math.gcd(h1, d)
        if gg == 0:
            if rhs % d == 0: xy = (0, y); break
            continue
        if rhs % gg == 0:
            x = (rhs//gg * pow(h1//gg, -1, d//gg)) % (d//gg) if d//gg>1 else 0
            if (h1*x + h2*y) % d == 1 % d: xy = (x, y); break
    if xy is None: return [cell]
    x, y = xy
    # kernel of psi0 mod d on Z^2: generated by w1=(h2,-h1)... need index-d sublattice:
    # K = {t: h1 t1 + h2 t2 == 0 mod d}: basis w1 = (h2, -h1) + correction, w2 = d*(x,y)... 
    # standard: K generated by (d*x_, d*y_)? Use: w2 = (d - h2* ? ...). Take
    # w1 = (h2, -h1) (psi0 = 0), w2 = (x*d - ?, ...) -- use w2 = (x, y)*0 + (d,0) if h1|.. 
    # General valid pair: w1 = (h2, -h1), w2 = (x*d, y*d)?? det = h2*y*d + h1*x*d = d*(h1x+h2y) = d (mod d^2)...
    w1 = (h2, -h1)
    w2 = (x*d - x*0, y*d) if False else None
    # take w2 = d*(x, y): psi0(w2) = d*(h1x+h2y) = d*1 == 0 mod d ✓
    w2 = (d*x, d*y)
    det = w1[0]*w2[1] - w1[1]*w2[0]
    if det == 0:
        w2 = (d, 0) if (h1*d) % d == 0 and h1 % d != 0 or True else w2
        # fallback: w2=(d,0): psi0 = h1*d == 0 mod d ✓
        w2 = (d, 0)
        det = w1[0]*w2[1] - w1[1]*w2[0]
        if det == 0:
            w1 = (0, d); w2 = (d, 0); det = -d*d  # ultra fallback (index d^2 — suboptimal but correct)
    # children: coset reps t0 = j*(x,y) for j = 0..d-1 (psi0 = j)
    out = []
    for j in range(d):
        if (phib + j*g) % n == c: continue      # covered slab — drop
        t0 = (j*x % (d*abs(det)) , j*y)
        # new cell lattice cols: A * w1, A * w2 ; rep: b + A t0
        na11 = a11*w1[0] + a12*w1[1]; na21 = a21*w1[0] + a22*w1[1]
        na12 = a11*w2[0] + a12*w2[1]; na22 = a21*w2[0] + a22*w2[1]
        nb1 = b1 + a11*t0[0] + a12*t0[1]; nb2 = b2 + a21*t0[0] + a22*t0[1]
        out.append((na11,na12,na21,na22,nb1,nb2))
    return out

# quick self-test: p=5 tile (1,3,4) at c=0 should split START into 3 cells of index 4
test = split(START, 1, 3, 4, 0)
tot = sum(1/cell_index(c) for c in test)
print(f"selftest: START minus (k+3l==0 mod 4) -> {len(test)} cells, total density {tot:.4f} (want 0.75)")
