#!/usr/bin/env python3
"""Clean cell/tile lattice engine for Erdos #203, with exact kernel bases.
Cell = (a11,a12,a21,a22,b1,b2): lattice cols A1=(a11,a21), A2=(a12,a22), rep b.
Tile (u,v,n,c): {x : u x1 + v x2 == c mod n}."""
import math
from functools import reduce

def idx(cell):
    return abs(cell[0]*cell[3] - cell[1]*cell[2])

def _hnf2(gens):
    """HNF-ish basis (w1, w2) of the lattice generated by 2-vectors gens."""
    vs = [tuple(v) for v in gens if v != (0, 0)]
    while True:
        nz = sorted((v for v in vs if v[0] != 0), key=lambda v: abs(v[0]))
        if len(nz) <= 1: break
        a = nz[0]; out = []
        for v in vs:
            if v == a or v[0] == 0: out.append(v); continue
            q = v[0] // a[0]
            out.append((v[0] - q*a[0], v[1] - q*a[1]))
        vs = [v for v in out if v != (0, 0)]
    w1 = next((v for v in vs if v[0] != 0), None)
    seconds = [abs(v[1]) for v in vs if v[0] == 0 and v[1] != 0]
    g2 = reduce(math.gcd, seconds) if seconds else 0
    if w1 is None: return ((0, g2) if g2 else None), None
    if g2: w1 = (w1[0], w1[1] % g2)
    return w1, (0, g2) if g2 else None

def split(cell, u, v, n, c):
    """Subcells of `cell` NOT covered by tile: None if tile misses cell,
    [] if tile swallows cell, else list of children (exact partition)."""
    a11,a12,a21,a22,b1,b2 = cell
    g1 = (u*a11 + v*a21) % n
    g2 = (u*a12 + v*a22) % n
    phib = (u*b1 + v*b2) % n
    g = math.gcd(math.gcd(g1, g2), n)
    if (c - phib) % g != 0: return None
    d = n // g
    if d == 1: return []
    h1, h2 = (g1 // g) % d, (g2 // g) % d           # gcd(h1,h2,d)=1
    # kernel K = d Z^2 + Z (h2, -h1); basis by HNF; |det| must equal d
    w1, w2 = _hnf2([(d, 0), (0, d), (h2 % d, (-h1) % d)])
    det = abs(w1[0]*w2[1] - w1[1]*w2[0])
    assert det == d, (cell, u, v, n, c, w1, w2, det)
    # coset reps: t0 with psi0(t0) == 1 mod d, reps j*t0
    t0 = None
    G = math.gcd(h1, d)
    for yy in range(d):
        r = (1 - h2*yy) % d
        if G and r % G == 0:
            xx = ((r // G) * pow(h1 // G, -1, d // G)) % (d // G) if d // G > 1 else 0
            if (h1*xx + h2*yy) % d == 1 % d: t0 = (xx, yy); break
        elif G == 0 and r == 0: t0 = (0, yy); break
    assert t0 is not None
    jstar = ((c - phib) // g) % d
    out = []
    for j in range(d):
        if j == jstar: continue
        tx, ty = j*t0[0], j*t0[1]
        out.append((a11*w1[0] + a12*w1[1], a11*w2[0] + a12*w2[1],
                    a21*w1[0] + a22*w1[1], a21*w2[0] + a22*w2[1],
                    b1 + a11*tx + a12*ty, b2 + a21*tx + a22*ty))
    return out

def members(cell, B):
    """all points of cell in [0,B)^2 — exact: (x,y) in cell iff
    A^{-1}((x,y)-b) is integral."""
    a11,a12,a21,a22,b1,b2 = cell
    det = a11*a22 - a12*a21
    pts = set()
    for x in range(B):
        for y in range(B):
            rx, ry = x - b1, y - b2
            s_num = a22*rx - a12*ry
            t_num = -a21*rx + a11*ry
            if s_num % det == 0 and t_num % det == 0: pts.add((x, y))
    return pts

if __name__ == '__main__':
    import random
    rng = random.Random(7)
    fails = 0
    for trial in range(300):
        n = rng.choice([4, 6, 8, 9, 10, 12])
        while True:
            u, v = rng.randrange(n), rng.randrange(n)
            if math.gcd(math.gcd(u, v), n) == 1: break
        c = rng.randrange(n)
        # random cell with modest entries
        while True:
            cell = (rng.randrange(1, 5), rng.randrange(0, 4),
                    rng.randrange(0, 4), rng.randrange(1, 5),
                    rng.randrange(6), rng.randrange(6))
            if idx(cell) != 0: break
        B = 2 * n * 5
        want = {p for p in members(cell, B) if (u*p[0] + v*p[1]) % n != c}
        r = split(cell, u, v, n, c)
        got = set()
        if r is None: got = members(cell, B)
        else:
            for ch in r: got |= members(ch, B)
        if got != want:
            fails += 1
            if fails <= 3: print("FAIL", cell, (u, v, n, c), len(got), len(want))
    print(f"brute-force cross-check: {300 - fails}/300 exact matches")
