/- leanprover/lean4:v4.29.1  mathlib v4.29.1 -/
import ErdosProblems.Erdos686K5ProperGlobalIntersection

/-!
# Erdős 686, k=5: exact bipartite tangent cancellation

The product of the four tangent defects on a `2 x 2` crossing grid lies in
the integer ideal generated by the two-row product and the two-column
product.  This is the exact polynomial cancellation behind the finite
index-tuple resultant calculation; it is proved here uniformly, without an
enumeration or a trusted external algebra system.

After the four-crossing owner square is cancelled, the remaining row and
column cofactors are coprime and satisfy one explicit first-power owner
congruence.  Thus the square-level condition is not left as another raw
height bound.
-/

namespace Erdos686
namespace Erdos686Variant

open scoped BigOperators

/-- External multiplier removed from the distinguished upper term. -/
def k5UpperFourMultiplier (t i : ℕ) : ℕ :=
  if i = t then 4 else 1

lemma k5UpperFourMultiplier_mul_upperTermAfterFour
    {n d t i : ℕ} (hfour : 4 ∣ n + d + t) :
    k5UpperFourMultiplier t i * upperTermAfterFour n d t i = n + d + i := by
  by_cases hit : i = t
  · subst i
    simp only [k5UpperFourMultiplier, upperTermAfterFour, if_pos]
    exact Nat.mul_div_cancel' hfour
  · simp [k5UpperFourMultiplier, upperTermAfterFour, hit]

/-- Row coefficient in the uncancelled tangent defect. -/
def k5LowerTangentWeight (j : ℕ) : ℤ :=
  4 * localBlockCoefficient 5 j

/-- Column coefficient after expressing the original upper term through its
distinguished-factor-four modification. -/
def k5ModifiedUpperTangentWeight (t i : ℕ) : ℤ :=
  localBlockCoefficient 5 i * (k5UpperFourMultiplier t i : ℤ)

lemma k5OwnerSquareDefect_eq_modified_bipartite
    {n d t j i : ℕ} (hfour : 4 ∣ n + d + t) :
    k5OwnerSquareDefect n d j i =
      k5ModifiedUpperTangentWeight t i *
          (upperTermAfterFour n d t i : ℤ) -
        k5LowerTangentWeight j * (n + j : ℤ) := by
  have hmul := k5UpperFourMultiplier_mul_upperTermAfterFour
    (n := n) (d := d) (t := t) (i := i) hfour
  have hmulZ :
      (k5UpperFourMultiplier t i : ℤ) *
          (upperTermAfterFour n d t i : ℤ) = (n + d + i : ℕ) := by
    exact_mod_cast hmul
  unfold k5OwnerSquareDefect k5ModifiedUpperTangentWeight
    k5LowerTangentWeight
  rw [← hmulZ]
  push_cast
  ring

/-- Row-ideal quotient in the universal `K_{2,2}` tangent identity. -/
def bipartiteTangentRowQuotient
    (x₁ x₂ y₁ y₂ p₁ p₂ q₁ q₂ : ℤ) : ℤ :=
  p₁ * p₂ * (p₁ * x₁ - q₁ * y₁ - q₂ * y₂) *
    (p₂ * x₂ - q₁ * y₁ - q₂ * y₂)

/-- Column-ideal quotient in the universal `K_{2,2}` tangent identity. -/
def bipartiteTangentColumnQuotient
    (x₁ x₂ y₁ y₂ p₁ p₂ q₁ q₂ : ℤ) : ℤ :=
  q₁ * q₂ *
    (p₁ ^ 2 * x₁ ^ 2 - p₁ * q₁ * x₁ * y₁ -
      p₁ * q₂ * x₁ * y₂ + p₂ ^ 2 * x₂ ^ 2 -
      p₂ * q₁ * x₂ * y₁ - p₂ * q₂ * x₂ * y₂ +
      q₁ * q₂ * y₁ * y₂)

/-- Exact polynomial ideal certificate.  Each monomial in the four-edge
product chooses a vertex cover of `K_{2,2}`, hence contains either both row
variables or both column variables.  The displayed identity is the expanded
ordinary-kernel certificate of that combinatorial fact. -/
theorem bipartite_tangent_product_ideal_identity
    (x₁ x₂ y₁ y₂ p₁ p₂ q₁ q₂ : ℤ) :
    (q₁ * y₁ - p₁ * x₁) * (q₂ * y₂ - p₁ * x₁) *
        (q₁ * y₁ - p₂ * x₂) * (q₂ * y₂ - p₂ * x₂) =
      (x₁ * x₂) *
          bipartiteTangentRowQuotient x₁ x₂ y₁ y₂ p₁ p₂ q₁ q₂ +
        (y₁ * y₂) *
          bipartiteTangentColumnQuotient x₁ x₂ y₁ y₂ p₁ p₂ q₁ q₂ := by
  unfold bipartiteTangentRowQuotient bipartiteTangentColumnQuotient
  ring

/-- The specialized row quotient for two proper-global rows and columns. -/
def k5ProperTangentRowQuotient
    (n d t j₁ j₂ i₁ i₂ : ℕ) : ℤ :=
  bipartiteTangentRowQuotient
    (n + j₁) (n + j₂)
    (upperTermAfterFour n d t i₁) (upperTermAfterFour n d t i₂)
    (k5LowerTangentWeight j₁) (k5LowerTangentWeight j₂)
    (k5ModifiedUpperTangentWeight t i₁)
    (k5ModifiedUpperTangentWeight t i₂)

/-- The specialized column quotient for two proper-global rows and columns. -/
def k5ProperTangentColumnQuotient
    (n d t j₁ j₂ i₁ i₂ : ℕ) : ℤ :=
  bipartiteTangentColumnQuotient
    (n + j₁) (n + j₂)
    (upperTermAfterFour n d t i₁) (upperTermAfterFour n d t i₂)
    (k5LowerTangentWeight j₁) (k5LowerTangentWeight j₂)
    (k5ModifiedUpperTangentWeight t i₁)
    (k5ModifiedUpperTangentWeight t i₂)

theorem k5_four_tangent_defects_ideal_identity
    {n d t j₁ j₂ i₁ i₂ : ℕ} (hfour : 4 ∣ n + d + t) :
    k5OwnerSquareDefect n d j₁ i₁ *
        k5OwnerSquareDefect n d j₁ i₂ *
        k5OwnerSquareDefect n d j₂ i₁ *
        k5OwnerSquareDefect n d j₂ i₂ =
      (((n + j₁) * (n + j₂) : ℕ) : ℤ) *
          k5ProperTangentRowQuotient n d t j₁ j₂ i₁ i₂ +
        ((upperTermAfterFour n d t i₁ *
            upperTermAfterFour n d t i₂ : ℕ) : ℤ) *
          k5ProperTangentColumnQuotient n d t j₁ j₂ i₁ i₂ := by
  rw [k5OwnerSquareDefect_eq_modified_bipartite hfour,
    k5OwnerSquareDefect_eq_modified_bipartite hfour,
    k5OwnerSquareDefect_eq_modified_bipartite hfour,
    k5OwnerSquareDefect_eq_modified_bipartite hfour]
  exact bipartite_tangent_product_ideal_identity
    (n + j₁) (n + j₂)
    (upperTermAfterFour n d t i₁) (upperTermAfterFour n d t i₂)
    (k5LowerTangentWeight j₁) (k5LowerTangentWeight j₂)
    (k5ModifiedUpperTangentWeight t i₁)
    (k5ModifiedUpperTangentWeight t i₂)

/-- Exact first-power congruence after cancelling the four-crossing owner
from the tangent square.  The two displayed natural cofactors are coprime.
This is the finite-index polynomial cancellation interface for the next CRT
or resultant step. -/
theorem k5_proper_global_crossing_dvd_coprime_cofactor_tangent_combination
    {n d t j₁ j₂ i₁ i₂ : ℕ}
    (data : CanonicalOwnerData 5 n d t)
    (hj₁ : j₁ ∈ Finset.Icc 1 5) (hj₂ : j₂ ∈ Finset.Icc 1 5)
    (hi₁ : i₁ ∈ Finset.Icc 1 5) (hi₂ : i₂ ∈ Finset.Icc 1 5)
    (hjneq : j₁ ≠ j₂) (hineq : i₁ ≠ i₂)
    (hfour : 4 ∣ n + d + t)
    (hj₁one : canonicalLowerResidual data j₁ = 1)
    (hj₂one : canonicalLowerResidual data j₂ = 1)
    (hi₁one : canonicalUpperResidual data i₁ = 1)
    (hi₂one : canonicalUpperResidual data i₂ = 1)
    (heq : blockProduct 5 (n + d) = 4 * blockProduct 5 n) :
    let A := (n + j₁) * (n + j₂)
    let B := upperTermAfterFour n d t i₁ * upperTermAfterFour n d t i₂
    let X := canonicalOwnerCell data j₁ i₁ *
      canonicalOwnerCell data j₁ i₂ *
      canonicalOwnerCell data j₂ i₁ *
      canonicalOwnerCell data j₂ i₂
    Nat.Coprime (A / X) (B / X) ∧
      ((X : ℕ) : ℤ) ∣
        k5ProperTangentRowQuotient n d t j₁ j₂ i₁ i₂ * (A / X : ℕ) +
          k5ProperTangentColumnQuotient n d t j₁ j₂ i₁ i₂ * (B / X : ℕ) := by
  dsimp only
  let A : ℕ := (n + j₁) * (n + j₂)
  let B : ℕ := upperTermAfterFour n d t i₁ * upperTermAfterFour n d t i₂
  let X : ℕ := canonicalOwnerCell data j₁ i₁ *
    canonicalOwnerCell data j₁ i₂ *
    canonicalOwnerCell data j₂ i₁ *
    canonicalOwnerCell data j₂ i₂
  let U : ℤ := k5ProperTangentRowQuotient n d t j₁ j₂ i₁ i₂
  let V : ℤ := k5ProperTangentColumnQuotient n d t j₁ j₂ i₁ i₂
  let a : ℕ := A / X
  let b : ℕ := B / X
  let F : ℤ := k5OwnerSquareDefect n d j₁ i₁ *
    k5OwnerSquareDefect n d j₁ i₂ *
    k5OwnerSquareDefect n d j₂ i₁ *
    k5OwnerSquareDefect n d j₂ i₂
  have hgcd : Nat.gcd A B = X := by
    dsimp [A, B, X]
    exact k5_proper_global_row_column_gcd_eq_crossings data
      hj₁ hj₂ hi₁ hi₂ hjneq hineq
        hj₁one hj₂one hi₁one hi₂one
  have hXpos : 0 < X := by
    dsimp [X]
    have h₁₁ := canonicalOwnerCell_pos data (j := j₁) (i := i₁)
    have h₁₂ := canonicalOwnerCell_pos data (j := j₁) (i := i₂)
    have h₂₁ := canonicalOwnerCell_pos data (j := j₂) (i := i₁)
    have h₂₂ := canonicalOwnerCell_pos data (j := j₂) (i := i₂)
    positivity
  have hcop : Nat.Coprime (A / X) (B / X) := by
    rw [← hgcd]
    exact Nat.coprime_div_gcd_div_gcd (by simpa [hgcd] using hXpos)
  have hA : X ∣ A := by rw [← hgcd]; exact Nat.gcd_dvd_left A B
  have hB : X ∣ B := by rw [← hgcd]; exact Nat.gcd_dvd_right A B
  have hAeq : X * (A / X) = A := Nat.mul_div_cancel' hA
  have hBeq : X * (B / X) = B := Nat.mul_div_cancel' hB
  have hAcast : (A : ℤ) = (X : ℤ) * (a : ℤ) := by
    dsimp [a]
    exact_mod_cast hAeq.symm
  have hBcast : (B : ℤ) = (X : ℤ) * (b : ℤ) := by
    dsimp [b]
    exact_mod_cast hBeq.symm
  have hFidentity : F = (A : ℤ) * U + (B : ℤ) * V := by
    dsimp [F, A, B, U, V]
    exact k5_four_tangent_defects_ideal_identity hfour
  have hFfactor : F = (X : ℤ) * (U * (a : ℤ) + V * (b : ℤ)) := by
    rw [hFidentity, hAcast, hBcast]
    ring
  have hsq : (X : ℤ) ^ 2 ∣ F := by
    dsimp [X, F]
    exact k5_crossing_product_sq_dvd_four_tangent_defects
      data hj₁ hj₂ hi₁ hi₂ hfour heq
  have hcancel : (X : ℤ) ∣
      U * (a : ℤ) + V * (b : ℤ) := by
    have hmul : (X : ℤ) * (X : ℤ) ∣
        (X : ℤ) * (U * (a : ℤ) + V * (b : ℤ)) := by
      simpa [pow_two, hFfactor] using hsq
    exact (mul_dvd_mul_iff_left (by exact_mod_cast hXpos.ne')).mp hmul
  exact ⟨hcop, by simpa [A, B, X, U, V, a, b] using hcancel⟩

#print axioms bipartite_tangent_product_ideal_identity
#print axioms k5_four_tangent_defects_ideal_identity
#print axioms k5_proper_global_crossing_dvd_coprime_cofactor_tangent_combination

end Erdos686Variant
end Erdos686
