#!/usr/bin/env python3
"""Regenerate the per-problem aggregate modules and the library root.

Each Erdős problem N with more than a bare root file gets
``ErdosProblems/ErdosN/All.lean`` importing every one of its submodules, so
``lake build ErdosProblems.ErdosN.All`` builds that problem alone (this is what
the CI matrix targets).  ``ErdosProblems.lean`` imports one entry per problem.

Run after adding or moving Lean files under ``ErdosProblems/``:

    python3 scripts/gen_aggregates.py

Idempotent; commit whatever it changes.
"""
from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ROOT = REPO / "ErdosProblems"
DO_NOT_EDIT = "-- Generated by scripts/gen_aggregates.py — do not edit by hand.\n"


def problem_of(module_parts: tuple[str, ...]) -> str | None:
    # ("ErdosProblems", "Erdos686", "EvenK", ...) -> "686"
    if len(module_parts) < 2:
        return None
    m = re.match(r"^Erdos(\d+)$", module_parts[1])
    return m.group(1) if m else None


def main() -> None:
    modules: dict[str, list[str]] = defaultdict(list)
    has_bare: dict[str, bool] = defaultdict(bool)

    for p in ROOT.rglob("*.lean"):
        parts = p.relative_to(REPO).with_suffix("").parts
        if parts[-1] == "All":
            continue  # never import an aggregate into another
        num = problem_of(parts)
        if num is None:
            continue
        mod = ".".join(parts)
        modules[num].append(mod)
        if mod == f"ErdosProblems.Erdos{num}":
            has_bare[num] = True

    entries: dict[str, str] = {}
    for num in sorted(modules, key=int):
        mods = sorted(set(modules[num]))
        sub = [m for m in mods if m != f"ErdosProblems.Erdos{num}"]
        if not sub:
            entries[num] = f"ErdosProblems.Erdos{num}"
            continue
        agg_mod = f"ErdosProblems.Erdos{num}.All"
        entries[num] = agg_mod
        header = (f"/-\nAggregate module for Erdős problem {num}: imports every\n"
                  f"submodule so `lake build {agg_mod}` builds the whole problem.\n"
                  f"Generated by scripts/gen_aggregates.py — do not edit by hand.\n-/\n")
        body = header + "".join(f"import {m}\n" for m in mods)
        agg = ROOT / f"Erdos{num}" / "All.lean"
        agg.parent.mkdir(parents=True, exist_ok=True)
        agg.write_text(body)

    master = ("-- Library root: import every problem's aggregate so `lake build`\n"
              "-- builds the whole library.  One entry per Erdős problem.\n"
              + DO_NOT_EDIT)
    master += "".join(f"import {entries[num]}\n" for num in sorted(modules, key=int))
    (REPO / "ErdosProblems.lean").write_text(master)

    print(f"wrote {sum(1 for e in entries.values() if e.endswith('.All'))} aggregates "
          f"and the library root over {len(entries)} problems")


if __name__ == "__main__":
    main()
