#!/usr/bin/env python3
"""Regenerate the aggregate modules, the library root, and the CI target list.

Every directory under ``ErdosProblems/`` that holds Lean modules gets an
``All.lean`` importing its direct files and each child directory's ``All``, so
``lake build <dir>.All`` builds exactly that subtree.  A directory that both
holds files directly and has child directories (and is large enough that CI
wants to split it) also gets a ``Loose.lean`` importing just its direct files,
so the split can cover those files without rebuilding the children.

``ErdosProblems.lean`` imports one entry per problem.  ``scripts/build-targets.json``
lists the modules the CI matrix builds: a covering set of aggregates, none
larger than ``CAP`` modules unless a leaf directory is itself that big.

Run after adding or moving Lean files under ``ErdosProblems/``:

    python3 scripts/gen_aggregates.py

Idempotent; commit whatever it changes.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ROOT = REPO / "ErdosProblems"
CAP = 800  # soft cap on modules per CI job; leaf dirs larger than this stay whole
GEN = "Generated by scripts/gen_aggregates.py — do not edit by hand."


def module_of(path: Path) -> str:
    return ".".join(path.relative_to(REPO).with_suffix("").parts)


def direct_modules(d: Path) -> list[str]:
    """Modules for the .lean files sitting directly in `d` (not All/Loose)."""
    return sorted(module_of(p) for p in d.glob("*.lean")
                  if p.stem not in ("All", "Loose"))


def child_dirs(d: Path) -> list[Path]:
    return sorted(c for c in d.iterdir()
                  if c.is_dir() and any(c.rglob("*.lean")))


def subtree_count(d: Path) -> int:
    return sum(1 for p in d.rglob("*.lean") if p.stem not in ("All", "Loose"))


def problem_of(d: Path) -> str | None:
    parts = d.relative_to(ROOT).parts
    if not parts:
        return None
    m = re.match(r"^Erdos(\d+)$", parts[0])
    return m.group(1) if m else None


def write_aggregates(d: Path) -> None:
    """Post-order: write All.lean (and Loose.lean where a split needs it)."""
    kids = child_dirs(d)
    for c in kids:
        write_aggregates(c)

    local = direct_modules(d)
    child_all = [f"{module_of(c)}.All" for c in kids]
    banner = (f"/-\nAggregate for {module_of(d)}: imports the whole subtree so "
              f"`lake build {module_of(d)}.All` builds it.\n{GEN}\n-/\n")
    (d / "All.lean").write_text(banner + "".join(
        f"import {m}\n" for m in local + child_all))

    if local and kids and subtree_count(d) > CAP:
        loose_banner = (f"/-\nDirect files of {module_of(d)} only (the split "
                        f"siblings build the subdirectories).\n{GEN}\n-/\n")
        (d / "Loose.lean").write_text(loose_banner + "".join(
            f"import {m}\n" for m in local))
    else:
        (d / "Loose.lean").unlink(missing_ok=True)


def cover(d: Path) -> list[str]:
    """Covering set of build targets for directory `d`."""
    kids = child_dirs(d)
    if subtree_count(d) <= CAP or not kids:
        return [f"{module_of(d)}.All"]
    targets: list[str] = []
    for c in kids:
        targets += cover(c)
    if direct_modules(d):
        targets.append(f"{module_of(d)}.Loose")
    return targets


def main() -> None:
    problem_dirs = sorted((p for p in ROOT.iterdir()
                           if p.is_dir() and re.match(r"^Erdos\d+$", p.name)),
                          key=lambda p: int(p.name[len("Erdos"):]))
    bare_roots = {p.stem for p in ROOT.glob("Erdos*.lean")}

    master_entries: list[str] = []
    targets: list[str] = []
    seen_problems: set[str] = set()

    for d in problem_dirs:
        write_aggregates(d)
        num = d.name[len("Erdos"):]
        seen_problems.add(num)
        # library root imports the bare root (if any) and the top aggregate
        if d.name in bare_roots:
            master_entries.append(f"ErdosProblems.{d.name}")
            targets.append(f"ErdosProblems.{d.name}")
        master_entries.append(f"{module_of(d)}.All")
        targets += cover(d)

    # problems that are a single bare file with no directory (617, 727)
    for stem in sorted(bare_roots, key=lambda s: int(s[len("Erdos"):])):
        num = stem[len("Erdos"):]
        if num in seen_problems:
            continue
        master_entries.append(f"ErdosProblems.{stem}")
        targets.append(f"ErdosProblems.{stem}")

    master = ("-- Library root: build the whole library.  One entry per problem.\n"
              f"-- {GEN}\n" + "".join(f"import {m}\n" for m in master_entries))
    (REPO / "ErdosProblems.lean").write_text(master)

    (REPO / "scripts" / "build-targets.json").write_text(
        json.dumps(sorted(set(targets)), indent=2) + "\n")

    print(f"aggregates written; {len(set(targets))} CI targets "
          f"over {len(problem_dirs)} problem directories")


if __name__ == "__main__":
    main()
