import Research.Definitions

namespace Erdos123

/-- Numbers generated by two bases. -/
def Smooth2 (p q : ℕ) : Set ℕ :=
  {x | ∃ i j : ℕ, x = p ^ i * q ^ j}

/-- Primitive representability of one target integer. -/
def PrimRep (A : Set ℕ) (n : ℕ) : Prop :=
  ∃ t : Finset ℕ, (∀ x ∈ t, x ∈ A) ∧ IsPrimitive t ∧ t.sum id = n

private lemma smooth2_eq_qpow_of_not_dvd {p q x : ℕ}
    (hx : x ∈ Smooth2 p q) (hpx : ¬p ∣ x) : ∃ j : ℕ, x = q ^ j := by
  rcases hx with ⟨i, j, rfl⟩
  by_cases hi : i = 0
  · subst i
    exact ⟨j, by simp⟩
  · exfalso
    apply hpx
    obtain ⟨i, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hi
    simp only [pow_succ]
    exact ⟨p ^ i * q ^ j, by ac_rfl⟩

private lemma smooth2_div_left_mem {p q x : ℕ}
    (hp : 1 < p) (hpq : Nat.Coprime p q)
    (hx : x ∈ Smooth2 p q) (hdiv : p ∣ x) : x / p ∈ Smooth2 p q := by
  rcases hx with ⟨i, j, rfl⟩
  have hi : i ≠ 0 := by
    intro hi
    subst i
    simp only [pow_zero, one_mul] at hdiv
    have hp_one := (hpq.pow_right j).eq_one_of_dvd hdiv
    omega
  obtain ⟨i, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hi
  refine ⟨i, j, ?_⟩
  simp [pow_succ, Nat.mul_div_left, Nat.zero_lt_of_lt hp, mul_assoc, mul_left_comm]

private lemma le_pow_self_of_two_le {p : ℕ} (hp : 2 ≤ p) :
    ∀ N : ℕ, N ≤ p ^ N := by
  intro N
  induction N with
  | zero => simp
  | succ N ih =>
      rw [pow_succ]
      have hone : 1 ≤ p ^ N := Nat.one_le_pow N p (by omega)
      nlinarith

/-- Erdős--Lewin propagation obstruction, in the left-base direction: if `s`
has no primitive representation by `p^i q^j`, then neither does `p*s`. -/
theorem not_primRep_smooth2_mul_left {p q s : ℕ}
    (hp : 1 < p) (hq : 1 < q) (hpq : Nat.Coprime p q)
    (hs : ¬PrimRep (Smooth2 p q) s) :
    ¬PrimRep (Smooth2 p q) (p * s) := by
  intro hps
  rcases hps with ⟨t, htA, htPrimitive, htSum⟩

  have hallDiv : ∀ x ∈ t, p ∣ x := by
    intro x hx
    by_contra hpx
    obtain ⟨ix, hxq⟩ := smooth2_eq_qpow_of_not_dvd (htA x hx) hpx
    have hOther : ∀ y ∈ t.erase x, p ∣ y := by
      intro y hy
      have hy_ne : y ≠ x := (Finset.mem_erase.mp hy).1
      have hy_mem : y ∈ t := (Finset.mem_erase.mp hy).2
      by_contra hpy
      obtain ⟨iy, hyq⟩ := smooth2_eq_qpow_of_not_dvd (htA y hy_mem) hpy
      rcases le_total ix iy with hxy | hyx
      · apply htPrimitive hx hy_mem hy_ne.symm
        rw [hxq, hyq]
        exact pow_dvd_pow q hxy
      · apply htPrimitive hy_mem hx hy_ne
        rw [hxq, hyq]
        exact pow_dvd_pow q hyx
    have hEraseDiv : p ∣ ∑ y ∈ t.erase x, y :=
      Finset.dvd_sum hOther
    have hTotalDiv : p ∣ ∑ y ∈ t, y := by
      have h : p ∣ t.sum id := by
        rw [htSum]
        exact ⟨s, rfl⟩
      simpa only [id_eq] using h
    have hEraseEq : (∑ y ∈ t.erase x, y) + x = ∑ y ∈ t, y := by
      simpa only [id_eq] using Finset.sum_erase_add t id hx
    have hAddDiv : p ∣ x + ∑ y ∈ t.erase x, y := by
      rw [add_comm, hEraseEq]
      exact hTotalDiv
    exact hpx ((Nat.dvd_add_iff_left hEraseDiv).mpr hAddDiv)

  let u : Finset ℕ := t.image (fun x => x / p)
  have hinj : Set.InjOn (fun x : ℕ => x / p) (t : Set ℕ) := by
    intro x hx y hy hxy
    calc
      x = p * (x / p) := (Nat.mul_div_cancel' (hallDiv x hx)).symm
      _ = p * (y / p) := congrArg (fun z => p * z) hxy
      _ = y := Nat.mul_div_cancel' (hallDiv y hy)

  apply hs
  refine ⟨u, ?_, ?_, ?_⟩
  · intro z hz
    rcases Finset.mem_image.mp hz with ⟨x, hx, rfl⟩
    exact smooth2_div_left_mem hp hpq (htA x hx) (hallDiv x hx)
  · intro z hz w hw hzw
    rcases Finset.mem_image.mp hz with ⟨x, hx, rfl⟩
    rcases Finset.mem_image.mp hw with ⟨y, hy, rfl⟩
    intro hdvd
    apply htPrimitive hx hy
    · intro hxy
      apply hzw
      simpa [hxy]
    · rw [← Nat.mul_div_cancel' (hallDiv x hx), ← Nat.mul_div_cancel' (hallDiv y hy)]
      exact Nat.mul_dvd_mul_left p hdvd
  · apply Nat.eq_of_mul_eq_mul_left (by omega : 0 < p)
    calc
      p * u.sum id = p * ∑ x ∈ t, x / p := by
        unfold u
        rw [Finset.sum_image hinj]
        simp only [id_eq]
      _ = ∑ x ∈ t, p * (x / p) := Finset.mul_sum t (fun x => x / p) p
      _ = ∑ x ∈ t, x := by
        apply Finset.sum_congr rfl
        intro x hx
        exact Nat.mul_div_cancel' (hallDiv x hx)
      _ = p * s := htSum

/-- Swapping the two bases does not change the generated set. -/
lemma smooth2_comm (p q : ℕ) : Smooth2 p q = Smooth2 q p := by
  ext x
  constructor
  · rintro ⟨i, j, rfl⟩
    exact ⟨j, i, by ac_rfl⟩
  · rintro ⟨j, i, rfl⟩
    exact ⟨i, j, by ac_rfl⟩

/-- Symmetric right-base form of the propagation obstruction. -/
theorem not_primRep_smooth2_mul_right {p q s : ℕ}
    (hp : 1 < p) (hq : 1 < q) (hpq : Nat.Coprime p q)
    (hs : ¬PrimRep (Smooth2 p q) s) :
    ¬PrimRep (Smooth2 p q) (q * s) := by
  have hs' : ¬PrimRep (Smooth2 q p) s := by
    simpa only [smooth2_comm q p] using hs
  have h := not_primRep_smooth2_mul_left hq hp hpq.symm hs'
  simpa only [smooth2_comm q p] using h

/-- A missing target propagates along every power of the left base. -/
theorem not_primRep_smooth2_pow_mul {p q s : ℕ}
    (hp : 1 < p) (hq : 1 < q) (hpq : Nat.Coprime p q)
    (hs : ¬PrimRep (Smooth2 p q) s) (i : ℕ) :
    ¬PrimRep (Smooth2 p q) (p ^ i * s) := by
  induction i with
  | zero => simpa using hs
  | succ i ih =>
      have h := not_primRep_smooth2_mul_left hp hq hpq ih
      simpa [pow_succ, mul_assoc, mul_comm, mul_left_comm] using h

/-- For a coprime two-base system, eventual d-completeness would force every
natural number (not merely every large one) to be primitively representable. -/
theorem smooth2_dComplete_iff_all_primRep {p q : ℕ}
    (hp : 1 < p) (hq : 1 < q) (hpq : Nat.Coprime p q) :
    IsDComplete (Smooth2 p q) ↔ ∀ n : ℕ, PrimRep (Smooth2 p q) n := by
  constructor
  · rintro ⟨N, hN⟩ n
    by_contra hn
    have hnpos : 0 < n := by
      by_contra hnzero
      have hn_eq : n = 0 := by omega
      apply hn
      subst n
      exact ⟨∅, by simp, by simp [IsPrimitive], by simp⟩
    have hNpow : N ≤ p ^ N := le_pow_self_of_two_le (p := p) (by omega) N
    have hlarge : N ≤ p ^ N * n :=
      hNpow.trans (Nat.le_mul_of_pos_right (p ^ N) hnpos)
    have hrep : PrimRep (Smooth2 p q) (p ^ N * n) := by
      simpa only [PrimRep] using hN (p ^ N * n) hlarge
    exact (not_primRep_smooth2_pow_mul hp hq hpq hn N) hrep
  · intro h
    refine ⟨0, ?_⟩
    intro n _hn
    simpa only [PrimRep] using h n

private lemma finset_member_le_sum_id {t : Finset ℕ} {x : ℕ} (hx : x ∈ t) :
    x ≤ t.sum id := by
  simpa only [id_eq] using
    (Finset.single_le_sum (fun y _hy => Nat.zero_le y) hx)

private lemma smooth2_eq_one_of_bases_ge_three {p q x : ℕ}
    (hp : 3 ≤ p) (hq : 3 ≤ q) (hx : x ∈ Smooth2 p q) (hsmall : x ≤ 2) :
    x = 1 := by
  rcases hx with ⟨i, j, rfl⟩
  by_cases hi : i = 0
  · subst i
    by_cases hj : j = 0
    · simp [hj]
    · have hqpow : q ≤ q ^ j := Nat.le_pow (Nat.pos_of_ne_zero hj)
      simp only [pow_zero, one_mul] at hsmall
      omega
  · have hpPow : p ≤ p ^ i := Nat.le_pow (Nat.pos_of_ne_zero hi)
    have hPowPos : 0 < q ^ j := pow_pos (by omega) j
    have hleMul : p ^ i ≤ p ^ i * q ^ j := Nat.le_mul_of_pos_right _ hPowPos
    omega

private lemma smooth2_two_q_eq_one_or_two {q x : ℕ}
    (hq : 4 ≤ q) (hx : x ∈ Smooth2 2 q) (hsmall : x ≤ 3) :
    x = 1 ∨ x = 2 := by
  rcases hx with ⟨i, j, rfl⟩
  by_cases hj : j = 0
  · subst j
    simp only [pow_zero, mul_one] at hsmall ⊢
    have hi : i ≤ 1 := by
      by_contra hi
      have hi2 : 2 ≤ i := by omega
      have hfour : 2 ^ 2 ≤ 2 ^ i := Nat.pow_le_pow_right (by omega) hi2
      norm_num at hfour
      omega
    interval_cases i <;> simp
  · have hqPow : q ≤ q ^ j := Nat.le_pow (Nat.pos_of_ne_zero hj)
    have hTwoPowPos : 0 < 2 ^ i := pow_pos (by omega) i
    have hleMul : q ^ j ≤ 2 ^ i * q ^ j := Nat.le_mul_of_pos_left _ hTwoPowPos
    omega

/-- If both bases are at least three, target `2` is missing. -/
theorem not_primRep_smooth2_two {p q : ℕ} (hp : 3 ≤ p) (hq : 3 ≤ q) :
    ¬PrimRep (Smooth2 p q) 2 := by
  rintro ⟨t, htA, _htPrimitive, htSum⟩
  have htSub : t ⊆ {1} := by
    intro x hx
    have hxle : x ≤ 2 := by rw [← htSum]; exact finset_member_le_sum_id hx
    have hxone := smooth2_eq_one_of_bases_ge_three hp hq (htA x hx) hxle
    simpa [hxone]
  rcases Finset.subset_singleton_iff.mp htSub with rfl | rfl <;> simp at htSum

/-- For bases `2` and `q ≥ 4`, target `3` is missing. -/
theorem not_primRep_smooth2_three {q : ℕ} (hq : 4 ≤ q) :
    ¬PrimRep (Smooth2 2 q) 3 := by
  rintro ⟨t, htA, htPrimitive, htSum⟩
  have hlow : ∀ x ∈ t, x = 1 ∨ x = 2 := by
    intro x hx
    apply smooth2_two_q_eq_one_or_two hq (htA x hx)
    rw [← htSum]
    exact finset_member_le_sum_id hx
  have hcard : t.card ≤ 1 := Finset.card_le_one.mpr (by
    intro x hx y hy
    rcases hlow x hx with rfl | rfl
    · rcases hlow y hy with rfl | rfl
      · rfl
      · exact False.elim ((htPrimitive hx hy (by norm_num)) (by norm_num))
    · rcases hlow y hy with rfl | rfl
      · exact False.elim ((htPrimitive hy hx (by norm_num)) (by norm_num))
      · rfl)
  by_cases htEmpty : t = ∅
  · subst t
    simp at htSum
  · have htCardPos : 0 < t.card := Finset.card_pos.mpr (Finset.nonempty_iff_ne_empty.mpr htEmpty)
    have htCard : t.card = 1 := by omega
    rcases Finset.card_eq_one.mp htCard with ⟨x, rfl⟩
    have hxlow := hlow x (by simp)
    rcases hxlow with rfl | rfl <;> norm_num at htSum

/-- Complete classification of the negative two-base cases: apart from the
unordered pair `{2,3}`, a coprime pair cannot be d-complete. -/
theorem not_dComplete_smooth2_of_not_two_three {p q : ℕ}
    (hp : 1 < p) (hq : 1 < q) (hpq : Nat.Coprime p q)
    (hpair : ¬((p = 2 ∧ q = 3) ∨ (p = 3 ∧ q = 2))) :
    ¬IsDComplete (Smooth2 p q) := by
  intro hd
  have hall := (smooth2_dComplete_iff_all_primRep hp hq hpq).mp hd
  by_cases hp2 : p = 2
  · subst p
    have hq2 : q ≠ 2 := by
      intro h
      subst q
      norm_num at hpq
    have hq3 : q ≠ 3 := by
      intro h
      apply hpair
      exact Or.inl ⟨rfl, h⟩
    exact not_primRep_smooth2_three (by omega) (hall 3)
  · by_cases hq2 : q = 2
    · subst q
      have hp3 : p ≠ 3 := by
        intro h
        apply hpair
        exact Or.inr ⟨h, rfl⟩
      have hp_ge : 4 ≤ p := by omega
      have hmiss : ¬PrimRep (Smooth2 2 p) 3 := not_primRep_smooth2_three hp_ge
      apply hmiss
      simpa only [smooth2_comm p 2] using hall 3
    · exact not_primRep_smooth2_two (by omega) (by omega) (hall 2)

end Erdos123
