import Research.FundamentalCellCount
import Research.ZonotopeMeasure

/-!
# Packing square lattice points into the square-plus-cell zonotope
-/

open Set MeasureTheory Module Submodule
open scoped Pointwise ENNReal Matrix

namespace Research

/-- Fundamental cells based at lattice points in `[0,Y]²` are contained in the
four-generator zonotope generated by the two square edges and the basis. -/
theorem basis_square_cells_pack_in_zono
    (b : Basis (Fin 2) ℝ (Fin 2 → ℝ))
    (A : Finset (span ℤ (Set.range b))) {Y : ℝ}
    (hY : 0 < Y)
    (hpoint : ∀ g ∈ A, ∀ i, 0 ≤ (g : Fin 2 → ℝ) i ∧ (g : Fin 2 → ℝ) i ≤ Y) :
    (A.card : ℝ≥0∞) * volume (ZSpan.fundamentalDomain b) ≤
      volume (zono4 ![Y, 0] ![0, Y] (b 0) (b 1)) := by
  let E : Set (Fin 2 → ℝ) := zono4 ![Y, 0] ![0, Y] (b 0) (b 1)
  have hsub : (⋃ g ∈ A, g +ᵥ ZSpan.fundamentalDomain b) ⊆ E := by
    intro p hp
    rcases Set.mem_iUnion.mp hp with ⟨g, hp⟩
    rcases Set.mem_iUnion.mp hp with ⟨hg, hp⟩
    rcases Set.mem_vadd_set.mp hp with ⟨f, hf, rfl⟩
    let w : ℝ := (g : Fin 2 → ℝ) 0 / Y
    let x : ℝ := (g : Fin 2 → ℝ) 1 / Y
    let y : ℝ := b.repr f 0
    let z : ℝ := b.repr f 1
    have hw : w ∈ Set.Icc (0 : ℝ) 1 := by
      exact ⟨div_nonneg (hpoint g hg 0).1 hY.le,
        (div_le_one hY).mpr (hpoint g hg 0).2⟩
    have hx : x ∈ Set.Icc (0 : ℝ) 1 := by
      exact ⟨div_nonneg (hpoint g hg 1).1 hY.le,
        (div_le_one hY).mpr (hpoint g hg 1).2⟩
    have hy : y ∈ Set.Icc (0 : ℝ) 1 := by
      have h := ((ZSpan.mem_fundamentalDomain b).mp hf) 0
      exact ⟨h.1, h.2.le⟩
    have hz : z ∈ Set.Icc (0 : ℝ) 1 := by
      have h := ((ZSpan.mem_fundamentalDomain b).mp hf) 1
      exact ⟨h.1, h.2.le⟩
    change (g : Fin 2 → ℝ) + f ∈ E
    refine ⟨w, x, y, z, hw, hx, hy, hz, ?_⟩
    have hgexpand : (g : Fin 2 → ℝ) = w • ![Y, 0] + x • ![0, Y] := by
      ext i
      fin_cases i <;> dsimp [w, x] <;> field_simp <;> ring
    have hfexpand : f = y • b 0 + z • b 1 := by
      have hsum := b.sum_repr f
      rw [Fin.sum_univ_two] at hsum
      exact hsum.symm
    rw [hgexpand, hfexpand]
    module
  letI : VAddInvariantMeasure (span ℤ (Set.range b))
      (Fin 2 → ℝ) volume :=
    ⟨fun c s _ ↦ measure_preimage_add volume (c : Fin 2 → ℝ) s⟩
  exact fundamentalDomain_finset_card_mul_measure_le
    (ZSpan.isAddFundamentalDomain b volume) A hsub

/-- Combining the packing with the zonotope cover gives a sharp-leading
pair-area inequality for every real basis. -/
theorem basis_square_cells_pack_pair_areas
    (b : Basis (Fin 2) ℝ (Fin 2 → ℝ))
    (A : Finset (span ℤ (Set.range b))) {Y : ℝ}
    (hY : 0 < Y)
    (hpoint : ∀ g ∈ A, ∀ i, 0 ≤ (g : Fin 2 → ℝ) i ∧ (g : Fin 2 → ℝ) i ≤ Y) :
    (A.card : ℝ≥0∞) * volume (ZSpan.fundamentalDomain b) ≤
      volume (para ![Y, 0] ![0, Y]) +
        6 * volume (para ![Y, 0] (b 0)) +
        6 * volume (para ![0, Y] (b 0)) +
        4 * volume (para ![Y, 0] (b 1)) +
        4 * volume (para ![0, Y] (b 1)) +
        4 * volume (para (b 0) (b 1)) := by
  let a : Fin 2 → ℝ := ![Y, 0]
  let c : Fin 2 → ℝ := ![0, Y]
  let u : Fin 2 → ℝ := b 0
  let v : Fin 2 → ℝ := b 1
  have huac : u = (u 0 / Y) • a + (u 1 / Y) • c := by
    ext i
    fin_cases i <;> dsimp [a, c] <;> field_simp <;> ring
  have hvac : v = (v 0 / Y) • a + (v 1 / Y) • c := by
    ext i
    fin_cases i <;> dsimp [a, c] <;> field_simp <;> ring
  have hcuv : c = (b.repr c 0) • u + (b.repr c 1) • v := by
    have hsum := b.sum_repr c
    rw [Fin.sum_univ_two] at hsum
    exact hsum.symm
  have hauv : a = (b.repr a 0) • u + (b.repr a 1) • v := by
    have hsum := b.sum_repr a
    rw [Fin.sum_univ_two] at hsum
    exact hsum.symm
  have hpack := basis_square_cells_pack_in_zono b A hY hpoint
  have hzono := volume_zono4_le hvac huac hcuv hauv
  exact hpack.trans (by simpa [a, c, u, v] using hzono)

/-- The fundamental-cell factor in the preceding packing inequality is the
absolute determinant of the basis. -/
theorem volume_fundamentalDomain_eq_det
    (b : Basis (Fin 2) ℝ (Fin 2 → ℝ)) :
    volume.real (ZSpan.fundamentalDomain b) =
      |(Pi.basisFun ℝ (Fin 2)).det b| := by
  rw [ZSpan.measureReal_fundamentalDomain b volume (Pi.basisFun ℝ (Fin 2))]
  rw [ZSpan.fundamentalDomain_pi_basisFun]
  simp only [measureReal_def]
  rw [Real.volume_pi_Ico_toReal (by intro i; norm_num)]
  simp

lemma basisFun_det_pair (v w : Fin 2 → ℝ) :
    (Pi.basisFun ℝ (Fin 2)).det ![v, w] = v 0 * w 1 - v 1 * w 0 := by
  rw [Pi.basisFun_det]
  change Matrix.det ![v, w] = _
  rw [Matrix.det_fin_two]
  norm_num

/-- Real determinant form of `basis_square_cells_pack_pair_areas`. -/
theorem basis_square_card_mul_det_le_pair_dets
    (b : Basis (Fin 2) ℝ (Fin 2 → ℝ))
    (A : Finset (span ℤ (Set.range b))) {Y : ℝ}
    (hY : 0 < Y)
    (hpoint : ∀ g ∈ A, ∀ i, 0 ≤ (g : Fin 2 → ℝ) i ∧ (g : Fin 2 → ℝ) i ≤ Y) :
    (A.card : ℝ) * |(Pi.basisFun ℝ (Fin 2)).det ![b 0, b 1]| ≤
      |(Pi.basisFun ℝ (Fin 2)).det ![![Y, 0], ![0, Y]]| +
        6 * |(Pi.basisFun ℝ (Fin 2)).det ![![Y, 0], b 0]| +
        6 * |(Pi.basisFun ℝ (Fin 2)).det ![![0, Y], b 0]| +
        4 * |(Pi.basisFun ℝ (Fin 2)).det ![![Y, 0], b 1]| +
        4 * |(Pi.basisFun ℝ (Fin 2)).det ![![0, Y], b 1]| +
        4 * |(Pi.basisFun ℝ (Fin 2)).det ![b 0, b 1]| := by
  have h := basis_square_cells_pack_pair_areas b A hY hpoint
  have htop :
      volume (para ![Y, 0] ![0, Y]) +
        6 * volume (para ![Y, 0] (b 0)) +
        6 * volume (para ![0, Y] (b 0)) +
        4 * volume (para ![Y, 0] (b 1)) +
        4 * volume (para ![0, Y] (b 1)) +
        4 * volume (para (b 0) (b 1)) ≠ ∞ := by
    simp [volume_para, ENNReal.add_ne_top, ENNReal.mul_ne_top]
  have ht := ENNReal.toReal_mono htop h
  simp only [ENNReal.toReal_mul, ENNReal.toReal_natCast] at ht
  norm_num [volume_para, ENNReal.toReal_add, ENNReal.mul_ne_top] at ht
  have hbmat : Matrix.of (b : Fin 2 → Fin 2 → ℝ) = ![b 0, b 1] := by
    ext i j
    fin_cases i <;> rfl
  rw [hbmat] at ht
  simpa [Pi.basisFun_det, Matrix.det] using ht

/-- Sup height of a real vector in dimension two. -/
def supHeight2 (v : Fin 2 → ℝ) : ℝ := max |v 0| |v 1|

lemma abs_coord_le_supHeight2 (v : Fin 2 → ℝ) (i : Fin 2) :
    |v i| ≤ supHeight2 v := by
  fin_cases i
  · exact le_max_left _ _
  · exact le_max_right _ _

/-- Coordinate-height form of the sharp-leading basis count. -/
theorem basis_square_card_mul_det_le_height
    (b : Basis (Fin 2) ℝ (Fin 2 → ℝ))
    (A : Finset (span ℤ (Set.range b))) {Y : ℝ}
    (hY : 0 < Y)
    (hpoint : ∀ g ∈ A, ∀ i, 0 ≤ (g : Fin 2 → ℝ) i ∧ (g : Fin 2 → ℝ) i ≤ Y) :
    (A.card : ℝ) * |(Pi.basisFun ℝ (Fin 2)).det ![b 0, b 1]| ≤
      Y ^ 2 + 12 * Y * supHeight2 (b 0) +
        8 * Y * supHeight2 (b 1) +
        4 * |(Pi.basisFun ℝ (Fin 2)).det ![b 0, b 1]| := by
  have h := basis_square_card_mul_det_le_pair_dets b A hY hpoint
  simp only [basisFun_det_pair] at h ⊢
  have hYabs : |Y| = Y := abs_of_pos hY
  have hu0 := abs_coord_le_supHeight2 (b 0) 0
  have hu1 := abs_coord_le_supHeight2 (b 0) 1
  have hv0 := abs_coord_le_supHeight2 (b 1) 0
  have hv1 := abs_coord_le_supHeight2 (b 1) 1
  norm_num at h
  rw [hYabs] at h
  have hY0 := hY.le
  nlinarith

/-- Reduced-basis consequence: once the first basis vector has height `L`,
the second has height at most `D/L+2L`, and `L²≤D`, the square count has
error `O(Y/L+1)` with no corner term. -/
theorem reduced_basis_square_discrepancy
    (b : Basis (Fin 2) ℝ (Fin 2 → ℝ))
    (A : Finset (span ℤ (Set.range b))) {Y D L : ℝ}
    (hY : 0 < Y) (hD : 0 < D) (hL : 0 < L)
    (hdet : |(Pi.basisFun ℝ (Fin 2)).det ![b 0, b 1]| = D)
    (hu : supHeight2 (b 0) ≤ L)
    (hv : supHeight2 (b 1) ≤ D / L + 2 * L)
    (hmink : L ^ 2 ≤ D)
    (hpoint : ∀ g ∈ A, ∀ i, 0 ≤ (g : Fin 2 → ℝ) i ∧ (g : Fin 2 → ℝ) i ≤ Y) :
    (A.card : ℝ) ≤ Y ^ 2 / D + 36 * (Y / L) + 4 := by
  have hcount := basis_square_card_mul_det_le_height b A hY hpoint
  rw [hdet] at hcount
  have hY0 := hY.le
  have hL0 := hL.le
  have hD0 := hD.le
  have hND : (A.card : ℝ) * D ≤
      Y ^ 2 + 28 * Y * L + 8 * Y * (D / L) + 4 * D := by
    have hhu := mul_le_mul_of_nonneg_left hu (by positivity : (0 : ℝ) ≤ 12 * Y)
    have hhv := mul_le_mul_of_nonneg_left hv (by positivity : (0 : ℝ) ≤ 8 * Y)
    nlinarith
  have hLD : L / D ≤ 1 / L := by
    apply (div_le_div_iff₀ hD hL).mpr
    field_simp [ne_of_gt hL]
    nlinarith
  have hYL : Y * L / D ≤ Y / L := by
    calc
      Y * L / D = Y * (L / D) := by ring
      _ ≤ Y * (1 / L) := mul_le_mul_of_nonneg_left hLD hY0
      _ = Y / L := by ring
  have hdivide : (A.card : ℝ) ≤
      (Y ^ 2 + 28 * Y * L + 8 * Y * (D / L) + 4 * D) / D := by
    apply (le_div_iff₀ hD).mpr
    simpa [mul_comm] using hND
  calc
    (A.card : ℝ) ≤
        (Y ^ 2 + 28 * Y * L + 8 * Y * (D / L) + 4 * D) / D := hdivide
    _ = Y ^ 2 / D + 28 * (Y * L / D) + 8 * (Y / L) + 4 := by
      field_simp
    _ ≤ Y ^ 2 / D + 36 * (Y / L) + 4 := by nlinarith

end Research
