import Research.ForwardFace
import Mathlib.MeasureTheory.Measure.Haar.OfBasis

/-!
# Low-dimensional zonotope covers preserving the base parallelogram once
-/

open Set
open scoped Pointwise

namespace Research

variable {E : Type*} [AddCommGroup E] [Module ℝ E]

/-- Closed parallelogram generated by two vectors. -/
def para (a b : E) : Set E :=
  {p | ∃ x y : ℝ, x ∈ Set.Icc 0 1 ∧ y ∈ Set.Icc 0 1 ∧ p = x • a + y • b}

/-- Three-generator zonotope. -/
def zono3 (a b c : E) : Set E :=
  {p | ∃ x y z : ℝ, x ∈ Set.Icc 0 1 ∧ y ∈ Set.Icc 0 1 ∧ z ∈ Set.Icc 0 1 ∧
    p = x • a + y • b + z • c}

/-- Four-generator zonotope. -/
def zono4 (a b c d : E) : Set E :=
  {p | ∃ w x y z : ℝ, w ∈ Set.Icc 0 1 ∧ x ∈ Set.Icc 0 1 ∧
    y ∈ Set.Icc 0 1 ∧ z ∈ Set.Icc 0 1 ∧
    p = w • a + x • b + y • c + z • d}

lemma mem_vadd_para_iff (q a b c : E) :
    q ∈ a +ᵥ para b c ↔
      ∃ x y : ℝ, x ∈ Set.Icc 0 1 ∧ y ∈ Set.Icc 0 1 ∧
        q = a + x • b + y • c := by
  rw [Set.mem_vadd_set]
  constructor
  · rintro ⟨p, ⟨x, y, hx, hy, rfl⟩, rfl⟩
    exact ⟨x, y, hx, hy, by
      simp only [vadd_eq_add]
      exact (add_assoc _ _ _).symm⟩
  · rintro ⟨x, y, hx, hy, rfl⟩
    refine ⟨x • b + y • c, ⟨x, y, hx, hy, rfl⟩, ?_⟩
    simp only [vadd_eq_add]
    exact (add_assoc _ _ _).symm

/-- A 3-zonotope is covered by its base parallelogram and two translates of
each side parallelogram. -/
theorem zono3_subset_five_para {a b c : E} {α β : ℝ}
    (hc : c = α • a + β • b) :
    zono3 a b c ⊆
      para a b ∪ (para b c ∪ ((a +ᵥ para b c) ∪
        (para a c ∪ (b +ᵥ para a c)))) := by
  intro p hp
  rcases hp with ⟨x, y, z, hx, hy, hz, rfl⟩
  obtain ⟨t, ht0, htz, hX, hY, hface⟩ :=
    exists_forward_face hx hy hz (a := α) (b := β)
  let X := x + t * α
  let Y := y + t * β
  let Z := z - t
  have hZ : Z ∈ Set.Icc (0 : ℝ) 1 := by
    exact ⟨sub_nonneg.mpr htz, by dsimp [Z]; linarith [hz.2]⟩
  have hrewrite : x • a + y • b + z • c = X • a + Y • b + Z • c := by
    rw [hc]
    dsimp [X, Y, Z]
    module
  rw [hrewrite]
  rcases hface with htzEq | hX0 | hX1 | hY0 | hY1
  · have hZ0 : Z = 0 := by dsimp [Z]; linarith
    left
    exact ⟨X, Y, hX, hY, by simp [hZ0]⟩
  · right; left
    exact ⟨Y, Z, hY, hZ, by simp [X, hX0]⟩
  · right; right; left
    rw [mem_vadd_para_iff]
    exact ⟨Y, Z, hY, hZ, by simp [X, hX1, add_assoc]⟩
  · right; right; right; left
    exact ⟨X, Z, hX, hZ, by simp [Y, hY0]⟩
  · right; right; right; right
    rw [mem_vadd_para_iff]
    exact ⟨X, Z, hX, hZ, by simp [Y, hY1, add_assoc, add_comm, add_left_comm]⟩

/-- A 4-zonotope can be pushed either to its 3-generator base or to one of
four translated 3-generator side zonotopes. -/
theorem zono4_subset_five_zono3 {a b c d : E} {α β : ℝ}
    (hd : d = α • a + β • b) :
    zono4 a b c d ⊆
      zono3 a b c ∪ (zono3 b c d ∪ ((a +ᵥ zono3 b c d) ∪
        (zono3 a c d ∪ (b +ᵥ zono3 a c d)))) := by
  intro p hp
  rcases hp with ⟨w, x, y, z, hw, hx, hy, hz, rfl⟩
  obtain ⟨t, ht0, htz, hW, hX, hface⟩ :=
    exists_forward_face hw hx hz (a := α) (b := β)
  let W := w + t * α
  let X := x + t * β
  let Z := z - t
  have hZ : Z ∈ Set.Icc (0 : ℝ) 1 :=
    ⟨sub_nonneg.mpr htz, by dsimp [Z]; linarith [hz.2]⟩
  have hrewrite : w • a + x • b + y • c + z • d =
      W • a + X • b + y • c + Z • d := by
    rw [hd]
    dsimp [W, X, Z]
    module
  rw [hrewrite]
  rcases hface with htzEq | hW0 | hW1 | hX0 | hX1
  · have hZ0 : Z = 0 := by dsimp [Z]; linarith
    left
    exact ⟨W, X, y, hW, hX, hy, by simp [hZ0]⟩
  · right; left
    exact ⟨X, y, Z, hX, hy, hZ, by simp [W, hW0]⟩
  · right; right; left
    rw [Set.mem_vadd_set]
    refine ⟨X • b + y • c + Z • d,
      ⟨X, y, Z, hX, hy, hZ, rfl⟩, ?_⟩
    simp [W, hW1, vadd_eq_add, add_assoc]
  · right; right; right; left
    exact ⟨W, y, Z, hW, hy, hZ, by simp [X, hX0]⟩
  · right; right; right; right
    rw [Set.mem_vadd_set]
    refine ⟨W • a + y • c + Z • d,
      ⟨W, y, Z, hW, hy, hZ, rfl⟩, ?_⟩
    simp [X, hX1, vadd_eq_add, add_assoc, add_comm, add_left_comm]

end Research
